# coding: utf-8

"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from myescapeplan.models.discovery_budget import DiscoveryBudget
from myescapeplan.models.discovery_dates import DiscoveryDates
from myescapeplan.models.discovery_origin import DiscoveryOrigin
from myescapeplan.models.discovery_party import DiscoveryParty
from myescapeplan.models.discovery_preferences import DiscoveryPreferences
from myescapeplan.models.structured_flight import StructuredFlight
from myescapeplan.models.structured_stay import StructuredStay
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BusinessSearchCreateRequest(BaseModel):
    """
    Detached verified search over the shared Business travel intent.
    """ # noqa: E501
    budget: Optional[DiscoveryBudget] = None
    budget_tier: Optional[StrictStr] = None
    categories: Optional[Annotated[List[StrictStr], Field(max_length=10)]] = None
    currency: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=3)]] = None
    date_option_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=128)]] = None
    dates: Optional[DiscoveryDates] = None
    destination_airport_iata_codes: Optional[Annotated[List[StrictStr], Field(max_length=32)]] = None
    destination_ids: Optional[Annotated[List[UUID], Field(max_length=50)]] = None
    discovery_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=128)]] = None
    flight: Optional[StructuredFlight] = None
    include_images: Optional[StrictBool] = Field(default=True, description="Whether destination and offer image metadata should be included in results and details.")
    language: Optional[Annotated[str, Field(strict=True, max_length=10)]] = 'en'
    max_results: Optional[Annotated[int, Field(le=10, strict=True, ge=1)]] = 10
    opportunity_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=128)]] = None
    origin: Optional[DiscoveryOrigin] = None
    party: Optional[DiscoveryParty] = None
    preferences: Optional[DiscoveryPreferences] = None
    query: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = None
    stay: Optional[StructuredStay] = None
    __properties: ClassVar[List[str]] = ["budget", "budget_tier", "categories", "currency", "date_option_id", "dates", "destination_airport_iata_codes", "destination_ids", "discovery_id", "flight", "include_images", "language", "max_results", "opportunity_id", "origin", "party", "preferences", "query", "stay"]

    @field_validator('budget_tier')
    def budget_tier_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['budget', 'standard', 'premium']):
            raise ValueError("must be one of enum values ('budget', 'standard', 'premium')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BusinessSearchCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dates
        if self.dates:
            _dict['dates'] = self.dates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of flight
        if self.flight:
            _dict['flight'] = self.flight.to_dict()
        # override the default output from pydantic by calling `to_dict()` of origin
        if self.origin:
            _dict['origin'] = self.origin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of party
        if self.party:
            _dict['party'] = self.party.to_dict()
        # override the default output from pydantic by calling `to_dict()` of preferences
        if self.preferences:
            _dict['preferences'] = self.preferences.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stay
        if self.stay:
            _dict['stay'] = self.stay.to_dict()
        # set to None if budget (nullable) is None
        # and model_fields_set contains the field
        if self.budget is None and "budget" in self.model_fields_set:
            _dict['budget'] = None

        # set to None if budget_tier (nullable) is None
        # and model_fields_set contains the field
        if self.budget_tier is None and "budget_tier" in self.model_fields_set:
            _dict['budget_tier'] = None

        # set to None if categories (nullable) is None
        # and model_fields_set contains the field
        if self.categories is None and "categories" in self.model_fields_set:
            _dict['categories'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if date_option_id (nullable) is None
        # and model_fields_set contains the field
        if self.date_option_id is None and "date_option_id" in self.model_fields_set:
            _dict['date_option_id'] = None

        # set to None if dates (nullable) is None
        # and model_fields_set contains the field
        if self.dates is None and "dates" in self.model_fields_set:
            _dict['dates'] = None

        # set to None if discovery_id (nullable) is None
        # and model_fields_set contains the field
        if self.discovery_id is None and "discovery_id" in self.model_fields_set:
            _dict['discovery_id'] = None

        # set to None if flight (nullable) is None
        # and model_fields_set contains the field
        if self.flight is None and "flight" in self.model_fields_set:
            _dict['flight'] = None

        # set to None if opportunity_id (nullable) is None
        # and model_fields_set contains the field
        if self.opportunity_id is None and "opportunity_id" in self.model_fields_set:
            _dict['opportunity_id'] = None

        # set to None if origin (nullable) is None
        # and model_fields_set contains the field
        if self.origin is None and "origin" in self.model_fields_set:
            _dict['origin'] = None

        # set to None if query (nullable) is None
        # and model_fields_set contains the field
        if self.query is None and "query" in self.model_fields_set:
            _dict['query'] = None

        # set to None if stay (nullable) is None
        # and model_fields_set contains the field
        if self.stay is None and "stay" in self.model_fields_set:
            _dict['stay'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BusinessSearchCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "budget": DiscoveryBudget.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "budget_tier": obj.get("budget_tier"),
            "categories": obj.get("categories"),
            "currency": obj.get("currency"),
            "date_option_id": obj.get("date_option_id"),
            "dates": DiscoveryDates.from_dict(obj["dates"]) if obj.get("dates") is not None else None,
            "destination_airport_iata_codes": obj.get("destination_airport_iata_codes"),
            "destination_ids": obj.get("destination_ids"),
            "discovery_id": obj.get("discovery_id"),
            "flight": StructuredFlight.from_dict(obj["flight"]) if obj.get("flight") is not None else None,
            "include_images": obj.get("include_images") if obj.get("include_images") is not None else True,
            "language": obj.get("language") if obj.get("language") is not None else 'en',
            "max_results": obj.get("max_results") if obj.get("max_results") is not None else 10,
            "opportunity_id": obj.get("opportunity_id"),
            "origin": DiscoveryOrigin.from_dict(obj["origin"]) if obj.get("origin") is not None else None,
            "party": DiscoveryParty.from_dict(obj["party"]) if obj.get("party") is not None else None,
            "preferences": DiscoveryPreferences.from_dict(obj["preferences"]) if obj.get("preferences") is not None else None,
            "query": obj.get("query"),
            "stay": StructuredStay.from_dict(obj["stay"]) if obj.get("stay") is not None else None
        })
        return _obj


