# coding: utf-8

"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from myescapeplan.models.date_option_component_summary import DateOptionComponentSummary
from myescapeplan.models.date_option_kind import DateOptionKind
from myescapeplan.models.date_range import DateRange
from myescapeplan.models.price_insight import PriceInsight
from myescapeplan.models.trip_price import TripPrice
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BusinessDetailDateOption(BaseModel):
    """
    Date-option detail without the disabled event inventory track.
    """ # noqa: E501
    candidate_id: Optional[StrictStr] = None
    date_option_kind: Optional[DateOptionKind] = None
    dates: DateRange
    flight_summary: Optional[DateOptionComponentSummary] = None
    hotel_summary: Optional[DateOptionComponentSummary] = None
    price_insights: Optional[List[PriceInsight]] = None
    primary_price_insight: Optional[PriceInsight] = None
    rental_summary: Optional[DateOptionComponentSummary] = None
    required_categories: Optional[List[StrictStr]] = None
    status: Optional[StrictStr] = None
    total_price: Optional[TripPrice] = None
    __properties: ClassVar[List[str]] = ["candidate_id", "date_option_kind", "dates", "flight_summary", "hotel_summary", "price_insights", "primary_price_insight", "rental_summary", "required_categories", "status", "total_price"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BusinessDetailDateOption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dates
        if self.dates:
            _dict['dates'] = self.dates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of flight_summary
        if self.flight_summary:
            _dict['flight_summary'] = self.flight_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotel_summary
        if self.hotel_summary:
            _dict['hotel_summary'] = self.hotel_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in price_insights (list)
        _items = []
        if self.price_insights:
            for _item_price_insights in self.price_insights:
                if _item_price_insights:
                    _items.append(_item_price_insights.to_dict())
            _dict['price_insights'] = _items
        # override the default output from pydantic by calling `to_dict()` of primary_price_insight
        if self.primary_price_insight:
            _dict['primary_price_insight'] = self.primary_price_insight.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rental_summary
        if self.rental_summary:
            _dict['rental_summary'] = self.rental_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_price
        if self.total_price:
            _dict['total_price'] = self.total_price.to_dict()
        # set to None if candidate_id (nullable) is None
        # and model_fields_set contains the field
        if self.candidate_id is None and "candidate_id" in self.model_fields_set:
            _dict['candidate_id'] = None

        # set to None if date_option_kind (nullable) is None
        # and model_fields_set contains the field
        if self.date_option_kind is None and "date_option_kind" in self.model_fields_set:
            _dict['date_option_kind'] = None

        # set to None if flight_summary (nullable) is None
        # and model_fields_set contains the field
        if self.flight_summary is None and "flight_summary" in self.model_fields_set:
            _dict['flight_summary'] = None

        # set to None if hotel_summary (nullable) is None
        # and model_fields_set contains the field
        if self.hotel_summary is None and "hotel_summary" in self.model_fields_set:
            _dict['hotel_summary'] = None

        # set to None if primary_price_insight (nullable) is None
        # and model_fields_set contains the field
        if self.primary_price_insight is None and "primary_price_insight" in self.model_fields_set:
            _dict['primary_price_insight'] = None

        # set to None if rental_summary (nullable) is None
        # and model_fields_set contains the field
        if self.rental_summary is None and "rental_summary" in self.model_fields_set:
            _dict['rental_summary'] = None

        # set to None if required_categories (nullable) is None
        # and model_fields_set contains the field
        if self.required_categories is None and "required_categories" in self.model_fields_set:
            _dict['required_categories'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['total_price'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BusinessDetailDateOption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "candidate_id": obj.get("candidate_id"),
            "date_option_kind": obj.get("date_option_kind"),
            "dates": DateRange.from_dict(obj["dates"]) if obj.get("dates") is not None else None,
            "flight_summary": DateOptionComponentSummary.from_dict(obj["flight_summary"]) if obj.get("flight_summary") is not None else None,
            "hotel_summary": DateOptionComponentSummary.from_dict(obj["hotel_summary"]) if obj.get("hotel_summary") is not None else None,
            "price_insights": [PriceInsight.from_dict(_item) for _item in obj["price_insights"]] if obj.get("price_insights") is not None else None,
            "primary_price_insight": PriceInsight.from_dict(obj["primary_price_insight"]) if obj.get("primary_price_insight") is not None else None,
            "rental_summary": DateOptionComponentSummary.from_dict(obj["rental_summary"]) if obj.get("rental_summary") is not None else None,
            "required_categories": obj.get("required_categories"),
            "status": obj.get("status"),
            "total_price": TripPrice.from_dict(obj["total_price"]) if obj.get("total_price") is not None else None
        })
        return _obj


