# coding: utf-8

"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from myescapeplan.models.business_price import BusinessPrice
from myescapeplan.models.business_track_summary import BusinessTrackSummary
from myescapeplan.models.price_insight import PriceInsight
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BusinessDateOption(BaseModel):
    """
    BusinessDateOption
    """ # noqa: E501
    date_option_id: StrictStr
    date_type: Optional[StrictStr] = 'unknown'
    end_date: date
    flights: Optional[BusinessTrackSummary] = None
    hotels: Optional[BusinessTrackSummary] = None
    nights: Annotated[int, Field(strict=True, ge=1)]
    price_insights: Optional[List[PriceInsight]] = None
    pricing: Optional[BusinessPrice] = None
    primary_price_insight: Optional[PriceInsight] = None
    rentals: Optional[BusinessTrackSummary] = None
    start_date: date
    status: Optional[StrictStr] = 'pending'
    unpriced_reason: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["date_option_id", "date_type", "end_date", "flights", "hotels", "nights", "price_insights", "pricing", "primary_price_insight", "rentals", "start_date", "status", "unpriced_reason"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'available', 'partial', 'unavailable', 'failed', 'error', 'skipped']):
            raise ValueError("must be one of enum values ('pending', 'available', 'partial', 'unavailable', 'failed', 'error', 'skipped')")
        return value

    @field_validator('unpriced_reason')
    def unpriced_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['search_budget_reached']):
            raise ValueError("must be one of enum values ('search_budget_reached')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BusinessDateOption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of flights
        if self.flights:
            _dict['flights'] = self.flights.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotels
        if self.hotels:
            _dict['hotels'] = self.hotels.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in price_insights (list)
        _items = []
        if self.price_insights:
            for _item_price_insights in self.price_insights:
                if _item_price_insights:
                    _items.append(_item_price_insights.to_dict())
            _dict['price_insights'] = _items
        # override the default output from pydantic by calling `to_dict()` of pricing
        if self.pricing:
            _dict['pricing'] = self.pricing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of primary_price_insight
        if self.primary_price_insight:
            _dict['primary_price_insight'] = self.primary_price_insight.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rentals
        if self.rentals:
            _dict['rentals'] = self.rentals.to_dict()
        # set to None if flights (nullable) is None
        # and model_fields_set contains the field
        if self.flights is None and "flights" in self.model_fields_set:
            _dict['flights'] = None

        # set to None if hotels (nullable) is None
        # and model_fields_set contains the field
        if self.hotels is None and "hotels" in self.model_fields_set:
            _dict['hotels'] = None

        # set to None if pricing (nullable) is None
        # and model_fields_set contains the field
        if self.pricing is None and "pricing" in self.model_fields_set:
            _dict['pricing'] = None

        # set to None if primary_price_insight (nullable) is None
        # and model_fields_set contains the field
        if self.primary_price_insight is None and "primary_price_insight" in self.model_fields_set:
            _dict['primary_price_insight'] = None

        # set to None if rentals (nullable) is None
        # and model_fields_set contains the field
        if self.rentals is None and "rentals" in self.model_fields_set:
            _dict['rentals'] = None

        # set to None if unpriced_reason (nullable) is None
        # and model_fields_set contains the field
        if self.unpriced_reason is None and "unpriced_reason" in self.model_fields_set:
            _dict['unpriced_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BusinessDateOption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date_option_id": obj.get("date_option_id"),
            "date_type": obj.get("date_type") if obj.get("date_type") is not None else 'unknown',
            "end_date": obj.get("end_date"),
            "flights": BusinessTrackSummary.from_dict(obj["flights"]) if obj.get("flights") is not None else None,
            "hotels": BusinessTrackSummary.from_dict(obj["hotels"]) if obj.get("hotels") is not None else None,
            "nights": obj.get("nights"),
            "price_insights": [PriceInsight.from_dict(_item) for _item in obj["price_insights"]] if obj.get("price_insights") is not None else None,
            "pricing": BusinessPrice.from_dict(obj["pricing"]) if obj.get("pricing") is not None else None,
            "primary_price_insight": PriceInsight.from_dict(obj["primary_price_insight"]) if obj.get("primary_price_insight") is not None else None,
            "rentals": BusinessTrackSummary.from_dict(obj["rentals"]) if obj.get("rentals") is not None else None,
            "start_date": obj.get("start_date"),
            "status": obj.get("status") if obj.get("status") is not None else 'pending',
            "unpriced_reason": obj.get("unpriced_reason")
        })
        return _obj


