# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from myescapeplan.models.trip_price import TripPrice
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DateOptionComponentSummary(BaseModel):
    """
    Lightweight component inventory for one exact date option.  Component metadata is deliberately scoped to the DateOption instead of the destination card. This prevents a selected sibling date from displaying a flight/stay count or \"from\" price that belongs to another date variant.  Keep property/destination metadata such as amenities, images, descriptions, reviews, and static events OUT of this model. Those are deduped at their natural property/destination scope and selected by candidate/date identity.
    """ # noqa: E501
    min_price: Optional[TripPrice] = None
    option_count: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["min_price", "option_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DateOptionComponentSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of min_price
        if self.min_price:
            _dict['min_price'] = self.min_price.to_dict()
        # set to None if min_price (nullable) is None
        # and model_fields_set contains the field
        if self.min_price is None and "min_price" in self.model_fields_set:
            _dict['min_price'] = None

        # set to None if option_count (nullable) is None
        # and model_fields_set contains the field
        if self.option_count is None and "option_count" in self.model_fields_set:
            _dict['option_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DateOptionComponentSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "min_price": TripPrice.from_dict(obj["min_price"]) if obj.get("min_price") is not None else None,
            "option_count": obj.get("option_count")
        })
        return _obj


