# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DateOptionKind(str, Enum):
    """
    DateOptionKind
    """

    """
    allowed enum values
    """
    REQUESTED = 'requested'
    NEARBY = 'nearby'
    ALTERNATIVE = 'alternative'
    DEFAULTED = 'defaulted'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DateOptionKind from a JSON string"""
        return cls(json.loads(json_str))


