# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from myescapeplan.models.discovery_usage import DiscoveryUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DiscoveryMeta(BaseModel):
    """
    DiscoveryMeta
    """ # noqa: E501
    candidate_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = 0
    contract_version: Optional[StrictStr] = 'travel.discovery.v1'
    snapshot_version: Optional[StrictStr] = None
    usage: Optional[DiscoveryUsage] = None
    __properties: ClassVar[List[str]] = ["candidate_count", "contract_version", "snapshot_version", "usage"]

    @field_validator('contract_version')
    def contract_version_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['travel.discovery.v1']):
            raise ValueError("must be one of enum values ('travel.discovery.v1')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiscoveryMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # set to None if snapshot_version (nullable) is None
        # and model_fields_set contains the field
        if self.snapshot_version is None and "snapshot_version" in self.model_fields_set:
            _dict['snapshot_version'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiscoveryMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "candidate_count": obj.get("candidate_count") if obj.get("candidate_count") is not None else 0,
            "contract_version": obj.get("contract_version") if obj.get("contract_version") is not None else 'travel.discovery.v1',
            "snapshot_version": obj.get("snapshot_version"),
            "usage": DiscoveryUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        return _obj


