# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from myescapeplan.models.budget_amount import BudgetAmount
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DiscoveryInterpretation(BaseModel):
    """
    DiscoveryInterpretation
    """ # noqa: E501
    adults: Optional[StrictInt] = 1
    budget_amount: Optional[BudgetAmount] = None
    budget_currency: Optional[StrictStr] = None
    budget_scope: Optional[StrictStr] = None
    categories: Optional[List[StrictStr]] = None
    children: Optional[StrictInt] = 0
    date_mode: Optional[StrictStr] = None
    date_text: Optional[StrictStr] = None
    duration_nights: Optional[StrictInt] = None
    end_date: Optional[StrictStr] = None
    origin: Optional[StrictStr] = None
    start_date: Optional[StrictStr] = None
    title: StrictStr
    warnings: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["adults", "budget_amount", "budget_currency", "budget_scope", "categories", "children", "date_mode", "date_text", "duration_nights", "end_date", "origin", "start_date", "title", "warnings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiscoveryInterpretation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget_amount
        if self.budget_amount:
            _dict['budget_amount'] = self.budget_amount.to_dict()
        # set to None if budget_amount (nullable) is None
        # and model_fields_set contains the field
        if self.budget_amount is None and "budget_amount" in self.model_fields_set:
            _dict['budget_amount'] = None

        # set to None if budget_currency (nullable) is None
        # and model_fields_set contains the field
        if self.budget_currency is None and "budget_currency" in self.model_fields_set:
            _dict['budget_currency'] = None

        # set to None if budget_scope (nullable) is None
        # and model_fields_set contains the field
        if self.budget_scope is None and "budget_scope" in self.model_fields_set:
            _dict['budget_scope'] = None

        # set to None if date_mode (nullable) is None
        # and model_fields_set contains the field
        if self.date_mode is None and "date_mode" in self.model_fields_set:
            _dict['date_mode'] = None

        # set to None if date_text (nullable) is None
        # and model_fields_set contains the field
        if self.date_text is None and "date_text" in self.model_fields_set:
            _dict['date_text'] = None

        # set to None if duration_nights (nullable) is None
        # and model_fields_set contains the field
        if self.duration_nights is None and "duration_nights" in self.model_fields_set:
            _dict['duration_nights'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['end_date'] = None

        # set to None if origin (nullable) is None
        # and model_fields_set contains the field
        if self.origin is None and "origin" in self.model_fields_set:
            _dict['origin'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiscoveryInterpretation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "adults": obj.get("adults") if obj.get("adults") is not None else 1,
            "budget_amount": BudgetAmount.from_dict(obj["budget_amount"]) if obj.get("budget_amount") is not None else None,
            "budget_currency": obj.get("budget_currency"),
            "budget_scope": obj.get("budget_scope"),
            "categories": obj.get("categories"),
            "children": obj.get("children") if obj.get("children") is not None else 0,
            "date_mode": obj.get("date_mode"),
            "date_text": obj.get("date_text"),
            "duration_nights": obj.get("duration_nights"),
            "end_date": obj.get("end_date"),
            "origin": obj.get("origin"),
            "start_date": obj.get("start_date"),
            "title": obj.get("title"),
            "warnings": obj.get("warnings")
        })
        return _obj


