# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DiscoveryPreferences(BaseModel):
    """
    DiscoveryPreferences
    """ # noqa: E501
    activity_preferences: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    event_types: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    interests: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    pace: Optional[StrictStr] = None
    trip_dimensions: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    weather: Optional[Annotated[str, Field(strict=True, max_length=80)]] = None
    __properties: ClassVar[List[str]] = ["activity_preferences", "event_types", "interests", "pace", "trip_dimensions", "weather"]

    @field_validator('pace')
    def pace_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['relaxed', 'balanced', 'busy']):
            raise ValueError("must be one of enum values ('relaxed', 'balanced', 'busy')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiscoveryPreferences from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pace (nullable) is None
        # and model_fields_set contains the field
        if self.pace is None and "pace" in self.model_fields_set:
            _dict['pace'] = None

        # set to None if weather (nullable) is None
        # and model_fields_set contains the field
        if self.weather is None and "weather" in self.model_fields_set:
            _dict['weather'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiscoveryPreferences from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "activity_preferences": obj.get("activity_preferences"),
            "event_types": obj.get("event_types"),
            "interests": obj.get("interests"),
            "pace": obj.get("pace"),
            "trip_dimensions": obj.get("trip_dimensions"),
            "weather": obj.get("weather")
        })
        return _obj


