# coding: utf-8

"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from myescapeplan.models.discovery_date_option import DiscoveryDateOption
from myescapeplan.models.discovery_destination import DiscoveryDestination
from myescapeplan.models.discovery_fit import DiscoveryFit
from myescapeplan.models.discovery_search_inputs_available import DiscoverySearchInputsAvailable
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DiscoveryOpportunity(BaseModel):
    """
    DiscoveryOpportunity
    """ # noqa: E501
    date_options: Optional[List[DiscoveryDateOption]] = None
    destination: DiscoveryDestination
    destination_airport_iata_codes: Optional[Annotated[List[StrictStr], Field(max_length=32)]] = None
    fit: Optional[DiscoveryFit] = None
    opportunity_id: StrictStr
    origin_airport_iata_codes: Optional[Annotated[List[StrictStr], Field(max_length=32)]] = None
    rank: Annotated[int, Field(strict=True, ge=1)]
    reasons: Optional[List[StrictStr]] = None
    search_inputs_available: Optional[DiscoverySearchInputsAvailable] = None
    tags: Optional[List[StrictStr]] = None
    verification_status: Optional[StrictStr] = 'not_verified'
    __properties: ClassVar[List[str]] = ["date_options", "destination", "destination_airport_iata_codes", "fit", "opportunity_id", "origin_airport_iata_codes", "rank", "reasons", "search_inputs_available", "tags", "verification_status"]

    @field_validator('verification_status')
    def verification_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['not_verified']):
            raise ValueError("must be one of enum values ('not_verified')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiscoveryOpportunity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in date_options (list)
        _items = []
        if self.date_options:
            for _item_date_options in self.date_options:
                if _item_date_options:
                    _items.append(_item_date_options.to_dict())
            _dict['date_options'] = _items
        # override the default output from pydantic by calling `to_dict()` of destination
        if self.destination:
            _dict['destination'] = self.destination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fit
        if self.fit:
            _dict['fit'] = self.fit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of search_inputs_available
        if self.search_inputs_available:
            _dict['search_inputs_available'] = self.search_inputs_available.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiscoveryOpportunity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date_options": [DiscoveryDateOption.from_dict(_item) for _item in obj["date_options"]] if obj.get("date_options") is not None else None,
            "destination": DiscoveryDestination.from_dict(obj["destination"]) if obj.get("destination") is not None else None,
            "destination_airport_iata_codes": obj.get("destination_airport_iata_codes"),
            "fit": DiscoveryFit.from_dict(obj["fit"]) if obj.get("fit") is not None else None,
            "opportunity_id": obj.get("opportunity_id"),
            "origin_airport_iata_codes": obj.get("origin_airport_iata_codes"),
            "rank": obj.get("rank"),
            "reasons": obj.get("reasons"),
            "search_inputs_available": DiscoverySearchInputsAvailable.from_dict(obj["search_inputs_available"]) if obj.get("search_inputs_available") is not None else None,
            "tags": obj.get("tags"),
            "verification_status": obj.get("verification_status") if obj.get("verification_status") is not None else 'not_verified'
        })
        return _obj


