# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Money(BaseModel):
    """
    Internal Money representation. amount_minor: integer value of the currency (e.g., cents) currency: ISO 4217 currency code (e.g., \"USD\", \"EUR\") raw_text: original raw text string if available currency_source: source of currency inference (provider, symbol_inferred, unknown) currency_confidence: confidence level of inference
    """ # noqa: E501
    amount_minor: StrictInt
    currency: StrictStr
    currency_confidence: Optional[StrictStr] = 'low'
    currency_source: Optional[StrictStr] = 'unknown'
    raw_text: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["amount_minor", "currency", "currency_confidence", "currency_source", "raw_text"]

    @field_validator('currency_confidence')
    def currency_confidence_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['high', 'medium', 'low']):
            raise ValueError("must be one of enum values ('high', 'medium', 'low')")
        return value

    @field_validator('currency_source')
    def currency_source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['provider', 'symbol_inferred', 'default', 'unknown']):
            raise ValueError("must be one of enum values ('provider', 'symbol_inferred', 'default', 'unknown')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Money from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if raw_text (nullable) is None
        # and model_fields_set contains the field
        if self.raw_text is None and "raw_text" in self.model_fields_set:
            _dict['raw_text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Money from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount_minor": obj.get("amount_minor"),
            "currency": obj.get("currency"),
            "currency_confidence": obj.get("currency_confidence") if obj.get("currency_confidence") is not None else 'low',
            "currency_source": obj.get("currency_source") if obj.get("currency_source") is not None else 'unknown',
            "raw_text": obj.get("raw_text")
        })
        return _obj


