# coding: utf-8

"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from myescapeplan.models.price_basis import PriceBasis
from myescapeplan.models.price_insight_kind import PriceInsightKind
from myescapeplan.models.price_insight_scope import PriceInsightScope
from myescapeplan.models.price_insight_source import PriceInsightSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PriceInsight(BaseModel):
    """
    A truthful, display-ready claim about one exact price identity.
    """ # noqa: E501
    basis: PriceBasis
    change_amount: Optional[Union[StrictFloat, StrictInt]] = None
    change_percent: Optional[Union[StrictFloat, StrictInt]] = None
    comparison_key: StrictStr
    confidence: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)]
    current_amount: Union[Annotated[float, Field(strict=True, gt=0.0)], Annotated[int, Field(strict=True, gt=0)]]
    expires_at: Optional[datetime] = None
    explanation: StrictStr
    id: StrictStr
    is_new_low: Optional[StrictBool] = None
    kind: PriceInsightKind
    label: StrictStr
    observation_count: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    observed_at: datetime
    previous_amount: Optional[Union[Annotated[float, Field(strict=True, gt=0.0)], Annotated[int, Field(strict=True, gt=0)]]] = None
    provider_name: Optional[StrictStr] = None
    relative_band: Optional[StrictStr] = None
    scope: PriceInsightScope
    source: PriceInsightSource
    threshold_amount: Optional[Union[Annotated[float, Field(strict=True, gt=0.0)], Annotated[int, Field(strict=True, gt=0)]]] = None
    __properties: ClassVar[List[str]] = ["basis", "change_amount", "change_percent", "comparison_key", "confidence", "currency", "current_amount", "expires_at", "explanation", "id", "is_new_low", "kind", "label", "observation_count", "observed_at", "previous_amount", "provider_name", "relative_band", "scope", "source", "threshold_amount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PriceInsight from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if change_amount (nullable) is None
        # and model_fields_set contains the field
        if self.change_amount is None and "change_amount" in self.model_fields_set:
            _dict['change_amount'] = None

        # set to None if change_percent (nullable) is None
        # and model_fields_set contains the field
        if self.change_percent is None and "change_percent" in self.model_fields_set:
            _dict['change_percent'] = None

        # set to None if confidence (nullable) is None
        # and model_fields_set contains the field
        if self.confidence is None and "confidence" in self.model_fields_set:
            _dict['confidence'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if is_new_low (nullable) is None
        # and model_fields_set contains the field
        if self.is_new_low is None and "is_new_low" in self.model_fields_set:
            _dict['is_new_low'] = None

        # set to None if observation_count (nullable) is None
        # and model_fields_set contains the field
        if self.observation_count is None and "observation_count" in self.model_fields_set:
            _dict['observation_count'] = None

        # set to None if previous_amount (nullable) is None
        # and model_fields_set contains the field
        if self.previous_amount is None and "previous_amount" in self.model_fields_set:
            _dict['previous_amount'] = None

        # set to None if provider_name (nullable) is None
        # and model_fields_set contains the field
        if self.provider_name is None and "provider_name" in self.model_fields_set:
            _dict['provider_name'] = None

        # set to None if relative_band (nullable) is None
        # and model_fields_set contains the field
        if self.relative_band is None and "relative_band" in self.model_fields_set:
            _dict['relative_band'] = None

        # set to None if threshold_amount (nullable) is None
        # and model_fields_set contains the field
        if self.threshold_amount is None and "threshold_amount" in self.model_fields_set:
            _dict['threshold_amount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PriceInsight from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "basis": obj.get("basis"),
            "change_amount": obj.get("change_amount"),
            "change_percent": obj.get("change_percent"),
            "comparison_key": obj.get("comparison_key"),
            "confidence": obj.get("confidence"),
            "currency": obj.get("currency"),
            "current_amount": obj.get("current_amount"),
            "expires_at": obj.get("expires_at"),
            "explanation": obj.get("explanation"),
            "id": obj.get("id"),
            "is_new_low": obj.get("is_new_low"),
            "kind": obj.get("kind"),
            "label": obj.get("label"),
            "observation_count": obj.get("observation_count"),
            "observed_at": obj.get("observed_at"),
            "previous_amount": obj.get("previous_amount"),
            "provider_name": obj.get("provider_name"),
            "relative_band": obj.get("relative_band"),
            "scope": obj.get("scope"),
            "source": obj.get("source"),
            "threshold_amount": obj.get("threshold_amount")
        })
        return _obj


