# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PriceBasis(str, Enum):
    """
    PriceBasis
    """

    """
    allowed enum values
    """
    ONE_WAY_PER_TRAVELLER = 'one_way_per_traveller'
    RETURN_PER_TRAVELLER = 'return_per_traveller'
    FLIGHT_PARTY_TOTAL = 'flight_party_total'
    ACCOMMODATION_PER_NIGHT = 'accommodation_per_night'
    ACCOMMODATION_PER_GUEST = 'accommodation_per_guest'
    ACCOMMODATION_TOTAL = 'accommodation_total'
    BUNDLE_PER_TRAVELLER = 'bundle_per_traveller'
    BUNDLE_PARTY_TOTAL = 'bundle_party_total'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PriceBasis from a JSON string"""
        return cls(json.loads(json_str))


