# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from myescapeplan.models.price_insight import PriceInsight
from myescapeplan.models.provider_url import ProviderUrl
from myescapeplan.models.standardized_flight_leg import StandardizedFlightLeg
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SlimStandardizedFlightOffer(BaseModel):
    """
    SlimStandardizedFlightOffer
    """ # noqa: E501
    can_unlock_return: Optional[StrictBool] = False
    currency: Optional[StrictStr] = None
    emissions_grams_co2e: Optional[StrictInt] = None
    emissions_level: Optional[StrictStr] = None
    legs: List[StandardizedFlightLeg]
    marketing_carriers: Optional[List[StrictStr]] = None
    max_segment_duration_minutes: Optional[StrictInt] = None
    offer_id: StrictStr
    operating_carriers: Optional[List[StrictStr]] = None
    outbound_selection_id: Optional[StrictStr] = None
    price_breakdown: Optional[Dict[str, StrictInt]] = None
    price_insights: Optional[List[PriceInsight]] = None
    price_provenance: StrictStr
    price_total: Optional[Union[StrictFloat, StrictInt]] = None
    primary_price_insight: Optional[PriceInsight] = None
    provider: StrictStr
    provider_urls: Optional[List[ProviderUrl]] = None
    total_duration_minutes: Optional[StrictInt] = None
    trip_type: StrictStr
    __properties: ClassVar[List[str]] = ["can_unlock_return", "currency", "emissions_grams_co2e", "emissions_level", "legs", "marketing_carriers", "max_segment_duration_minutes", "offer_id", "operating_carriers", "outbound_selection_id", "price_breakdown", "price_insights", "price_provenance", "price_total", "primary_price_insight", "provider", "provider_urls", "total_duration_minutes", "trip_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SlimStandardizedFlightOffer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in legs (list)
        _items = []
        if self.legs:
            for _item_legs in self.legs:
                if _item_legs:
                    _items.append(_item_legs.to_dict())
            _dict['legs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in price_insights (list)
        _items = []
        if self.price_insights:
            for _item_price_insights in self.price_insights:
                if _item_price_insights:
                    _items.append(_item_price_insights.to_dict())
            _dict['price_insights'] = _items
        # override the default output from pydantic by calling `to_dict()` of primary_price_insight
        if self.primary_price_insight:
            _dict['primary_price_insight'] = self.primary_price_insight.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in provider_urls (list)
        _items = []
        if self.provider_urls:
            for _item_provider_urls in self.provider_urls:
                if _item_provider_urls:
                    _items.append(_item_provider_urls.to_dict())
            _dict['provider_urls'] = _items
        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if emissions_grams_co2e (nullable) is None
        # and model_fields_set contains the field
        if self.emissions_grams_co2e is None and "emissions_grams_co2e" in self.model_fields_set:
            _dict['emissions_grams_co2e'] = None

        # set to None if emissions_level (nullable) is None
        # and model_fields_set contains the field
        if self.emissions_level is None and "emissions_level" in self.model_fields_set:
            _dict['emissions_level'] = None

        # set to None if max_segment_duration_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.max_segment_duration_minutes is None and "max_segment_duration_minutes" in self.model_fields_set:
            _dict['max_segment_duration_minutes'] = None

        # set to None if outbound_selection_id (nullable) is None
        # and model_fields_set contains the field
        if self.outbound_selection_id is None and "outbound_selection_id" in self.model_fields_set:
            _dict['outbound_selection_id'] = None

        # set to None if price_breakdown (nullable) is None
        # and model_fields_set contains the field
        if self.price_breakdown is None and "price_breakdown" in self.model_fields_set:
            _dict['price_breakdown'] = None

        # set to None if price_total (nullable) is None
        # and model_fields_set contains the field
        if self.price_total is None and "price_total" in self.model_fields_set:
            _dict['price_total'] = None

        # set to None if primary_price_insight (nullable) is None
        # and model_fields_set contains the field
        if self.primary_price_insight is None and "primary_price_insight" in self.model_fields_set:
            _dict['primary_price_insight'] = None

        # set to None if total_duration_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.total_duration_minutes is None and "total_duration_minutes" in self.model_fields_set:
            _dict['total_duration_minutes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SlimStandardizedFlightOffer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "can_unlock_return": obj.get("can_unlock_return") if obj.get("can_unlock_return") is not None else False,
            "currency": obj.get("currency"),
            "emissions_grams_co2e": obj.get("emissions_grams_co2e"),
            "emissions_level": obj.get("emissions_level"),
            "legs": [StandardizedFlightLeg.from_dict(_item) for _item in obj["legs"]] if obj.get("legs") is not None else None,
            "marketing_carriers": obj.get("marketing_carriers"),
            "max_segment_duration_minutes": obj.get("max_segment_duration_minutes"),
            "offer_id": obj.get("offer_id"),
            "operating_carriers": obj.get("operating_carriers"),
            "outbound_selection_id": obj.get("outbound_selection_id"),
            "price_breakdown": obj.get("price_breakdown"),
            "price_insights": [PriceInsight.from_dict(_item) for _item in obj["price_insights"]] if obj.get("price_insights") is not None else None,
            "price_provenance": obj.get("price_provenance"),
            "price_total": obj.get("price_total"),
            "primary_price_insight": PriceInsight.from_dict(obj["primary_price_insight"]) if obj.get("primary_price_insight") is not None else None,
            "provider": obj.get("provider"),
            "provider_urls": [ProviderUrl.from_dict(_item) for _item in obj["provider_urls"]] if obj.get("provider_urls") is not None else None,
            "total_duration_minutes": obj.get("total_duration_minutes"),
            "trip_type": obj.get("trip_type")
        })
        return _obj


