# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from myescapeplan.models.image_object import ImageObject
from myescapeplan.models.price_insight import PriceInsight
from myescapeplan.models.provider_url import ProviderUrl
from myescapeplan.models.standardized_stay_offer import StandardizedStayOffer
from myescapeplan.models.stay_deal_signal import StayDealSignal
from myescapeplan.models.stay_nearby_place import StayNearbyPlace
from myescapeplan.models.stay_rating_bucket import StayRatingBucket
from myescapeplan.models.stay_review_topic import StayReviewTopic
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SlimStandardizedStay(BaseModel):
    """
    SlimStandardizedStay
    """ # noqa: E501
    address: Optional[StrictStr] = None
    amenity_types: Optional[List[StrictStr]] = None
    bathrooms_min: Optional[StrictInt] = None
    bedrooms_min: Optional[StrictInt] = None
    check_in_time: Optional[StrictStr] = None
    check_out_time: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    country_code: Optional[StrictStr] = None
    deal: Optional[StayDealSignal] = None
    description: Optional[StrictStr] = None
    distance_from_beach_km: Optional[Union[StrictFloat, StrictInt]] = None
    eco_certified: Optional[StrictBool] = None
    free_cancellation: Optional[StrictBool] = None
    hotel_class: Optional[StrictInt] = None
    id: StrictStr
    images: Optional[List[ImageObject]] = None
    is_vacation_rental: StrictBool
    lat: Optional[Union[StrictFloat, StrictInt]] = None
    location_rating: Optional[Union[StrictFloat, StrictInt]] = None
    lon: Optional[Union[StrictFloat, StrictInt]] = None
    name: StrictStr
    nearby_places: Optional[List[StayNearbyPlace]] = None
    offer_snapshot: Optional[StandardizedStayOffer] = None
    price_insights: Optional[List[PriceInsight]] = None
    primary_price_insight: Optional[PriceInsight] = None
    property_token: Optional[StrictStr] = None
    property_type: Optional[StrictStr] = None
    provider: StrictStr
    provider_property_id: StrictStr
    provider_urls: Optional[List[ProviderUrl]] = None
    rating_bucket: Optional[StrictStr] = None
    rating_count: Optional[StrictInt] = None
    rating_distribution: Optional[List[StayRatingBucket]] = None
    rating_value: Optional[Union[StrictFloat, StrictInt]] = None
    raw_amenities: Optional[List[StrictStr]] = None
    region: Optional[StrictStr] = None
    review_topics: Optional[List[StayReviewTopic]] = None
    sleeps: Optional[StrictInt] = None
    special_offers: Optional[StrictBool] = None
    stay_kind: StrictStr
    __properties: ClassVar[List[str]] = ["address", "amenity_types", "bathrooms_min", "bedrooms_min", "check_in_time", "check_out_time", "city", "country_code", "deal", "description", "distance_from_beach_km", "eco_certified", "free_cancellation", "hotel_class", "id", "images", "is_vacation_rental", "lat", "location_rating", "lon", "name", "nearby_places", "offer_snapshot", "price_insights", "primary_price_insight", "property_token", "property_type", "provider", "provider_property_id", "provider_urls", "rating_bucket", "rating_count", "rating_distribution", "rating_value", "raw_amenities", "region", "review_topics", "sleeps", "special_offers", "stay_kind"]

    @field_validator('property_type')
    def property_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['hotel', 'hostel', 'resort', 'motel', 'inn', 'bed_and_breakfast', 'apartment_hotel', 'apartment', 'guest_house', 'villa', 'ryokan', 'minshuku', 'vacation_rental', 'other']):
            raise ValueError("must be one of enum values ('hotel', 'hostel', 'resort', 'motel', 'inn', 'bed_and_breakfast', 'apartment_hotel', 'apartment', 'guest_house', 'villa', 'ryokan', 'minshuku', 'vacation_rental', 'other')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SlimStandardizedStay from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of deal
        if self.deal:
            _dict['deal'] = self.deal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in images (list)
        _items = []
        if self.images:
            for _item_images in self.images:
                if _item_images:
                    _items.append(_item_images.to_dict())
            _dict['images'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in nearby_places (list)
        _items = []
        if self.nearby_places:
            for _item_nearby_places in self.nearby_places:
                if _item_nearby_places:
                    _items.append(_item_nearby_places.to_dict())
            _dict['nearby_places'] = _items
        # override the default output from pydantic by calling `to_dict()` of offer_snapshot
        if self.offer_snapshot:
            _dict['offer_snapshot'] = self.offer_snapshot.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in price_insights (list)
        _items = []
        if self.price_insights:
            for _item_price_insights in self.price_insights:
                if _item_price_insights:
                    _items.append(_item_price_insights.to_dict())
            _dict['price_insights'] = _items
        # override the default output from pydantic by calling `to_dict()` of primary_price_insight
        if self.primary_price_insight:
            _dict['primary_price_insight'] = self.primary_price_insight.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in provider_urls (list)
        _items = []
        if self.provider_urls:
            for _item_provider_urls in self.provider_urls:
                if _item_provider_urls:
                    _items.append(_item_provider_urls.to_dict())
            _dict['provider_urls'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rating_distribution (list)
        _items = []
        if self.rating_distribution:
            for _item_rating_distribution in self.rating_distribution:
                if _item_rating_distribution:
                    _items.append(_item_rating_distribution.to_dict())
            _dict['rating_distribution'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in review_topics (list)
        _items = []
        if self.review_topics:
            for _item_review_topics in self.review_topics:
                if _item_review_topics:
                    _items.append(_item_review_topics.to_dict())
            _dict['review_topics'] = _items
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if bathrooms_min (nullable) is None
        # and model_fields_set contains the field
        if self.bathrooms_min is None and "bathrooms_min" in self.model_fields_set:
            _dict['bathrooms_min'] = None

        # set to None if bedrooms_min (nullable) is None
        # and model_fields_set contains the field
        if self.bedrooms_min is None and "bedrooms_min" in self.model_fields_set:
            _dict['bedrooms_min'] = None

        # set to None if check_in_time (nullable) is None
        # and model_fields_set contains the field
        if self.check_in_time is None and "check_in_time" in self.model_fields_set:
            _dict['check_in_time'] = None

        # set to None if check_out_time (nullable) is None
        # and model_fields_set contains the field
        if self.check_out_time is None and "check_out_time" in self.model_fields_set:
            _dict['check_out_time'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if country_code (nullable) is None
        # and model_fields_set contains the field
        if self.country_code is None and "country_code" in self.model_fields_set:
            _dict['country_code'] = None

        # set to None if deal (nullable) is None
        # and model_fields_set contains the field
        if self.deal is None and "deal" in self.model_fields_set:
            _dict['deal'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if distance_from_beach_km (nullable) is None
        # and model_fields_set contains the field
        if self.distance_from_beach_km is None and "distance_from_beach_km" in self.model_fields_set:
            _dict['distance_from_beach_km'] = None

        # set to None if eco_certified (nullable) is None
        # and model_fields_set contains the field
        if self.eco_certified is None and "eco_certified" in self.model_fields_set:
            _dict['eco_certified'] = None

        # set to None if free_cancellation (nullable) is None
        # and model_fields_set contains the field
        if self.free_cancellation is None and "free_cancellation" in self.model_fields_set:
            _dict['free_cancellation'] = None

        # set to None if hotel_class (nullable) is None
        # and model_fields_set contains the field
        if self.hotel_class is None and "hotel_class" in self.model_fields_set:
            _dict['hotel_class'] = None

        # set to None if images (nullable) is None
        # and model_fields_set contains the field
        if self.images is None and "images" in self.model_fields_set:
            _dict['images'] = None

        # set to None if lat (nullable) is None
        # and model_fields_set contains the field
        if self.lat is None and "lat" in self.model_fields_set:
            _dict['lat'] = None

        # set to None if location_rating (nullable) is None
        # and model_fields_set contains the field
        if self.location_rating is None and "location_rating" in self.model_fields_set:
            _dict['location_rating'] = None

        # set to None if lon (nullable) is None
        # and model_fields_set contains the field
        if self.lon is None and "lon" in self.model_fields_set:
            _dict['lon'] = None

        # set to None if offer_snapshot (nullable) is None
        # and model_fields_set contains the field
        if self.offer_snapshot is None and "offer_snapshot" in self.model_fields_set:
            _dict['offer_snapshot'] = None

        # set to None if primary_price_insight (nullable) is None
        # and model_fields_set contains the field
        if self.primary_price_insight is None and "primary_price_insight" in self.model_fields_set:
            _dict['primary_price_insight'] = None

        # set to None if property_token (nullable) is None
        # and model_fields_set contains the field
        if self.property_token is None and "property_token" in self.model_fields_set:
            _dict['property_token'] = None

        # set to None if property_type (nullable) is None
        # and model_fields_set contains the field
        if self.property_type is None and "property_type" in self.model_fields_set:
            _dict['property_type'] = None

        # set to None if rating_bucket (nullable) is None
        # and model_fields_set contains the field
        if self.rating_bucket is None and "rating_bucket" in self.model_fields_set:
            _dict['rating_bucket'] = None

        # set to None if rating_count (nullable) is None
        # and model_fields_set contains the field
        if self.rating_count is None and "rating_count" in self.model_fields_set:
            _dict['rating_count'] = None

        # set to None if rating_value (nullable) is None
        # and model_fields_set contains the field
        if self.rating_value is None and "rating_value" in self.model_fields_set:
            _dict['rating_value'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['region'] = None

        # set to None if sleeps (nullable) is None
        # and model_fields_set contains the field
        if self.sleeps is None and "sleeps" in self.model_fields_set:
            _dict['sleeps'] = None

        # set to None if special_offers (nullable) is None
        # and model_fields_set contains the field
        if self.special_offers is None and "special_offers" in self.model_fields_set:
            _dict['special_offers'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SlimStandardizedStay from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "amenity_types": obj.get("amenity_types"),
            "bathrooms_min": obj.get("bathrooms_min"),
            "bedrooms_min": obj.get("bedrooms_min"),
            "check_in_time": obj.get("check_in_time"),
            "check_out_time": obj.get("check_out_time"),
            "city": obj.get("city"),
            "country_code": obj.get("country_code"),
            "deal": StayDealSignal.from_dict(obj["deal"]) if obj.get("deal") is not None else None,
            "description": obj.get("description"),
            "distance_from_beach_km": obj.get("distance_from_beach_km"),
            "eco_certified": obj.get("eco_certified"),
            "free_cancellation": obj.get("free_cancellation"),
            "hotel_class": obj.get("hotel_class"),
            "id": obj.get("id"),
            "images": [ImageObject.from_dict(_item) for _item in obj["images"]] if obj.get("images") is not None else None,
            "is_vacation_rental": obj.get("is_vacation_rental"),
            "lat": obj.get("lat"),
            "location_rating": obj.get("location_rating"),
            "lon": obj.get("lon"),
            "name": obj.get("name"),
            "nearby_places": [StayNearbyPlace.from_dict(_item) for _item in obj["nearby_places"]] if obj.get("nearby_places") is not None else None,
            "offer_snapshot": StandardizedStayOffer.from_dict(obj["offer_snapshot"]) if obj.get("offer_snapshot") is not None else None,
            "price_insights": [PriceInsight.from_dict(_item) for _item in obj["price_insights"]] if obj.get("price_insights") is not None else None,
            "primary_price_insight": PriceInsight.from_dict(obj["primary_price_insight"]) if obj.get("primary_price_insight") is not None else None,
            "property_token": obj.get("property_token"),
            "property_type": obj.get("property_type"),
            "provider": obj.get("provider"),
            "provider_property_id": obj.get("provider_property_id"),
            "provider_urls": [ProviderUrl.from_dict(_item) for _item in obj["provider_urls"]] if obj.get("provider_urls") is not None else None,
            "rating_bucket": obj.get("rating_bucket"),
            "rating_count": obj.get("rating_count"),
            "rating_distribution": [StayRatingBucket.from_dict(_item) for _item in obj["rating_distribution"]] if obj.get("rating_distribution") is not None else None,
            "rating_value": obj.get("rating_value"),
            "raw_amenities": obj.get("raw_amenities"),
            "region": obj.get("region"),
            "review_topics": [StayReviewTopic.from_dict(_item) for _item in obj["review_topics"]] if obj.get("review_topics") is not None else None,
            "sleeps": obj.get("sleeps"),
            "special_offers": obj.get("special_offers"),
            "stay_kind": obj.get("stay_kind")
        })
        return _obj


