# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from myescapeplan.models.money import Money
from myescapeplan.models.provider_url import ProviderUrl
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StandardizedEvent(BaseModel):
    """
    Provider-normalized event representation.
    """ # noqa: E501
    address: Optional[StrictStr] = None
    category: Optional[StrictStr] = None
    date_unverified: Optional[StrictBool] = False
    debug_info: Optional[Dict[str, Any]] = None
    description: Optional[StrictStr] = None
    duration_minutes: Optional[StrictInt] = None
    end: Optional[datetime] = None
    experience_type: Optional[StrictStr] = None
    fx_as_of: Optional[date] = None
    geo_unverified: Optional[StrictBool] = False
    id: Optional[StrictStr] = None
    image_url: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    image_urls: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = None
    is_approx: Optional[StrictBool] = False
    is_time_bounded: Optional[StrictBool] = True
    kind: Optional[StrictStr] = 'event'
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    location_name: Optional[StrictStr] = None
    location_ref: Optional[StrictStr] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    money_display: Optional[Money] = None
    money_original: Optional[Money] = None
    price_note: Optional[StrictStr] = None
    provider: Optional[StrictStr] = None
    provider_product_id: Optional[StrictStr] = None
    provider_urls: Optional[List[ProviderUrl]] = None
    rating: Optional[Union[StrictFloat, StrictInt]] = None
    reviews: Optional[StrictInt] = None
    start: Optional[datetime] = None
    ticket_url: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    timezone: Optional[StrictStr] = None
    title: StrictStr
    venue: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["address", "category", "date_unverified", "debug_info", "description", "duration_minutes", "end", "experience_type", "fx_as_of", "geo_unverified", "id", "image_url", "image_urls", "is_approx", "is_time_bounded", "kind", "latitude", "location_name", "location_ref", "longitude", "money_display", "money_original", "price_note", "provider", "provider_product_id", "provider_urls", "rating", "reviews", "start", "ticket_url", "timezone", "title", "venue"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['event', 'activity']):
            raise ValueError("must be one of enum values ('event', 'activity')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StandardizedEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of money_display
        if self.money_display:
            _dict['money_display'] = self.money_display.to_dict()
        # override the default output from pydantic by calling `to_dict()` of money_original
        if self.money_original:
            _dict['money_original'] = self.money_original.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in provider_urls (list)
        _items = []
        if self.provider_urls:
            for _item_provider_urls in self.provider_urls:
                if _item_provider_urls:
                    _items.append(_item_provider_urls.to_dict())
            _dict['provider_urls'] = _items
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict['category'] = None

        # set to None if debug_info (nullable) is None
        # and model_fields_set contains the field
        if self.debug_info is None and "debug_info" in self.model_fields_set:
            _dict['debug_info'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if duration_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.duration_minutes is None and "duration_minutes" in self.model_fields_set:
            _dict['duration_minutes'] = None

        # set to None if end (nullable) is None
        # and model_fields_set contains the field
        if self.end is None and "end" in self.model_fields_set:
            _dict['end'] = None

        # set to None if experience_type (nullable) is None
        # and model_fields_set contains the field
        if self.experience_type is None and "experience_type" in self.model_fields_set:
            _dict['experience_type'] = None

        # set to None if fx_as_of (nullable) is None
        # and model_fields_set contains the field
        if self.fx_as_of is None and "fx_as_of" in self.model_fields_set:
            _dict['fx_as_of'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['image_url'] = None

        # set to None if latitude (nullable) is None
        # and model_fields_set contains the field
        if self.latitude is None and "latitude" in self.model_fields_set:
            _dict['latitude'] = None

        # set to None if location_name (nullable) is None
        # and model_fields_set contains the field
        if self.location_name is None and "location_name" in self.model_fields_set:
            _dict['location_name'] = None

        # set to None if location_ref (nullable) is None
        # and model_fields_set contains the field
        if self.location_ref is None and "location_ref" in self.model_fields_set:
            _dict['location_ref'] = None

        # set to None if longitude (nullable) is None
        # and model_fields_set contains the field
        if self.longitude is None and "longitude" in self.model_fields_set:
            _dict['longitude'] = None

        # set to None if money_display (nullable) is None
        # and model_fields_set contains the field
        if self.money_display is None and "money_display" in self.model_fields_set:
            _dict['money_display'] = None

        # set to None if money_original (nullable) is None
        # and model_fields_set contains the field
        if self.money_original is None and "money_original" in self.model_fields_set:
            _dict['money_original'] = None

        # set to None if price_note (nullable) is None
        # and model_fields_set contains the field
        if self.price_note is None and "price_note" in self.model_fields_set:
            _dict['price_note'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if provider_product_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_product_id is None and "provider_product_id" in self.model_fields_set:
            _dict['provider_product_id'] = None

        # set to None if rating (nullable) is None
        # and model_fields_set contains the field
        if self.rating is None and "rating" in self.model_fields_set:
            _dict['rating'] = None

        # set to None if reviews (nullable) is None
        # and model_fields_set contains the field
        if self.reviews is None and "reviews" in self.model_fields_set:
            _dict['reviews'] = None

        # set to None if start (nullable) is None
        # and model_fields_set contains the field
        if self.start is None and "start" in self.model_fields_set:
            _dict['start'] = None

        # set to None if ticket_url (nullable) is None
        # and model_fields_set contains the field
        if self.ticket_url is None and "ticket_url" in self.model_fields_set:
            _dict['ticket_url'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        # set to None if venue (nullable) is None
        # and model_fields_set contains the field
        if self.venue is None and "venue" in self.model_fields_set:
            _dict['venue'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StandardizedEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "category": obj.get("category"),
            "date_unverified": obj.get("date_unverified") if obj.get("date_unverified") is not None else False,
            "debug_info": obj.get("debug_info"),
            "description": obj.get("description"),
            "duration_minutes": obj.get("duration_minutes"),
            "end": obj.get("end"),
            "experience_type": obj.get("experience_type"),
            "fx_as_of": obj.get("fx_as_of"),
            "geo_unverified": obj.get("geo_unverified") if obj.get("geo_unverified") is not None else False,
            "id": obj.get("id"),
            "image_url": obj.get("image_url"),
            "image_urls": obj.get("image_urls"),
            "is_approx": obj.get("is_approx") if obj.get("is_approx") is not None else False,
            "is_time_bounded": obj.get("is_time_bounded") if obj.get("is_time_bounded") is not None else True,
            "kind": obj.get("kind") if obj.get("kind") is not None else 'event',
            "latitude": obj.get("latitude"),
            "location_name": obj.get("location_name"),
            "location_ref": obj.get("location_ref"),
            "longitude": obj.get("longitude"),
            "money_display": Money.from_dict(obj["money_display"]) if obj.get("money_display") is not None else None,
            "money_original": Money.from_dict(obj["money_original"]) if obj.get("money_original") is not None else None,
            "price_note": obj.get("price_note"),
            "provider": obj.get("provider"),
            "provider_product_id": obj.get("provider_product_id"),
            "provider_urls": [ProviderUrl.from_dict(_item) for _item in obj["provider_urls"]] if obj.get("provider_urls") is not None else None,
            "rating": obj.get("rating"),
            "reviews": obj.get("reviews"),
            "start": obj.get("start"),
            "ticket_url": obj.get("ticket_url"),
            "timezone": obj.get("timezone"),
            "title": obj.get("title"),
            "venue": obj.get("venue")
        })
        return _obj


