# coding: utf-8

"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from myescapeplan.models.standardized_flight_segment import StandardizedFlightSegment
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StandardizedFlightLeg(BaseModel):
    """
    StandardizedFlightLeg
    """ # noqa: E501
    arrival_airport: Optional[StrictStr] = None
    arrival_time_local: Optional[StrictStr] = None
    arrival_time_utc: Optional[datetime] = None
    arrival_timezone: Optional[StrictStr] = None
    departure_airport: Optional[StrictStr] = None
    departure_time_local: Optional[StrictStr] = None
    departure_time_utc: Optional[datetime] = None
    departure_timezone: Optional[StrictStr] = None
    duration_minutes: Optional[StrictInt] = None
    layover_minutes_total: Optional[StrictInt] = None
    leg_index: StrictInt
    segments: List[StandardizedFlightSegment]
    stop_count: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["arrival_airport", "arrival_time_local", "arrival_time_utc", "arrival_timezone", "departure_airport", "departure_time_local", "departure_time_utc", "departure_timezone", "duration_minutes", "layover_minutes_total", "leg_index", "segments", "stop_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StandardizedFlightLeg from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in segments (list)
        _items = []
        if self.segments:
            for _item_segments in self.segments:
                if _item_segments:
                    _items.append(_item_segments.to_dict())
            _dict['segments'] = _items
        # set to None if arrival_airport (nullable) is None
        # and model_fields_set contains the field
        if self.arrival_airport is None and "arrival_airport" in self.model_fields_set:
            _dict['arrival_airport'] = None

        # set to None if arrival_time_local (nullable) is None
        # and model_fields_set contains the field
        if self.arrival_time_local is None and "arrival_time_local" in self.model_fields_set:
            _dict['arrival_time_local'] = None

        # set to None if arrival_time_utc (nullable) is None
        # and model_fields_set contains the field
        if self.arrival_time_utc is None and "arrival_time_utc" in self.model_fields_set:
            _dict['arrival_time_utc'] = None

        # set to None if arrival_timezone (nullable) is None
        # and model_fields_set contains the field
        if self.arrival_timezone is None and "arrival_timezone" in self.model_fields_set:
            _dict['arrival_timezone'] = None

        # set to None if departure_airport (nullable) is None
        # and model_fields_set contains the field
        if self.departure_airport is None and "departure_airport" in self.model_fields_set:
            _dict['departure_airport'] = None

        # set to None if departure_time_local (nullable) is None
        # and model_fields_set contains the field
        if self.departure_time_local is None and "departure_time_local" in self.model_fields_set:
            _dict['departure_time_local'] = None

        # set to None if departure_time_utc (nullable) is None
        # and model_fields_set contains the field
        if self.departure_time_utc is None and "departure_time_utc" in self.model_fields_set:
            _dict['departure_time_utc'] = None

        # set to None if departure_timezone (nullable) is None
        # and model_fields_set contains the field
        if self.departure_timezone is None and "departure_timezone" in self.model_fields_set:
            _dict['departure_timezone'] = None

        # set to None if duration_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.duration_minutes is None and "duration_minutes" in self.model_fields_set:
            _dict['duration_minutes'] = None

        # set to None if layover_minutes_total (nullable) is None
        # and model_fields_set contains the field
        if self.layover_minutes_total is None and "layover_minutes_total" in self.model_fields_set:
            _dict['layover_minutes_total'] = None

        # set to None if stop_count (nullable) is None
        # and model_fields_set contains the field
        if self.stop_count is None and "stop_count" in self.model_fields_set:
            _dict['stop_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StandardizedFlightLeg from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "arrival_airport": obj.get("arrival_airport"),
            "arrival_time_local": obj.get("arrival_time_local"),
            "arrival_time_utc": obj.get("arrival_time_utc"),
            "arrival_timezone": obj.get("arrival_timezone"),
            "departure_airport": obj.get("departure_airport"),
            "departure_time_local": obj.get("departure_time_local"),
            "departure_time_utc": obj.get("departure_time_utc"),
            "departure_timezone": obj.get("departure_timezone"),
            "duration_minutes": obj.get("duration_minutes"),
            "layover_minutes_total": obj.get("layover_minutes_total"),
            "leg_index": obj.get("leg_index"),
            "segments": [StandardizedFlightSegment.from_dict(_item) for _item in obj["segments"]] if obj.get("segments") is not None else None,
            "stop_count": obj.get("stop_count")
        })
        return _obj


