# coding: utf-8

"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from myescapeplan.models.price_insight import PriceInsight
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StandardizedStayOffer(BaseModel):
    """
    StandardizedStayOffer
    """ # noqa: E501
    check_in_date: Optional[StrictStr] = None
    check_out_date: Optional[StrictStr] = None
    currency: Optional[StrictStr] = None
    nightly_price: Optional[Union[StrictFloat, StrictInt]] = None
    price_insights: Optional[List[PriceInsight]] = None
    price_total: Optional[Union[StrictFloat, StrictInt]] = None
    primary_price_insight: Optional[PriceInsight] = None
    taxes_fees_included: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["check_in_date", "check_out_date", "currency", "nightly_price", "price_insights", "price_total", "primary_price_insight", "taxes_fees_included"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StandardizedStayOffer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in price_insights (list)
        _items = []
        if self.price_insights:
            for _item_price_insights in self.price_insights:
                if _item_price_insights:
                    _items.append(_item_price_insights.to_dict())
            _dict['price_insights'] = _items
        # override the default output from pydantic by calling `to_dict()` of primary_price_insight
        if self.primary_price_insight:
            _dict['primary_price_insight'] = self.primary_price_insight.to_dict()
        # set to None if check_in_date (nullable) is None
        # and model_fields_set contains the field
        if self.check_in_date is None and "check_in_date" in self.model_fields_set:
            _dict['check_in_date'] = None

        # set to None if check_out_date (nullable) is None
        # and model_fields_set contains the field
        if self.check_out_date is None and "check_out_date" in self.model_fields_set:
            _dict['check_out_date'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if nightly_price (nullable) is None
        # and model_fields_set contains the field
        if self.nightly_price is None and "nightly_price" in self.model_fields_set:
            _dict['nightly_price'] = None

        # set to None if price_total (nullable) is None
        # and model_fields_set contains the field
        if self.price_total is None and "price_total" in self.model_fields_set:
            _dict['price_total'] = None

        # set to None if primary_price_insight (nullable) is None
        # and model_fields_set contains the field
        if self.primary_price_insight is None and "primary_price_insight" in self.model_fields_set:
            _dict['primary_price_insight'] = None

        # set to None if taxes_fees_included (nullable) is None
        # and model_fields_set contains the field
        if self.taxes_fees_included is None and "taxes_fees_included" in self.model_fields_set:
            _dict['taxes_fees_included'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StandardizedStayOffer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "check_in_date": obj.get("check_in_date"),
            "check_out_date": obj.get("check_out_date"),
            "currency": obj.get("currency"),
            "nightly_price": obj.get("nightly_price"),
            "price_insights": [PriceInsight.from_dict(_item) for _item in obj["price_insights"]] if obj.get("price_insights") is not None else None,
            "price_total": obj.get("price_total"),
            "primary_price_insight": PriceInsight.from_dict(obj["primary_price_insight"]) if obj.get("primary_price_insight") is not None else None,
            "taxes_fees_included": obj.get("taxes_fees_included")
        })
        return _obj


