# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StructuredStay(BaseModel):
    """
    Only amenities with an existing provider parameter and post-filter.
    """ # noqa: E501
    amenities: Optional[Annotated[List[StrictStr], Field(max_length=17)]] = None
    direction: Optional[StrictStr] = 'prefer'
    property_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["amenities", "direction", "property_type"]

    @field_validator('amenities')
    def amenities_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['FREE_WIFI', 'POOL', 'AIR_CONDITIONING', 'PARKING', 'PETS_ALLOWED', 'SPA', 'GYM', 'BREAKFAST_INCLUDED', 'RESTAURANT', 'BAR', 'ROOM_SERVICE', 'WHEELCHAIR_ACCESSIBLE', 'BEACH_ACCESS', 'ALL_INCLUSIVE', 'CHILD_FRIENDLY', 'INDOOR_POOL', 'OUTDOOR_POOL']):
                raise ValueError("each list item must be one of ('FREE_WIFI', 'POOL', 'AIR_CONDITIONING', 'PARKING', 'PETS_ALLOWED', 'SPA', 'GYM', 'BREAKFAST_INCLUDED', 'RESTAURANT', 'BAR', 'ROOM_SERVICE', 'WHEELCHAIR_ACCESSIBLE', 'BEACH_ACCESS', 'ALL_INCLUSIVE', 'CHILD_FRIENDLY', 'INDOOR_POOL', 'OUTDOOR_POOL')")
        return value

    @field_validator('direction')
    def direction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['prefer', 'must']):
            raise ValueError("must be one of enum values ('prefer', 'must')")
        return value

    @field_validator('property_type')
    def property_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['resort', 'villa', 'apartment']):
            raise ValueError("must be one of enum values ('resort', 'villa', 'apartment')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StructuredStay from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if property_type (nullable) is None
        # and model_fields_set contains the field
        if self.property_type is None and "property_type" in self.model_fields_set:
            _dict['property_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StructuredStay from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amenities": obj.get("amenities"),
            "direction": obj.get("direction") if obj.get("direction") is not None else 'prefer',
            "property_type": obj.get("property_type")
        })
        return _obj


