# coding: utf-8

"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StructuredFlight(BaseModel):
    """
    StructuredFlight
    """ # noqa: E501
    cabin_class: Optional[StrictStr] = None
    direction: Optional[StrictStr] = 'prefer'
    directions: Optional[Dict[str, StrictStr]] = None
    exclude_airlines: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    include_airlines: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    max_stops: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["cabin_class", "direction", "directions", "exclude_airlines", "include_airlines", "max_stops"]

    @field_validator('cabin_class')
    def cabin_class_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['economy', 'premium_economy', 'business', 'first']):
            raise ValueError("must be one of enum values ('economy', 'premium_economy', 'business', 'first')")
        return value

    @field_validator('direction')
    def direction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['prefer', 'must']):
            raise ValueError("must be one of enum values ('prefer', 'must')")
        return value

    @field_validator('directions')
    def directions_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value.values():
            if i not in set(['prefer', 'must']):
                raise ValueError("dict values must be one of enum values ('prefer', 'must')")
        return value

    @field_validator('max_stops')
    def max_stops_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0]):
            raise ValueError("must be one of enum values (0)")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StructuredFlight from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cabin_class (nullable) is None
        # and model_fields_set contains the field
        if self.cabin_class is None and "cabin_class" in self.model_fields_set:
            _dict['cabin_class'] = None

        # set to None if max_stops (nullable) is None
        # and model_fields_set contains the field
        if self.max_stops is None and "max_stops" in self.model_fields_set:
            _dict['max_stops'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StructuredFlight from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cabin_class": obj.get("cabin_class"),
            "direction": obj.get("direction") if obj.get("direction") is not None else 'prefer',
            "directions": obj.get("directions"),
            "exclude_airlines": obj.get("exclude_airlines"),
            "include_airlines": obj.get("include_airlines"),
            "max_stops": obj.get("max_stops")
        })
        return _obj


