# coding: utf-8

"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WeatherObservation(BaseModel):
    """
    WeatherObservation
    """ # noqa: E501
    avg_temp_c: Optional[Union[StrictFloat, StrictInt]] = None
    condition: Optional[StrictStr] = None
    var_date: StrictStr = Field(alias="date")
    description: StrictStr
    max_temp_c: Optional[Union[StrictFloat, StrictInt]] = None
    min_temp_c: Optional[Union[StrictFloat, StrictInt]] = None
    source: StrictStr
    temperature_celsius: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["avg_temp_c", "condition", "date", "description", "max_temp_c", "min_temp_c", "source", "temperature_celsius"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WeatherObservation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if avg_temp_c (nullable) is None
        # and model_fields_set contains the field
        if self.avg_temp_c is None and "avg_temp_c" in self.model_fields_set:
            _dict['avg_temp_c'] = None

        # set to None if condition (nullable) is None
        # and model_fields_set contains the field
        if self.condition is None and "condition" in self.model_fields_set:
            _dict['condition'] = None

        # set to None if max_temp_c (nullable) is None
        # and model_fields_set contains the field
        if self.max_temp_c is None and "max_temp_c" in self.model_fields_set:
            _dict['max_temp_c'] = None

        # set to None if min_temp_c (nullable) is None
        # and model_fields_set contains the field
        if self.min_temp_c is None and "min_temp_c" in self.model_fields_set:
            _dict['min_temp_c'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WeatherObservation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "avg_temp_c": obj.get("avg_temp_c"),
            "condition": obj.get("condition"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "max_temp_c": obj.get("max_temp_c"),
            "min_temp_c": obj.get("min_temp_c"),
            "source": obj.get("source"),
            "temperature_celsius": obj.get("temperature_celsius")
        })
        return _obj


