/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AffiliateLink
 */
export interface AffiliateLink {
    /**
     * 
     * @type {string}
     * @memberof AffiliateLink
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof AffiliateLink
     */
    company: string;
    /**
     * 
     * @type {string}
     * @memberof AffiliateLink
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AffiliateLink
     */
    offerRef?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AffiliateLink
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof AffiliateLink
     */
    targetUrl: string;
    /**
     * 
     * @type {string}
     * @memberof AffiliateLink
     */
    trackingUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AffiliateLink
     */
    url: string;
}

/**
 * Check if a given object implements the AffiliateLink interface.
 */
export function instanceOfAffiliateLink(value: object): value is AffiliateLink {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('company' in value) || value['company'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if ((!('targetUrl' in (value as Record<string, any>)) && !('target_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['targetUrl'] === undefined && (value as Record<string, any>)['target_url'] === undefined)) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function AffiliateLinkFromJSON(json: any): AffiliateLink {
    return AffiliateLinkFromJSONTyped(json, false);
}

export function AffiliateLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffiliateLink {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'company': json['company'],
        'name': json['name'],
        'offerRef': json['offer_ref'] === undefined ? undefined : json['offer_ref'] === null ? null : json['offer_ref'],
        'provider': json['provider'],
        'targetUrl': json['target_url'],
        'trackingUrl': json['tracking_url'] === undefined ? undefined : json['tracking_url'] === null ? null : json['tracking_url'],
        'url': json['url'],
    };
}

export function AffiliateLinkToJSON(json: any): AffiliateLink {
    return AffiliateLinkToJSONTyped(json, false);
}

export function AffiliateLinkToJSONTyped(value?: AffiliateLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'company': value['company'],
        'name': value['name'],
        'offer_ref': value['offerRef'],
        'provider': value['provider'],
        'target_url': value['targetUrl'],
        'tracking_url': value['trackingUrl'],
        'url': value['url'],
    };
}

