/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AirportRef
 */
export interface AirportRef {
    /**
     * 
     * @type {string}
     * @memberof AirportRef
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof AirportRef
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof AirportRef
     */
    iata: string;
    /**
     * 
     * @type {number}
     * @memberof AirportRef
     */
    lat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AirportRef
     */
    lon?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AirportRef
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AirportRef
     */
    placeId?: string | null;
}

/**
 * Check if a given object implements the AirportRef interface.
 */
export function instanceOfAirportRef(value: object): value is AirportRef {
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('iata' in value) || value['iata'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AirportRefFromJSON(json: any): AirportRef {
    return AirportRefFromJSONTyped(json, false);
}

export function AirportRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirportRef {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'],
        'country': json['country'],
        'iata': json['iata'],
        'lat': json['lat'] === undefined ? undefined : json['lat'] === null ? null : json['lat'],
        'lon': json['lon'] === undefined ? undefined : json['lon'] === null ? null : json['lon'],
        'name': json['name'],
        'placeId': json['place_id'] === undefined ? undefined : json['place_id'] === null ? null : json['place_id'],
    };
}

export function AirportRefToJSON(json: any): AirportRef {
    return AirportRefToJSONTyped(json, false);
}

export function AirportRefToJSONTyped(value?: AirportRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'country': value['country'],
        'iata': value['iata'],
        'lat': value['lat'],
        'lon': value['lon'],
        'name': value['name'],
        'place_id': value['placeId'],
    };
}

