/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AmenityType = {
    FreeWifi: 'FREE_WIFI',
    Pool: 'POOL',
    AirConditioning: 'AIR_CONDITIONING',
    Parking: 'PARKING',
    PetsAllowed: 'PETS_ALLOWED',
    Spa: 'SPA',
    Gym: 'GYM',
    BreakfastIncluded: 'BREAKFAST_INCLUDED',
    Restaurant: 'RESTAURANT',
    Bar: 'BAR',
    RoomService: 'ROOM_SERVICE',
    WheelchairAccessible: 'WHEELCHAIR_ACCESSIBLE',
    Laundry: 'LAUNDRY',
    Kitchen: 'KITCHEN',
    HotTub: 'HOT_TUB',
    BeachAccess: 'BEACH_ACCESS',
    AllInclusive: 'ALL_INCLUSIVE',
    ChildFriendly: 'CHILD_FRIENDLY',
    IndoorPool: 'INDOOR_POOL',
    OutdoorPool: 'OUTDOOR_POOL'
} as const;
export type AmenityType = typeof AmenityType[keyof typeof AmenityType];


export function instanceOfAmenityType(value: any): boolean {
    for (const key in AmenityType) {
        if (Object.prototype.hasOwnProperty.call(AmenityType, key)) {
            if (AmenityType[key as keyof typeof AmenityType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AmenityTypeFromJSON(json: any): AmenityType {
    return AmenityTypeFromJSONTyped(json, false);
}

export function AmenityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmenityType {
    return json as AmenityType;
}

export function AmenityTypeToJSON(value?: AmenityType | null): any {
    return value as any;
}

export function AmenityTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AmenityType {
    return value as AmenityType;
}

