/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BudgetAmount
 */
export interface BudgetAmount {
}

/**
 * Check if a given object implements the BudgetAmount interface.
 */
export function instanceOfBudgetAmount(value: object): value is BudgetAmount {
    return true;
}

export function BudgetAmountFromJSON(json: any): BudgetAmount {
    return BudgetAmountFromJSONTyped(json, false);
}

export function BudgetAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetAmount {
    return json;
}

export function BudgetAmountToJSON(json: any): BudgetAmount {
    return BudgetAmountToJSONTyped(json, false);
}

export function BudgetAmountToJSONTyped(value?: BudgetAmount | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

