/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessApiError } from './BusinessApiError';
import {
    BusinessApiErrorFromJSON,
    BusinessApiErrorFromJSONTyped,
    BusinessApiErrorToJSON,
    BusinessApiErrorToJSONTyped,
} from './BusinessApiError';

/**
 * 
 * @export
 * @interface BusinessErrorEnvelope
 */
export interface BusinessErrorEnvelope {
    /**
     * 
     * @type {BusinessApiError}
     * @memberof BusinessErrorEnvelope
     */
    error: BusinessApiError;
}

/**
 * Check if a given object implements the BusinessErrorEnvelope interface.
 */
export function instanceOfBusinessErrorEnvelope(value: object): value is BusinessErrorEnvelope {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BusinessErrorEnvelopeFromJSON(json: any): BusinessErrorEnvelope {
    return BusinessErrorEnvelopeFromJSONTyped(json, false);
}

export function BusinessErrorEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessErrorEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'error': BusinessApiErrorFromJSON(json['error']),
    };
}

export function BusinessErrorEnvelopeToJSON(json: any): BusinessErrorEnvelope {
    return BusinessErrorEnvelopeToJSONTyped(json, false);
}

export function BusinessErrorEnvelopeToJSONTyped(value?: BusinessErrorEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': BusinessApiErrorToJSON(value['error']),
    };
}

