/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AffiliateLink } from './AffiliateLink';
import {
    AffiliateLinkFromJSON,
    AffiliateLinkFromJSONTyped,
    AffiliateLinkToJSON,
    AffiliateLinkToJSONTyped,
} from './AffiliateLink';
import type { SlimStandardizedStay } from './SlimStandardizedStay';
import {
    SlimStandardizedStayFromJSON,
    SlimStandardizedStayFromJSONTyped,
    SlimStandardizedStayToJSON,
    SlimStandardizedStayToJSONTyped,
} from './SlimStandardizedStay';
import type { BusinessSearchResult } from './BusinessSearchResult';
import {
    BusinessSearchResultFromJSON,
    BusinessSearchResultFromJSONTyped,
    BusinessSearchResultToJSON,
    BusinessSearchResultToJSONTyped,
} from './BusinessSearchResult';
import type { WeatherHint } from './WeatherHint';
import {
    WeatherHintFromJSON,
    WeatherHintFromJSONTyped,
    WeatherHintToJSON,
    WeatherHintToJSONTyped,
} from './WeatherHint';
import type { SlimStandardizedFlightOffer } from './SlimStandardizedFlightOffer';
import {
    SlimStandardizedFlightOfferFromJSON,
    SlimStandardizedFlightOfferFromJSONTyped,
    SlimStandardizedFlightOfferToJSON,
    SlimStandardizedFlightOfferToJSONTyped,
} from './SlimStandardizedFlightOffer';
import type { DestinationAccessSummary } from './DestinationAccessSummary';
import {
    DestinationAccessSummaryFromJSON,
    DestinationAccessSummaryFromJSONTyped,
    DestinationAccessSummaryToJSON,
    DestinationAccessSummaryToJSONTyped,
} from './DestinationAccessSummary';
import type { BusinessTripResultDetail } from './BusinessTripResultDetail';
import {
    BusinessTripResultDetailFromJSON,
    BusinessTripResultDetailFromJSONTyped,
    BusinessTripResultDetailToJSON,
    BusinessTripResultDetailToJSONTyped,
} from './BusinessTripResultDetail';
import type { WeatherObservation } from './WeatherObservation';
import {
    WeatherObservationFromJSON,
    WeatherObservationFromJSONTyped,
    WeatherObservationToJSON,
    WeatherObservationToJSONTyped,
} from './WeatherObservation';

/**
 * Rich Business result detail backed by the consumer result contract.
 * @export
 * @interface BusinessResultDetail
 */
export interface BusinessResultDetail {
    /**
     * 
     * @type {Array<AffiliateLink>}
     * @memberof BusinessResultDetail
     */
    affiliateLinks?: Array<AffiliateLink>;
    /**
     * 
     * @type {DestinationAccessSummary}
     * @memberof BusinessResultDetail
     */
    destinationAccess?: DestinationAccessSummary | null;
    /**
     * 
     * @type {BusinessTripResultDetail}
     * @memberof BusinessResultDetail
     */
    detail: BusinessTripResultDetail;
    /**
     * 
     * @type {Array<SlimStandardizedFlightOffer>}
     * @memberof BusinessResultDetail
     */
    flights?: Array<SlimStandardizedFlightOffer>;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessResultDetail
     */
    hasMoreFlights?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessResultDetail
     */
    hasMoreHotels?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessResultDetail
     */
    hasMoreRentals?: boolean;
    /**
     * 
     * @type {Array<SlimStandardizedStay>}
     * @memberof BusinessResultDetail
     */
    hotels?: Array<SlimStandardizedStay>;
    /**
     * 
     * @type {Array<SlimStandardizedStay>}
     * @memberof BusinessResultDetail
     */
    rentals?: Array<SlimStandardizedStay>;
    /**
     * 
     * @type {BusinessSearchResult}
     * @memberof BusinessResultDetail
     */
    result: BusinessSearchResult;
    /**
     * 
     * @type {WeatherHint}
     * @memberof BusinessResultDetail
     */
    weather?: WeatherHint | null;
    /**
     * 
     * @type {Array<WeatherObservation>}
     * @memberof BusinessResultDetail
     */
    weatherData?: Array<WeatherObservation>;
    /**
     * 
     * @type {BusinessResultDetailWeatherStatusEnum}
     * @memberof BusinessResultDetail
     */
    weatherStatus?: BusinessResultDetailWeatherStatusEnum;
}


/**
 * @export
 */
export const BusinessResultDetailWeatherStatusEnum = {
    Available: 'available',
    Unavailable: 'unavailable',
    Partial: 'partial',
    Failed: 'failed',
    Pending: 'pending',
    NotRequested: 'not_requested'
} as const;
export type BusinessResultDetailWeatherStatusEnum = typeof BusinessResultDetailWeatherStatusEnum[keyof typeof BusinessResultDetailWeatherStatusEnum];


/**
 * Check if a given object implements the BusinessResultDetail interface.
 */
export function instanceOfBusinessResultDetail(value: object): value is BusinessResultDetail {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function BusinessResultDetailFromJSON(json: any): BusinessResultDetail {
    return BusinessResultDetailFromJSONTyped(json, false);
}

export function BusinessResultDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessResultDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateLinks': json['affiliate_links'] == null ? undefined : ((json['affiliate_links'] as Array<any>).map(AffiliateLinkFromJSON)),
        'destinationAccess': json['destination_access'] === undefined ? undefined : json['destination_access'] === null ? null : DestinationAccessSummaryFromJSON(json['destination_access']),
        'detail': BusinessTripResultDetailFromJSON(json['detail']),
        'flights': json['flights'] == null ? undefined : ((json['flights'] as Array<any>).map(SlimStandardizedFlightOfferFromJSON)),
        'hasMoreFlights': json['has_more_flights'] == null ? undefined : json['has_more_flights'],
        'hasMoreHotels': json['has_more_hotels'] == null ? undefined : json['has_more_hotels'],
        'hasMoreRentals': json['has_more_rentals'] == null ? undefined : json['has_more_rentals'],
        'hotels': json['hotels'] == null ? undefined : ((json['hotels'] as Array<any>).map(SlimStandardizedStayFromJSON)),
        'rentals': json['rentals'] == null ? undefined : ((json['rentals'] as Array<any>).map(SlimStandardizedStayFromJSON)),
        'result': BusinessSearchResultFromJSON(json['result']),
        'weather': json['weather'] === undefined ? undefined : json['weather'] === null ? null : WeatherHintFromJSON(json['weather']),
        'weatherData': json['weather_data'] == null ? undefined : ((json['weather_data'] as Array<any>).map(WeatherObservationFromJSON)),
        'weatherStatus': json['weather_status'] == null ? undefined : json['weather_status'],
    };
}

export function BusinessResultDetailToJSON(json: any): BusinessResultDetail {
    return BusinessResultDetailToJSONTyped(json, false);
}

export function BusinessResultDetailToJSONTyped(value?: BusinessResultDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliate_links': value['affiliateLinks'] == null ? undefined : ((value['affiliateLinks'] as Array<any>).map(AffiliateLinkToJSON)),
        'destination_access': DestinationAccessSummaryToJSON(value['destinationAccess']),
        'detail': BusinessTripResultDetailToJSON(value['detail']),
        'flights': value['flights'] == null ? undefined : ((value['flights'] as Array<any>).map(SlimStandardizedFlightOfferToJSON)),
        'has_more_flights': value['hasMoreFlights'],
        'has_more_hotels': value['hasMoreHotels'],
        'has_more_rentals': value['hasMoreRentals'],
        'hotels': value['hotels'] == null ? undefined : ((value['hotels'] as Array<any>).map(SlimStandardizedStayToJSON)),
        'rentals': value['rentals'] == null ? undefined : ((value['rentals'] as Array<any>).map(SlimStandardizedStayToJSON)),
        'result': BusinessSearchResultToJSON(value['result']),
        'weather': WeatherHintToJSON(value['weather']),
        'weather_data': value['weatherData'] == null ? undefined : ((value['weatherData'] as Array<any>).map(WeatherObservationToJSON)),
        'weather_status': value['weatherStatus'],
    };
}

