/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Verified stay window. A bare dict here would document as a free-form map.
 * @export
 * @interface BusinessResultDates
 */
export interface BusinessResultDates {
    /**
     * 
     * @type {Date}
     * @memberof BusinessResultDates
     */
    endDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof BusinessResultDates
     */
    startDate: Date;
}

/**
 * Check if a given object implements the BusinessResultDates interface.
 */
export function instanceOfBusinessResultDates(value: object): value is BusinessResultDates {
    if ((!('endDate' in (value as Record<string, any>)) && !('end_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['endDate'] === undefined && (value as Record<string, any>)['end_date'] === undefined)) return false;
    if ((!('startDate' in (value as Record<string, any>)) && !('start_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['startDate'] === undefined && (value as Record<string, any>)['start_date'] === undefined)) return false;
    return true;
}

export function BusinessResultDatesFromJSON(json: any): BusinessResultDates {
    return BusinessResultDatesFromJSONTyped(json, false);
}

export function BusinessResultDatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessResultDates {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': (new Date(json['end_date'])),
        'startDate': (new Date(json['start_date'])),
    };
}

export function BusinessResultDatesToJSON(json: any): BusinessResultDates {
    return BusinessResultDatesToJSONTyped(json, false);
}

export function BusinessResultDatesToJSONTyped(value?: BusinessResultDates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_date': value['endDate'].toISOString().substring(0,10),
        'start_date': value['startDate'].toISOString().substring(0,10),
    };
}

