/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessPrice } from './BusinessPrice';
import {
    BusinessPriceFromJSON,
    BusinessPriceFromJSONTyped,
    BusinessPriceToJSON,
    BusinessPriceToJSONTyped,
} from './BusinessPrice';
import type { PriceInsight } from './PriceInsight';
import {
    PriceInsightFromJSON,
    PriceInsightFromJSONTyped,
    PriceInsightToJSON,
    PriceInsightToJSONTyped,
} from './PriceInsight';
import type { BusinessTrackSummary } from './BusinessTrackSummary';
import {
    BusinessTrackSummaryFromJSON,
    BusinessTrackSummaryFromJSONTyped,
    BusinessTrackSummaryToJSON,
    BusinessTrackSummaryToJSONTyped,
} from './BusinessTrackSummary';

/**
 * 
 * @export
 * @interface BusinessDateOption
 */
export interface BusinessDateOption {
    /**
     * 
     * @type {string}
     * @memberof BusinessDateOption
     */
    dateOptionId: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessDateOption
     */
    dateType?: string;
    /**
     * 
     * @type {Date}
     * @memberof BusinessDateOption
     */
    endDate: Date;
    /**
     * 
     * @type {BusinessTrackSummary}
     * @memberof BusinessDateOption
     */
    flights?: BusinessTrackSummary | null;
    /**
     * 
     * @type {BusinessTrackSummary}
     * @memberof BusinessDateOption
     */
    hotels?: BusinessTrackSummary | null;
    /**
     * 
     * @type {number}
     * @memberof BusinessDateOption
     */
    nights: number;
    /**
     * 
     * @type {Array<PriceInsight>}
     * @memberof BusinessDateOption
     */
    priceInsights?: Array<PriceInsight>;
    /**
     * 
     * @type {BusinessPrice}
     * @memberof BusinessDateOption
     */
    pricing?: BusinessPrice | null;
    /**
     * 
     * @type {PriceInsight}
     * @memberof BusinessDateOption
     */
    primaryPriceInsight?: PriceInsight | null;
    /**
     * 
     * @type {BusinessTrackSummary}
     * @memberof BusinessDateOption
     */
    rentals?: BusinessTrackSummary | null;
    /**
     * 
     * @type {Date}
     * @memberof BusinessDateOption
     */
    startDate: Date;
    /**
     * 
     * @type {BusinessDateOptionStatusEnum}
     * @memberof BusinessDateOption
     */
    status?: BusinessDateOptionStatusEnum;
    /**
     * 
     * @type {BusinessDateOptionUnpricedReasonEnum}
     * @memberof BusinessDateOption
     */
    unpricedReason?: BusinessDateOptionUnpricedReasonEnum | null;
}


/**
 * @export
 */
export const BusinessDateOptionStatusEnum = {
    Pending: 'pending',
    Available: 'available',
    Partial: 'partial',
    Unavailable: 'unavailable',
    Failed: 'failed',
    Error: 'error',
    Skipped: 'skipped'
} as const;
export type BusinessDateOptionStatusEnum = typeof BusinessDateOptionStatusEnum[keyof typeof BusinessDateOptionStatusEnum];

/**
 * @export
 */
export const BusinessDateOptionUnpricedReasonEnum = {
    SearchBudgetReached: 'search_budget_reached'
} as const;
export type BusinessDateOptionUnpricedReasonEnum = typeof BusinessDateOptionUnpricedReasonEnum[keyof typeof BusinessDateOptionUnpricedReasonEnum];


/**
 * Check if a given object implements the BusinessDateOption interface.
 */
export function instanceOfBusinessDateOption(value: object): value is BusinessDateOption {
    if ((!('dateOptionId' in (value as Record<string, any>)) && !('date_option_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['dateOptionId'] === undefined && (value as Record<string, any>)['date_option_id'] === undefined)) return false;
    if ((!('endDate' in (value as Record<string, any>)) && !('end_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['endDate'] === undefined && (value as Record<string, any>)['end_date'] === undefined)) return false;
    if (!('nights' in value) || value['nights'] === undefined) return false;
    if ((!('startDate' in (value as Record<string, any>)) && !('start_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['startDate'] === undefined && (value as Record<string, any>)['start_date'] === undefined)) return false;
    return true;
}

export function BusinessDateOptionFromJSON(json: any): BusinessDateOption {
    return BusinessDateOptionFromJSONTyped(json, false);
}

export function BusinessDateOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessDateOption {
    if (json == null) {
        return json;
    }
    return {
        
        'dateOptionId': json['date_option_id'],
        'dateType': json['date_type'] == null ? undefined : json['date_type'],
        'endDate': (new Date(json['end_date'])),
        'flights': json['flights'] === undefined ? undefined : json['flights'] === null ? null : BusinessTrackSummaryFromJSON(json['flights']),
        'hotels': json['hotels'] === undefined ? undefined : json['hotels'] === null ? null : BusinessTrackSummaryFromJSON(json['hotels']),
        'nights': json['nights'],
        'priceInsights': json['price_insights'] == null ? undefined : ((json['price_insights'] as Array<any>).map(PriceInsightFromJSON)),
        'pricing': json['pricing'] === undefined ? undefined : json['pricing'] === null ? null : BusinessPriceFromJSON(json['pricing']),
        'primaryPriceInsight': json['primary_price_insight'] === undefined ? undefined : json['primary_price_insight'] === null ? null : PriceInsightFromJSON(json['primary_price_insight']),
        'rentals': json['rentals'] === undefined ? undefined : json['rentals'] === null ? null : BusinessTrackSummaryFromJSON(json['rentals']),
        'startDate': (new Date(json['start_date'])),
        'status': json['status'] == null ? undefined : json['status'],
        'unpricedReason': json['unpriced_reason'] === undefined ? undefined : json['unpriced_reason'] === null ? null : json['unpriced_reason'],
    };
}

export function BusinessDateOptionToJSON(json: any): BusinessDateOption {
    return BusinessDateOptionToJSONTyped(json, false);
}

export function BusinessDateOptionToJSONTyped(value?: BusinessDateOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date_option_id': value['dateOptionId'],
        'date_type': value['dateType'],
        'end_date': value['endDate'].toISOString().substring(0,10),
        'flights': BusinessTrackSummaryToJSON(value['flights']),
        'hotels': BusinessTrackSummaryToJSON(value['hotels']),
        'nights': value['nights'],
        'price_insights': value['priceInsights'] == null ? undefined : ((value['priceInsights'] as Array<any>).map(PriceInsightToJSON)),
        'pricing': BusinessPriceToJSON(value['pricing']),
        'primary_price_insight': PriceInsightToJSON(value['primaryPriceInsight']),
        'rentals': BusinessTrackSummaryToJSON(value['rentals']),
        'start_date': value['startDate'].toISOString().substring(0,10),
        'status': value['status'],
        'unpriced_reason': value['unpricedReason'],
    };
}

