/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessJobStatus } from './BusinessJobStatus';
import {
    BusinessJobStatusFromJSON,
    BusinessJobStatusFromJSONTyped,
    BusinessJobStatusToJSON,
    BusinessJobStatusToJSONTyped,
} from './BusinessJobStatus';
import type { BusinessApiError } from './BusinessApiError';
import {
    BusinessApiErrorFromJSON,
    BusinessApiErrorFromJSONTyped,
    BusinessApiErrorToJSON,
    BusinessApiErrorToJSONTyped,
} from './BusinessApiError';
import type { BusinessJobLinks } from './BusinessJobLinks';
import {
    BusinessJobLinksFromJSON,
    BusinessJobLinksFromJSONTyped,
    BusinessJobLinksToJSON,
    BusinessJobLinksToJSONTyped,
} from './BusinessJobLinks';

/**
 * 
 * @export
 * @interface BusinessJobResource
 */
export interface BusinessJobResource {
    /**
     * 
     * @type {string}
     * @memberof BusinessJobResource
     */
    clientReference?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof BusinessJobResource
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BusinessJobResource
     */
    createdAt: Date;
    /**
     * 
     * @type {BusinessJobResourceEnvironmentEnum}
     * @memberof BusinessJobResource
     */
    environment: BusinessJobResourceEnvironmentEnum;
    /**
     * 
     * @type {BusinessApiError}
     * @memberof BusinessJobResource
     */
    error?: BusinessApiError | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessJobResource
     */
    id: string;
    /**
     * 
     * @type {BusinessJobLinks}
     * @memberof BusinessJobResource
     */
    links: BusinessJobLinks;
    /**
     * 
     * @type {Date}
     * @memberof BusinessJobResource
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {BusinessJobStatus}
     * @memberof BusinessJobResource
     */
    status: BusinessJobStatus;
}


/**
 * @export
 */
export const BusinessJobResourceEnvironmentEnum = {
    Test: 'test',
    Live: 'live'
} as const;
export type BusinessJobResourceEnvironmentEnum = typeof BusinessJobResourceEnvironmentEnum[keyof typeof BusinessJobResourceEnvironmentEnum];


/**
 * Check if a given object implements the BusinessJobResource interface.
 */
export function instanceOfBusinessJobResource(value: object): value is BusinessJobResource {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BusinessJobResourceFromJSON(json: any): BusinessJobResource {
    return BusinessJobResourceFromJSONTyped(json, false);
}

export function BusinessJobResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessJobResource {
    if (json == null) {
        return json;
    }
    return {
        
        'clientReference': json['client_reference'] === undefined ? undefined : json['client_reference'] === null ? null : json['client_reference'],
        'completedAt': json['completed_at'] === undefined ? undefined : json['completed_at'] === null ? null : (new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'environment': json['environment'],
        'error': json['error'] === undefined ? undefined : json['error'] === null ? null : BusinessApiErrorFromJSON(json['error']),
        'id': json['id'],
        'links': BusinessJobLinksFromJSON(json['links']),
        'startedAt': json['started_at'] === undefined ? undefined : json['started_at'] === null ? null : (new Date(json['started_at'])),
        'status': BusinessJobStatusFromJSON(json['status']),
    };
}

export function BusinessJobResourceToJSON(json: any): BusinessJobResource {
    return BusinessJobResourceToJSONTyped(json, false);
}

export function BusinessJobResourceToJSONTyped(value?: BusinessJobResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_reference': value['clientReference'],
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'environment': value['environment'],
        'error': BusinessApiErrorToJSON(value['error']),
        'id': value['id'],
        'links': BusinessJobLinksToJSON(value['links']),
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'status': BusinessJobStatusToJSON(value['status']),
    };
}

