/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessRateLimits
 */
export interface BusinessRateLimits {
    /**
     * 
     * @type {number}
     * @memberof BusinessRateLimits
     */
    discoveryPerMinute: number;
}

/**
 * Check if a given object implements the BusinessRateLimits interface.
 */
export function instanceOfBusinessRateLimits(value: object): value is BusinessRateLimits {
    if ((!('discoveryPerMinute' in (value as Record<string, any>)) && !('discovery_per_minute' in (value as Record<string, any>))) || ((value as Record<string, any>)['discoveryPerMinute'] === undefined && (value as Record<string, any>)['discovery_per_minute'] === undefined)) return false;
    return true;
}

export function BusinessRateLimitsFromJSON(json: any): BusinessRateLimits {
    return BusinessRateLimitsFromJSONTyped(json, false);
}

export function BusinessRateLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessRateLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'discoveryPerMinute': json['discovery_per_minute'],
    };
}

export function BusinessRateLimitsToJSON(json: any): BusinessRateLimits {
    return BusinessRateLimitsToJSONTyped(json, false);
}

export function BusinessRateLimitsToJSONTyped(value?: BusinessRateLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'discovery_per_minute': value['discoveryPerMinute'],
    };
}

