/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessPrice
 */
export interface BusinessPrice {
    /**
     * 
     * @type {BusinessPriceBasisEnum}
     * @memberof BusinessPrice
     */
    basis?: BusinessPriceBasisEnum;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessPrice
     */
    bookablePackagePrice?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BusinessPrice
     */
    currency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BusinessPrice
     */
    total?: number | null;
}


/**
 * @export
 */
export const BusinessPriceBasisEnum = {
    VoyagerSummaryTotal: 'voyager_summary_total',
    DateOptionTotal: 'date_option_total',
    ComponentMinimum: 'component_minimum',
    Unknown: 'unknown'
} as const;
export type BusinessPriceBasisEnum = typeof BusinessPriceBasisEnum[keyof typeof BusinessPriceBasisEnum];


/**
 * Check if a given object implements the BusinessPrice interface.
 */
export function instanceOfBusinessPrice(value: object): value is BusinessPrice {
    return true;
}

export function BusinessPriceFromJSON(json: any): BusinessPrice {
    return BusinessPriceFromJSONTyped(json, false);
}

export function BusinessPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'basis': json['basis'] == null ? undefined : json['basis'],
        'bookablePackagePrice': json['bookable_package_price'] == null ? undefined : json['bookable_package_price'],
        'currency': json['currency'] === undefined ? undefined : json['currency'] === null ? null : json['currency'],
        'total': json['total'] === undefined ? undefined : json['total'] === null ? null : json['total'],
    };
}

export function BusinessPriceToJSON(json: any): BusinessPrice {
    return BusinessPriceToJSONTyped(json, false);
}

export function BusinessPriceToJSONTyped(value?: BusinessPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'basis': value['basis'],
        'bookable_package_price': value['bookablePackagePrice'],
        'currency': value['currency'],
        'total': value['total'],
    };
}

