/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessUsageCounter
 */
export interface BusinessUsageCounter {
    /**
     * 
     * @type {number}
     * @memberof BusinessUsageCounter
     */
    allowance: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessUsageCounter
     */
    remaining: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessUsageCounter
     */
    used: number;
}

/**
 * Check if a given object implements the BusinessUsageCounter interface.
 */
export function instanceOfBusinessUsageCounter(value: object): value is BusinessUsageCounter {
    if (!('allowance' in value) || value['allowance'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    if (!('used' in value) || value['used'] === undefined) return false;
    return true;
}

export function BusinessUsageCounterFromJSON(json: any): BusinessUsageCounter {
    return BusinessUsageCounterFromJSONTyped(json, false);
}

export function BusinessUsageCounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessUsageCounter {
    if (json == null) {
        return json;
    }
    return {
        
        'allowance': json['allowance'],
        'remaining': json['remaining'],
        'used': json['used'],
    };
}

export function BusinessUsageCounterToJSON(json: any): BusinessUsageCounter {
    return BusinessUsageCounterToJSONTyped(json, false);
}

export function BusinessUsageCounterToJSONTyped(value?: BusinessUsageCounter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowance': value['allowance'],
        'remaining': value['remaining'],
        'used': value['used'],
    };
}

