/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessApiError
 */
export interface BusinessApiError {
    /**
     * 
     * @type {string}
     * @memberof BusinessApiError
     */
    code: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BusinessApiError
     */
    details?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof BusinessApiError
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessApiError
     */
    retryable?: boolean;
}

/**
 * Check if a given object implements the BusinessApiError interface.
 */
export function instanceOfBusinessApiError(value: object): value is BusinessApiError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function BusinessApiErrorFromJSON(json: any): BusinessApiError {
    return BusinessApiErrorFromJSONTyped(json, false);
}

export function BusinessApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessApiError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'],
        'retryable': json['retryable'] == null ? undefined : json['retryable'],
    };
}

export function BusinessApiErrorToJSON(json: any): BusinessApiError {
    return BusinessApiErrorToJSONTyped(json, false);
}

export function BusinessApiErrorToJSONTyped(value?: BusinessApiError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
        'retryable': value['retryable'],
    };
}

