/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BusinessJobStatus = {
    Queued: 'queued',
    Planning: 'planning',
    Running: 'running',
    Completed: 'completed',
    Partial: 'partial',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type BusinessJobStatus = typeof BusinessJobStatus[keyof typeof BusinessJobStatus];


export function instanceOfBusinessJobStatus(value: any): boolean {
    for (const key in BusinessJobStatus) {
        if (Object.prototype.hasOwnProperty.call(BusinessJobStatus, key)) {
            if (BusinessJobStatus[key as keyof typeof BusinessJobStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BusinessJobStatusFromJSON(json: any): BusinessJobStatus {
    return BusinessJobStatusFromJSONTyped(json, false);
}

export function BusinessJobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessJobStatus {
    return json as BusinessJobStatus;
}

export function BusinessJobStatusToJSON(value?: BusinessJobStatus | null): any {
    return value as any;
}

export function BusinessJobStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BusinessJobStatus {
    return value as BusinessJobStatus;
}

