/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessUsagePeriod
 */
export interface BusinessUsagePeriod {
    /**
     * 
     * @type {Date}
     * @memberof BusinessUsagePeriod
     */
    end: Date;
    /**
     * 
     * @type {Date}
     * @memberof BusinessUsagePeriod
     */
    start: Date;
}

/**
 * Check if a given object implements the BusinessUsagePeriod interface.
 */
export function instanceOfBusinessUsagePeriod(value: object): value is BusinessUsagePeriod {
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function BusinessUsagePeriodFromJSON(json: any): BusinessUsagePeriod {
    return BusinessUsagePeriodFromJSONTyped(json, false);
}

export function BusinessUsagePeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessUsagePeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'end': (new Date(json['end'])),
        'start': (new Date(json['start'])),
    };
}

export function BusinessUsagePeriodToJSON(json: any): BusinessUsagePeriod {
    return BusinessUsagePeriodToJSONTyped(json, false);
}

export function BusinessUsagePeriodToJSONTyped(value?: BusinessUsagePeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end': value['end'].toISOString(),
        'start': value['start'].toISOString(),
    };
}

