/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessPrice } from './BusinessPrice';
import {
    BusinessPriceFromJSON,
    BusinessPriceFromJSONTyped,
    BusinessPriceToJSON,
    BusinessPriceToJSONTyped,
} from './BusinessPrice';
import type { ImageObject } from './ImageObject';
import {
    ImageObjectFromJSON,
    ImageObjectFromJSONTyped,
    ImageObjectToJSON,
    ImageObjectToJSONTyped,
} from './ImageObject';
import type { PriceInsight } from './PriceInsight';
import {
    PriceInsightFromJSON,
    PriceInsightFromJSONTyped,
    PriceInsightToJSON,
    PriceInsightToJSONTyped,
} from './PriceInsight';
import type { BusinessResultDates } from './BusinessResultDates';
import {
    BusinessResultDatesFromJSON,
    BusinessResultDatesFromJSONTyped,
    BusinessResultDatesToJSON,
    BusinessResultDatesToJSONTyped,
} from './BusinessResultDates';
import type { WeatherHint } from './WeatherHint';
import {
    WeatherHintFromJSON,
    WeatherHintFromJSONTyped,
    WeatherHintToJSON,
    WeatherHintToJSONTyped,
} from './WeatherHint';
import type { BusinessDateOption } from './BusinessDateOption';
import {
    BusinessDateOptionFromJSON,
    BusinessDateOptionFromJSONTyped,
    BusinessDateOptionToJSON,
    BusinessDateOptionToJSONTyped,
} from './BusinessDateOption';
import type { BusinessTrackSummary } from './BusinessTrackSummary';
import {
    BusinessTrackSummaryFromJSON,
    BusinessTrackSummaryFromJSONTyped,
    BusinessTrackSummaryToJSON,
    BusinessTrackSummaryToJSONTyped,
} from './BusinessTrackSummary';
import type { DestinationAccessSummary } from './DestinationAccessSummary';
import {
    DestinationAccessSummaryFromJSON,
    DestinationAccessSummaryFromJSONTyped,
    DestinationAccessSummaryToJSON,
    DestinationAccessSummaryToJSONTyped,
} from './DestinationAccessSummary';
import type { WeatherObservation } from './WeatherObservation';
import {
    WeatherObservationFromJSON,
    WeatherObservationFromJSONTyped,
    WeatherObservationToJSON,
    WeatherObservationToJSONTyped,
} from './WeatherObservation';

/**
 * 
 * @export
 * @interface BusinessSearchResult
 */
export interface BusinessSearchResult {
    /**
     * 
     * @type {{ [key: string]: BusinessPrice; }}
     * @memberof BusinessSearchResult
     */
    componentPricing?: { [key: string]: BusinessPrice; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BusinessSearchResult
     */
    dataStatus?: { [key: string]: any; };
    /**
     * 
     * @type {Array<BusinessDateOption>}
     * @memberof BusinessSearchResult
     */
    dateOptions?: Array<BusinessDateOption>;
    /**
     * 
     * @type {BusinessResultDates}
     * @memberof BusinessSearchResult
     */
    dates?: BusinessResultDates | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessSearchResult
     */
    description?: string | null;
    /**
     * 
     * @type {DestinationAccessSummary}
     * @memberof BusinessSearchResult
     */
    destinationAccess?: DestinationAccessSummary | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessSearchResult
     */
    destinationId: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessSearchResult
     */
    detailsUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessSearchResult
     */
    displayName?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BusinessSearchResult
     */
    features?: Array<string>;
    /**
     * 
     * @type {BusinessTrackSummary}
     * @memberof BusinessSearchResult
     */
    flights: BusinessTrackSummary;
    /**
     * 
     * @type {BusinessTrackSummary}
     * @memberof BusinessSearchResult
     */
    hotels: BusinessTrackSummary;
    /**
     * 
     * @type {Array<ImageObject>}
     * @memberof BusinessSearchResult
     */
    images?: Array<ImageObject> | null;
    /**
     * 
     * @type {Array<PriceInsight>}
     * @memberof BusinessSearchResult
     */
    priceInsights?: Array<PriceInsight>;
    /**
     * 
     * @type {BusinessPrice}
     * @memberof BusinessSearchResult
     */
    pricing?: BusinessPrice | null;
    /**
     * 
     * @type {number}
     * @memberof BusinessSearchResult
     */
    rank?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessSearchResult
     */
    reason?: string | null;
    /**
     * 
     * @type {BusinessTrackSummary}
     * @memberof BusinessSearchResult
     */
    rentals: BusinessTrackSummary;
    /**
     * 
     * @type {Array<string>}
     * @memberof BusinessSearchResult
     */
    requestedCategories?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BusinessSearchResult
     */
    resultId: string;
    /**
     * 
     * @type {Date}
     * @memberof BusinessSearchResult
     */
    verifiedAt?: Date | null;
    /**
     * 
     * @type {WeatherHint}
     * @memberof BusinessSearchResult
     */
    weather?: WeatherHint | null;
    /**
     * 
     * @type {Array<WeatherObservation>}
     * @memberof BusinessSearchResult
     */
    weatherData?: Array<WeatherObservation>;
    /**
     * 
     * @type {BusinessSearchResultWeatherStatusEnum}
     * @memberof BusinessSearchResult
     */
    weatherStatus?: BusinessSearchResultWeatherStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BusinessSearchResult
     */
    weatherSummary?: string | null;
}


/**
 * @export
 */
export const BusinessSearchResultWeatherStatusEnum = {
    Available: 'available',
    Unavailable: 'unavailable',
    Partial: 'partial',
    Failed: 'failed',
    Pending: 'pending',
    NotRequested: 'not_requested'
} as const;
export type BusinessSearchResultWeatherStatusEnum = typeof BusinessSearchResultWeatherStatusEnum[keyof typeof BusinessSearchResultWeatherStatusEnum];


/**
 * Check if a given object implements the BusinessSearchResult interface.
 */
export function instanceOfBusinessSearchResult(value: object): value is BusinessSearchResult {
    if ((!('destinationId' in (value as Record<string, any>)) && !('destination_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['destinationId'] === undefined && (value as Record<string, any>)['destination_id'] === undefined)) return false;
    if (!('flights' in value) || value['flights'] === undefined) return false;
    if (!('hotels' in value) || value['hotels'] === undefined) return false;
    if (!('rentals' in value) || value['rentals'] === undefined) return false;
    if ((!('resultId' in (value as Record<string, any>)) && !('result_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['resultId'] === undefined && (value as Record<string, any>)['result_id'] === undefined)) return false;
    return true;
}

export function BusinessSearchResultFromJSON(json: any): BusinessSearchResult {
    return BusinessSearchResultFromJSONTyped(json, false);
}

export function BusinessSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'componentPricing': json['component_pricing'] == null ? undefined : (mapValues(json['component_pricing'], BusinessPriceFromJSON)),
        'dataStatus': json['data_status'] == null ? undefined : json['data_status'],
        'dateOptions': json['date_options'] == null ? undefined : ((json['date_options'] as Array<any>).map(BusinessDateOptionFromJSON)),
        'dates': json['dates'] === undefined ? undefined : json['dates'] === null ? null : BusinessResultDatesFromJSON(json['dates']),
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'destinationAccess': json['destination_access'] === undefined ? undefined : json['destination_access'] === null ? null : DestinationAccessSummaryFromJSON(json['destination_access']),
        'destinationId': json['destination_id'],
        'detailsUrl': json['details_url'] === undefined ? undefined : json['details_url'] === null ? null : json['details_url'],
        'displayName': json['display_name'] === undefined ? undefined : json['display_name'] === null ? null : json['display_name'],
        'features': json['features'] == null ? undefined : json['features'],
        'flights': BusinessTrackSummaryFromJSON(json['flights']),
        'hotels': BusinessTrackSummaryFromJSON(json['hotels']),
        'images': json['images'] === undefined ? undefined : json['images'] === null ? null : ((json['images'] as Array<any>).map(ImageObjectFromJSON)),
        'priceInsights': json['price_insights'] == null ? undefined : ((json['price_insights'] as Array<any>).map(PriceInsightFromJSON)),
        'pricing': json['pricing'] === undefined ? undefined : json['pricing'] === null ? null : BusinessPriceFromJSON(json['pricing']),
        'rank': json['rank'] === undefined ? undefined : json['rank'] === null ? null : json['rank'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
        'rentals': BusinessTrackSummaryFromJSON(json['rentals']),
        'requestedCategories': json['requested_categories'] == null ? undefined : json['requested_categories'],
        'resultId': json['result_id'],
        'verifiedAt': json['verified_at'] === undefined ? undefined : json['verified_at'] === null ? null : (new Date(json['verified_at'])),
        'weather': json['weather'] === undefined ? undefined : json['weather'] === null ? null : WeatherHintFromJSON(json['weather']),
        'weatherData': json['weather_data'] == null ? undefined : ((json['weather_data'] as Array<any>).map(WeatherObservationFromJSON)),
        'weatherStatus': json['weather_status'] == null ? undefined : json['weather_status'],
        'weatherSummary': json['weather_summary'] === undefined ? undefined : json['weather_summary'] === null ? null : json['weather_summary'],
    };
}

export function BusinessSearchResultToJSON(json: any): BusinessSearchResult {
    return BusinessSearchResultToJSONTyped(json, false);
}

export function BusinessSearchResultToJSONTyped(value?: BusinessSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'component_pricing': value['componentPricing'] == null ? undefined : (mapValues(value['componentPricing'], BusinessPriceToJSON)),
        'data_status': value['dataStatus'],
        'date_options': value['dateOptions'] == null ? undefined : ((value['dateOptions'] as Array<any>).map(BusinessDateOptionToJSON)),
        'dates': BusinessResultDatesToJSON(value['dates']),
        'description': value['description'],
        'destination_access': DestinationAccessSummaryToJSON(value['destinationAccess']),
        'destination_id': value['destinationId'],
        'details_url': value['detailsUrl'],
        'display_name': value['displayName'],
        'features': value['features'],
        'flights': BusinessTrackSummaryToJSON(value['flights']),
        'hotels': BusinessTrackSummaryToJSON(value['hotels']),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageObjectToJSON)),
        'price_insights': value['priceInsights'] == null ? undefined : ((value['priceInsights'] as Array<any>).map(PriceInsightToJSON)),
        'pricing': BusinessPriceToJSON(value['pricing']),
        'rank': value['rank'],
        'reason': value['reason'],
        'rentals': BusinessTrackSummaryToJSON(value['rentals']),
        'requested_categories': value['requestedCategories'],
        'result_id': value['resultId'],
        'verified_at': value['verifiedAt'] == null ? value['verifiedAt'] : value['verifiedAt'].toISOString(),
        'weather': WeatherHintToJSON(value['weather']),
        'weather_data': value['weatherData'] == null ? undefined : ((value['weatherData'] as Array<any>).map(WeatherObservationToJSON)),
        'weather_status': value['weatherStatus'],
        'weather_summary': value['weatherSummary'],
    };
}

