/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TripPrice } from './TripPrice';
import {
    TripPriceFromJSON,
    TripPriceFromJSONTyped,
    TripPriceToJSON,
    TripPriceToJSONTyped,
} from './TripPrice';
import type { DateOptionKind } from './DateOptionKind';
import {
    DateOptionKindFromJSON,
    DateOptionKindFromJSONTyped,
    DateOptionKindToJSON,
    DateOptionKindToJSONTyped,
} from './DateOptionKind';
import type { DateRange } from './DateRange';
import {
    DateRangeFromJSON,
    DateRangeFromJSONTyped,
    DateRangeToJSON,
    DateRangeToJSONTyped,
} from './DateRange';
import type { DateOptionComponentSummary } from './DateOptionComponentSummary';
import {
    DateOptionComponentSummaryFromJSON,
    DateOptionComponentSummaryFromJSONTyped,
    DateOptionComponentSummaryToJSON,
    DateOptionComponentSummaryToJSONTyped,
} from './DateOptionComponentSummary';
import type { PriceInsight } from './PriceInsight';
import {
    PriceInsightFromJSON,
    PriceInsightFromJSONTyped,
    PriceInsightToJSON,
    PriceInsightToJSONTyped,
} from './PriceInsight';

/**
 * Date-option detail without the disabled event inventory track.
 * @export
 * @interface BusinessDetailDateOption
 */
export interface BusinessDetailDateOption {
    /**
     * 
     * @type {string}
     * @memberof BusinessDetailDateOption
     */
    candidateId?: string | null;
    /**
     * 
     * @type {DateOptionKind}
     * @memberof BusinessDetailDateOption
     */
    dateOptionKind?: DateOptionKind | null;
    /**
     * 
     * @type {DateRange}
     * @memberof BusinessDetailDateOption
     */
    dates: DateRange;
    /**
     * 
     * @type {DateOptionComponentSummary}
     * @memberof BusinessDetailDateOption
     */
    flightSummary?: DateOptionComponentSummary | null;
    /**
     * 
     * @type {DateOptionComponentSummary}
     * @memberof BusinessDetailDateOption
     */
    hotelSummary?: DateOptionComponentSummary | null;
    /**
     * 
     * @type {Array<PriceInsight>}
     * @memberof BusinessDetailDateOption
     */
    priceInsights?: Array<PriceInsight>;
    /**
     * 
     * @type {PriceInsight}
     * @memberof BusinessDetailDateOption
     */
    primaryPriceInsight?: PriceInsight | null;
    /**
     * 
     * @type {DateOptionComponentSummary}
     * @memberof BusinessDetailDateOption
     */
    rentalSummary?: DateOptionComponentSummary | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BusinessDetailDateOption
     */
    requiredCategories?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessDetailDateOption
     */
    status?: string | null;
    /**
     * 
     * @type {TripPrice}
     * @memberof BusinessDetailDateOption
     */
    totalPrice?: TripPrice | null;
}



/**
 * Check if a given object implements the BusinessDetailDateOption interface.
 */
export function instanceOfBusinessDetailDateOption(value: object): value is BusinessDetailDateOption {
    if (!('dates' in value) || value['dates'] === undefined) return false;
    return true;
}

export function BusinessDetailDateOptionFromJSON(json: any): BusinessDetailDateOption {
    return BusinessDetailDateOptionFromJSONTyped(json, false);
}

export function BusinessDetailDateOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessDetailDateOption {
    if (json == null) {
        return json;
    }
    return {
        
        'candidateId': json['candidate_id'] === undefined ? undefined : json['candidate_id'] === null ? null : json['candidate_id'],
        'dateOptionKind': json['date_option_kind'] === undefined ? undefined : json['date_option_kind'] === null ? null : DateOptionKindFromJSON(json['date_option_kind']),
        'dates': DateRangeFromJSON(json['dates']),
        'flightSummary': json['flight_summary'] === undefined ? undefined : json['flight_summary'] === null ? null : DateOptionComponentSummaryFromJSON(json['flight_summary']),
        'hotelSummary': json['hotel_summary'] === undefined ? undefined : json['hotel_summary'] === null ? null : DateOptionComponentSummaryFromJSON(json['hotel_summary']),
        'priceInsights': json['price_insights'] == null ? undefined : ((json['price_insights'] as Array<any>).map(PriceInsightFromJSON)),
        'primaryPriceInsight': json['primary_price_insight'] === undefined ? undefined : json['primary_price_insight'] === null ? null : PriceInsightFromJSON(json['primary_price_insight']),
        'rentalSummary': json['rental_summary'] === undefined ? undefined : json['rental_summary'] === null ? null : DateOptionComponentSummaryFromJSON(json['rental_summary']),
        'requiredCategories': json['required_categories'] === undefined ? undefined : json['required_categories'] === null ? null : json['required_categories'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : json['status'],
        'totalPrice': json['total_price'] === undefined ? undefined : json['total_price'] === null ? null : TripPriceFromJSON(json['total_price']),
    };
}

export function BusinessDetailDateOptionToJSON(json: any): BusinessDetailDateOption {
    return BusinessDetailDateOptionToJSONTyped(json, false);
}

export function BusinessDetailDateOptionToJSONTyped(value?: BusinessDetailDateOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candidate_id': value['candidateId'],
        'date_option_kind': DateOptionKindToJSON(value['dateOptionKind']),
        'dates': DateRangeToJSON(value['dates']),
        'flight_summary': DateOptionComponentSummaryToJSON(value['flightSummary']),
        'hotel_summary': DateOptionComponentSummaryToJSON(value['hotelSummary']),
        'price_insights': value['priceInsights'] == null ? undefined : ((value['priceInsights'] as Array<any>).map(PriceInsightToJSON)),
        'primary_price_insight': PriceInsightToJSON(value['primaryPriceInsight']),
        'rental_summary': DateOptionComponentSummaryToJSON(value['rentalSummary']),
        'required_categories': value['requiredCategories'],
        'status': value['status'],
        'total_price': TripPriceToJSON(value['totalPrice']),
    };
}

