/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessConcurrencyUsage
 */
export interface BusinessConcurrencyUsage {
    /**
     * 
     * @type {number}
     * @memberof BusinessConcurrencyUsage
     */
    active: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessConcurrencyUsage
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessConcurrencyUsage
     */
    remaining: number;
}

/**
 * Check if a given object implements the BusinessConcurrencyUsage interface.
 */
export function instanceOfBusinessConcurrencyUsage(value: object): value is BusinessConcurrencyUsage {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    return true;
}

export function BusinessConcurrencyUsageFromJSON(json: any): BusinessConcurrencyUsage {
    return BusinessConcurrencyUsageFromJSONTyped(json, false);
}

export function BusinessConcurrencyUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessConcurrencyUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'limit': json['limit'],
        'remaining': json['remaining'],
    };
}

export function BusinessConcurrencyUsageToJSON(json: any): BusinessConcurrencyUsage {
    return BusinessConcurrencyUsageToJSONTyped(json, false);
}

export function BusinessConcurrencyUsageToJSONTyped(value?: BusinessConcurrencyUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'limit': value['limit'],
        'remaining': value['remaining'],
    };
}

