/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AffiliateLink } from './AffiliateLink';
import {
    AffiliateLinkFromJSON,
    AffiliateLinkFromJSONTyped,
    AffiliateLinkToJSON,
    AffiliateLinkToJSONTyped,
} from './AffiliateLink';
import type { TripPrice } from './TripPrice';
import {
    TripPriceFromJSON,
    TripPriceFromJSONTyped,
    TripPriceToJSON,
    TripPriceToJSONTyped,
} from './TripPrice';
import type { BusinessDetailDateOption } from './BusinessDetailDateOption';
import {
    BusinessDetailDateOptionFromJSON,
    BusinessDetailDateOptionFromJSONTyped,
    BusinessDetailDateOptionToJSON,
    BusinessDetailDateOptionToJSONTyped,
} from './BusinessDetailDateOption';
import type { DestinationReasonPayload } from './DestinationReasonPayload';
import {
    DestinationReasonPayloadFromJSON,
    DestinationReasonPayloadFromJSONTyped,
    DestinationReasonPayloadToJSON,
    DestinationReasonPayloadToJSONTyped,
} from './DestinationReasonPayload';
import type { DateRange } from './DateRange';
import {
    DateRangeFromJSON,
    DateRangeFromJSONTyped,
    DateRangeToJSON,
    DateRangeToJSONTyped,
} from './DateRange';
import type { FlightDetail } from './FlightDetail';
import {
    FlightDetailFromJSON,
    FlightDetailFromJSONTyped,
    FlightDetailToJSON,
    FlightDetailToJSONTyped,
} from './FlightDetail';
import type { ImageObject } from './ImageObject';
import {
    ImageObjectFromJSON,
    ImageObjectFromJSONTyped,
    ImageObjectToJSON,
    ImageObjectToJSONTyped,
} from './ImageObject';
import type { AirportRef } from './AirportRef';
import {
    AirportRefFromJSON,
    AirportRefFromJSONTyped,
    AirportRefToJSON,
    AirportRefToJSONTyped,
} from './AirportRef';
import type { PriceInsight } from './PriceInsight';
import {
    PriceInsightFromJSON,
    PriceInsightFromJSONTyped,
    PriceInsightToJSON,
    PriceInsightToJSONTyped,
} from './PriceInsight';
import type { DestinationAccessSummary } from './DestinationAccessSummary';
import {
    DestinationAccessSummaryFromJSON,
    DestinationAccessSummaryFromJSONTyped,
    DestinationAccessSummaryToJSON,
    DestinationAccessSummaryToJSONTyped,
} from './DestinationAccessSummary';
import type { StayDetail } from './StayDetail';
import {
    StayDetailFromJSON,
    StayDetailFromJSONTyped,
    StayDetailToJSON,
    StayDetailToJSONTyped,
} from './StayDetail';

/**
 * Consumer detail projection with event inventory intentionally disabled.
 * @export
 * @interface BusinessTripResultDetail
 */
export interface BusinessTripResultDetail {
    /**
     * 
     * @type {Array<AffiliateLink>}
     * @memberof BusinessTripResultDetail
     */
    affiliateLinks?: Array<AffiliateLink> | null;
    /**
     * 
     * @type {{ [key: string]: AirportRef; }}
     * @memberof BusinessTripResultDetail
     */
    airportRefs?: { [key: string]: AirportRef; };
    /**
     * 
     * @type {Array<BusinessDetailDateOption>}
     * @memberof BusinessTripResultDetail
     */
    dateOptions?: Array<BusinessDetailDateOption> | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessTripResultDetail
     */
    description?: string | null;
    /**
     * 
     * @type {DestinationAccessSummary}
     * @memberof BusinessTripResultDetail
     */
    destinationAccess?: DestinationAccessSummary | null;
    /**
     * 
     * @type {DestinationReasonPayload}
     * @memberof BusinessTripResultDetail
     */
    destinationReason?: DestinationReasonPayload | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessTripResultDetail
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessTripResultDetail
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {Array<FlightDetail>}
     * @memberof BusinessTripResultDetail
     */
    flights?: Array<FlightDetail> | null;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessTripResultDetail
     */
    hasMoreFlights?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessTripResultDetail
     */
    hasMoreHotels?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessTripResultDetail
     */
    hasMoreVacationRentals?: boolean | null;
    /**
     * 
     * @type {Array<StayDetail>}
     * @memberof BusinessTripResultDetail
     */
    hotels?: Array<StayDetail> | null;
    /**
     * 
     * @type {Array<ImageObject>}
     * @memberof BusinessTripResultDetail
     */
    images?: Array<ImageObject> | null;
    /**
     * 
     * @type {Array<PriceInsight>}
     * @memberof BusinessTripResultDetail
     */
    priceInsights?: Array<PriceInsight>;
    /**
     * 
     * @type {PriceInsight}
     * @memberof BusinessTripResultDetail
     */
    primaryPriceInsight?: PriceInsight | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessTripResultDetail
     */
    reason?: string | null;
    /**
     * 
     * @type {Array<StayDetail>}
     * @memberof BusinessTripResultDetail
     */
    rentals?: Array<StayDetail> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BusinessTripResultDetail
     */
    requestedCategories?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessTripResultDetail
     */
    runId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessTripResultDetail
     */
    searchId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessTripResultDetail
     */
    specHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessTripResultDetail
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof BusinessTripResultDetail
     */
    totalFlightsCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BusinessTripResultDetail
     */
    totalHotelsCount?: number | null;
    /**
     * 
     * @type {TripPrice}
     * @memberof BusinessTripResultDetail
     */
    totalPrice?: TripPrice | null;
    /**
     * 
     * @type {number}
     * @memberof BusinessTripResultDetail
     */
    totalVacationRentalsCount?: number | null;
    /**
     * 
     * @type {DateRange}
     * @memberof BusinessTripResultDetail
     */
    tripDates?: DateRange | null;
}

/**
 * Check if a given object implements the BusinessTripResultDetail interface.
 */
export function instanceOfBusinessTripResultDetail(value: object): value is BusinessTripResultDetail {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BusinessTripResultDetailFromJSON(json: any): BusinessTripResultDetail {
    return BusinessTripResultDetailFromJSONTyped(json, false);
}

export function BusinessTripResultDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessTripResultDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateLinks': json['affiliate_links'] === undefined ? undefined : json['affiliate_links'] === null ? null : ((json['affiliate_links'] as Array<any>).map(AffiliateLinkFromJSON)),
        'airportRefs': json['airport_refs'] == null ? undefined : (mapValues(json['airport_refs'], AirportRefFromJSON)),
        'dateOptions': json['date_options'] === undefined ? undefined : json['date_options'] === null ? null : ((json['date_options'] as Array<any>).map(BusinessDetailDateOptionFromJSON)),
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'destinationAccess': json['destination_access'] === undefined ? undefined : json['destination_access'] === null ? null : DestinationAccessSummaryFromJSON(json['destination_access']),
        'destinationReason': json['destination_reason'] === undefined ? undefined : json['destination_reason'] === null ? null : DestinationReasonPayloadFromJSON(json['destination_reason']),
        'displayName': json['display_name'] === undefined ? undefined : json['display_name'] === null ? null : json['display_name'],
        'errorMessage': json['error_message'] === undefined ? undefined : json['error_message'] === null ? null : json['error_message'],
        'flights': json['flights'] === undefined ? undefined : json['flights'] === null ? null : ((json['flights'] as Array<any>).map(FlightDetailFromJSON)),
        'hasMoreFlights': json['has_more_flights'] === undefined ? undefined : json['has_more_flights'] === null ? null : json['has_more_flights'],
        'hasMoreHotels': json['has_more_hotels'] === undefined ? undefined : json['has_more_hotels'] === null ? null : json['has_more_hotels'],
        'hasMoreVacationRentals': json['has_more_vacation_rentals'] === undefined ? undefined : json['has_more_vacation_rentals'] === null ? null : json['has_more_vacation_rentals'],
        'hotels': json['hotels'] === undefined ? undefined : json['hotels'] === null ? null : ((json['hotels'] as Array<any>).map(StayDetailFromJSON)),
        'images': json['images'] === undefined ? undefined : json['images'] === null ? null : ((json['images'] as Array<any>).map(ImageObjectFromJSON)),
        'priceInsights': json['price_insights'] == null ? undefined : ((json['price_insights'] as Array<any>).map(PriceInsightFromJSON)),
        'primaryPriceInsight': json['primary_price_insight'] === undefined ? undefined : json['primary_price_insight'] === null ? null : PriceInsightFromJSON(json['primary_price_insight']),
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
        'rentals': json['rentals'] === undefined ? undefined : json['rentals'] === null ? null : ((json['rentals'] as Array<any>).map(StayDetailFromJSON)),
        'requestedCategories': json['requested_categories'] === undefined ? undefined : json['requested_categories'] === null ? null : json['requested_categories'],
        'runId': json['run_id'] === undefined ? undefined : json['run_id'] === null ? null : json['run_id'],
        'searchId': json['search_id'] === undefined ? undefined : json['search_id'] === null ? null : json['search_id'],
        'specHash': json['spec_hash'] === undefined ? undefined : json['spec_hash'] === null ? null : json['spec_hash'],
        'status': json['status'],
        'totalFlightsCount': json['total_flights_count'] === undefined ? undefined : json['total_flights_count'] === null ? null : json['total_flights_count'],
        'totalHotelsCount': json['total_hotels_count'] === undefined ? undefined : json['total_hotels_count'] === null ? null : json['total_hotels_count'],
        'totalPrice': json['total_price'] === undefined ? undefined : json['total_price'] === null ? null : TripPriceFromJSON(json['total_price']),
        'totalVacationRentalsCount': json['total_vacation_rentals_count'] === undefined ? undefined : json['total_vacation_rentals_count'] === null ? null : json['total_vacation_rentals_count'],
        'tripDates': json['trip_dates'] === undefined ? undefined : json['trip_dates'] === null ? null : DateRangeFromJSON(json['trip_dates']),
    };
}

export function BusinessTripResultDetailToJSON(json: any): BusinessTripResultDetail {
    return BusinessTripResultDetailToJSONTyped(json, false);
}

export function BusinessTripResultDetailToJSONTyped(value?: BusinessTripResultDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliate_links': value['affiliateLinks'] == null ? undefined : ((value['affiliateLinks'] as Array<any>).map(AffiliateLinkToJSON)),
        'airport_refs': value['airportRefs'] == null ? undefined : (mapValues(value['airportRefs'], AirportRefToJSON)),
        'date_options': value['dateOptions'] == null ? undefined : ((value['dateOptions'] as Array<any>).map(BusinessDetailDateOptionToJSON)),
        'description': value['description'],
        'destination_access': DestinationAccessSummaryToJSON(value['destinationAccess']),
        'destination_reason': DestinationReasonPayloadToJSON(value['destinationReason']),
        'display_name': value['displayName'],
        'error_message': value['errorMessage'],
        'flights': value['flights'] == null ? undefined : ((value['flights'] as Array<any>).map(FlightDetailToJSON)),
        'has_more_flights': value['hasMoreFlights'],
        'has_more_hotels': value['hasMoreHotels'],
        'has_more_vacation_rentals': value['hasMoreVacationRentals'],
        'hotels': value['hotels'] == null ? undefined : ((value['hotels'] as Array<any>).map(StayDetailToJSON)),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageObjectToJSON)),
        'price_insights': value['priceInsights'] == null ? undefined : ((value['priceInsights'] as Array<any>).map(PriceInsightToJSON)),
        'primary_price_insight': PriceInsightToJSON(value['primaryPriceInsight']),
        'reason': value['reason'],
        'rentals': value['rentals'] == null ? undefined : ((value['rentals'] as Array<any>).map(StayDetailToJSON)),
        'requested_categories': value['requestedCategories'],
        'run_id': value['runId'],
        'search_id': value['searchId'],
        'spec_hash': value['specHash'],
        'status': value['status'],
        'total_flights_count': value['totalFlightsCount'],
        'total_hotels_count': value['totalHotelsCount'],
        'total_price': TripPriceToJSON(value['totalPrice']),
        'total_vacation_rentals_count': value['totalVacationRentalsCount'],
        'trip_dates': DateRangeToJSON(value['tripDates']),
    };
}

