/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessRateLimits } from './BusinessRateLimits';
import {
    BusinessRateLimitsFromJSON,
    BusinessRateLimitsFromJSONTyped,
    BusinessRateLimitsToJSON,
    BusinessRateLimitsToJSONTyped,
} from './BusinessRateLimits';
import type { BusinessVerifiedSearchUsage } from './BusinessVerifiedSearchUsage';
import {
    BusinessVerifiedSearchUsageFromJSON,
    BusinessVerifiedSearchUsageFromJSONTyped,
    BusinessVerifiedSearchUsageToJSON,
    BusinessVerifiedSearchUsageToJSONTyped,
} from './BusinessVerifiedSearchUsage';
import type { BusinessConcurrencyUsage } from './BusinessConcurrencyUsage';
import {
    BusinessConcurrencyUsageFromJSON,
    BusinessConcurrencyUsageFromJSONTyped,
    BusinessConcurrencyUsageToJSON,
    BusinessConcurrencyUsageToJSONTyped,
} from './BusinessConcurrencyUsage';
import type { BusinessUsageCounter } from './BusinessUsageCounter';
import {
    BusinessUsageCounterFromJSON,
    BusinessUsageCounterFromJSONTyped,
    BusinessUsageCounterToJSON,
    BusinessUsageCounterToJSONTyped,
} from './BusinessUsageCounter';
import type { BusinessUsagePeriod } from './BusinessUsagePeriod';
import {
    BusinessUsagePeriodFromJSON,
    BusinessUsagePeriodFromJSONTyped,
    BusinessUsagePeriodToJSON,
    BusinessUsagePeriodToJSONTyped,
} from './BusinessUsagePeriod';

/**
 * 
 * @export
 * @interface BusinessUsageResponse
 */
export interface BusinessUsageResponse {
    /**
     * 
     * @type {BusinessUsageResponseAllowanceScopeEnum}
     * @memberof BusinessUsageResponse
     */
    allowanceScope?: BusinessUsageResponseAllowanceScopeEnum;
    /**
     * 
     * @type {Date}
     * @memberof BusinessUsageResponse
     */
    asOf: Date;
    /**
     * 
     * @type {BusinessConcurrencyUsage}
     * @memberof BusinessUsageResponse
     */
    concurrency: BusinessConcurrencyUsage;
    /**
     * 
     * @type {BusinessUsageCounter}
     * @memberof BusinessUsageResponse
     */
    discovery: BusinessUsageCounter;
    /**
     * 
     * @type {BusinessUsageResponseEnvironmentEnum}
     * @memberof BusinessUsageResponse
     */
    environment: BusinessUsageResponseEnvironmentEnum;
    /**
     * 
     * @type {BusinessUsagePeriod}
     * @memberof BusinessUsageResponse
     */
    period: BusinessUsagePeriod;
    /**
     * 
     * @type {BusinessUsageResponsePlanTierEnum}
     * @memberof BusinessUsageResponse
     */
    planTier: BusinessUsageResponsePlanTierEnum;
    /**
     * 
     * @type {BusinessRateLimits}
     * @memberof BusinessUsageResponse
     */
    rateLimits: BusinessRateLimits;
    /**
     * 
     * @type {Array<string>}
     * @memberof BusinessUsageResponse
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {BusinessVerifiedSearchUsage}
     * @memberof BusinessUsageResponse
     */
    verifiedSearches: BusinessVerifiedSearchUsage;
}


/**
 * @export
 */
export const BusinessUsageResponseAllowanceScopeEnum = {
    Client: 'client',
    Account: 'account'
} as const;
export type BusinessUsageResponseAllowanceScopeEnum = typeof BusinessUsageResponseAllowanceScopeEnum[keyof typeof BusinessUsageResponseAllowanceScopeEnum];

/**
 * @export
 */
export const BusinessUsageResponseEnvironmentEnum = {
    Test: 'test',
    Live: 'live'
} as const;
export type BusinessUsageResponseEnvironmentEnum = typeof BusinessUsageResponseEnvironmentEnum[keyof typeof BusinessUsageResponseEnvironmentEnum];

/**
 * @export
 */
export const BusinessUsageResponsePlanTierEnum = {
    Trial: 'trial',
    Starter: 'starter',
    Growth: 'growth',
    Scale: 'scale'
} as const;
export type BusinessUsageResponsePlanTierEnum = typeof BusinessUsageResponsePlanTierEnum[keyof typeof BusinessUsageResponsePlanTierEnum];


/**
 * Check if a given object implements the BusinessUsageResponse interface.
 */
export function instanceOfBusinessUsageResponse(value: object): value is BusinessUsageResponse {
    if ((!('asOf' in (value as Record<string, any>)) && !('as_of' in (value as Record<string, any>))) || ((value as Record<string, any>)['asOf'] === undefined && (value as Record<string, any>)['as_of'] === undefined)) return false;
    if (!('concurrency' in value) || value['concurrency'] === undefined) return false;
    if (!('discovery' in value) || value['discovery'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    if ((!('planTier' in (value as Record<string, any>)) && !('plan_tier' in (value as Record<string, any>))) || ((value as Record<string, any>)['planTier'] === undefined && (value as Record<string, any>)['plan_tier'] === undefined)) return false;
    if ((!('rateLimits' in (value as Record<string, any>)) && !('rate_limits' in (value as Record<string, any>))) || ((value as Record<string, any>)['rateLimits'] === undefined && (value as Record<string, any>)['rate_limits'] === undefined)) return false;
    if ((!('verifiedSearches' in (value as Record<string, any>)) && !('verified_searches' in (value as Record<string, any>))) || ((value as Record<string, any>)['verifiedSearches'] === undefined && (value as Record<string, any>)['verified_searches'] === undefined)) return false;
    return true;
}

export function BusinessUsageResponseFromJSON(json: any): BusinessUsageResponse {
    return BusinessUsageResponseFromJSONTyped(json, false);
}

export function BusinessUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'allowanceScope': json['allowance_scope'] == null ? undefined : json['allowance_scope'],
        'asOf': (new Date(json['as_of'])),
        'concurrency': BusinessConcurrencyUsageFromJSON(json['concurrency']),
        'discovery': BusinessUsageCounterFromJSON(json['discovery']),
        'environment': json['environment'],
        'period': BusinessUsagePeriodFromJSON(json['period']),
        'planTier': json['plan_tier'],
        'rateLimits': BusinessRateLimitsFromJSON(json['rate_limits']),
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'verifiedSearches': BusinessVerifiedSearchUsageFromJSON(json['verified_searches']),
    };
}

export function BusinessUsageResponseToJSON(json: any): BusinessUsageResponse {
    return BusinessUsageResponseToJSONTyped(json, false);
}

export function BusinessUsageResponseToJSONTyped(value?: BusinessUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowance_scope': value['allowanceScope'],
        'as_of': value['asOf'].toISOString(),
        'concurrency': BusinessConcurrencyUsageToJSON(value['concurrency']),
        'discovery': BusinessUsageCounterToJSON(value['discovery']),
        'environment': value['environment'],
        'period': BusinessUsagePeriodToJSON(value['period']),
        'plan_tier': value['planTier'],
        'rate_limits': BusinessRateLimitsToJSON(value['rateLimits']),
        'scopes': value['scopes'],
        'verified_searches': BusinessVerifiedSearchUsageToJSON(value['verifiedSearches']),
    };
}

