/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogueDestinationMatches } from './CatalogueDestinationMatches';
import {
    CatalogueDestinationMatchesFromJSON,
    CatalogueDestinationMatchesFromJSONTyped,
    CatalogueDestinationMatchesToJSON,
    CatalogueDestinationMatchesToJSONTyped,
} from './CatalogueDestinationMatches';
import type { CatalogueRef } from './CatalogueRef';
import {
    CatalogueRefFromJSON,
    CatalogueRefFromJSONTyped,
    CatalogueRefToJSON,
    CatalogueRefToJSONTyped,
} from './CatalogueRef';

/**
 * 
 * @export
 * @interface CatalogueMatchResponse
 */
export interface CatalogueMatchResponse {
    /**
     * 
     * @type {Array<CatalogueDestinationMatches>}
     * @memberof CatalogueMatchResponse
     */
    destinations?: Array<CatalogueDestinationMatches>;
    /**
     * 
     * @type {string}
     * @memberof CatalogueMatchResponse
     */
    discoveryId?: string | null;
    /**
     * 
     * @type {Array<CatalogueRef>}
     * @memberof CatalogueMatchResponse
     */
    unmatchedRefs?: Array<CatalogueRef>;
}

/**
 * Check if a given object implements the CatalogueMatchResponse interface.
 */
export function instanceOfCatalogueMatchResponse(value: object): value is CatalogueMatchResponse {
    return true;
}

export function CatalogueMatchResponseFromJSON(json: any): CatalogueMatchResponse {
    return CatalogueMatchResponseFromJSONTyped(json, false);
}

export function CatalogueMatchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogueMatchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'destinations': json['destinations'] == null ? undefined : ((json['destinations'] as Array<any>).map(CatalogueDestinationMatchesFromJSON)),
        'discoveryId': json['discovery_id'] === undefined ? undefined : json['discovery_id'] === null ? null : json['discovery_id'],
        'unmatchedRefs': json['unmatched_refs'] == null ? undefined : ((json['unmatched_refs'] as Array<any>).map(CatalogueRefFromJSON)),
    };
}

export function CatalogueMatchResponseToJSON(json: any): CatalogueMatchResponse {
    return CatalogueMatchResponseToJSONTyped(json, false);
}

export function CatalogueMatchResponseToJSONTyped(value?: CatalogueMatchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinations': value['destinations'] == null ? undefined : ((value['destinations'] as Array<any>).map(CatalogueDestinationMatchesToJSON)),
        'discovery_id': value['discoveryId'],
        'unmatched_refs': value['unmatchedRefs'] == null ? undefined : ((value['unmatchedRefs'] as Array<any>).map(CatalogueRefToJSON)),
    };
}

