/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogueRef } from './CatalogueRef';
import {
    CatalogueRefFromJSON,
    CatalogueRefFromJSONTyped,
    CatalogueRefToJSON,
    CatalogueRefToJSONTyped,
} from './CatalogueRef';

/**
 * Reusable customer-owned supply.
 * 
 * Catalogue products deliberately narrow the shared component vocabulary:
 * itinerary-only constructs such as notes and free time are not products.
 * ``subtype`` carries product specificity without widening the stable kind enum.
 * ``description`` is matching/internal catalogue copy; ``client_description``
 * remains explicit client-facing copy when the item is materialised.
 * @export
 * @interface CatalogueItem
 */
export interface CatalogueItem {
    /**
     * 
     * @type {string}
     * @memberof CatalogueItem
     */
    clientDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogueItem
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogueItem
     */
    destinationIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogueItem
     */
    inclusions?: string;
    /**
     * 
     * @type {CatalogueItemKindEnum}
     * @memberof CatalogueItem
     */
    kind: CatalogueItemKindEnum;
    /**
     * 
     * @type {CatalogueRef}
     * @memberof CatalogueItem
     */
    ref: CatalogueRef;
    /**
     * 
     * @type {string}
     * @memberof CatalogueItem
     */
    subtype?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogueItem
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogueItem
     */
    title: string;
}


/**
 * @export
 */
export const CatalogueItemKindEnum = {
    Flight: 'flight',
    Activity: 'activity',
    Event: 'event',
    Package: 'package',
    PrivateAviation: 'private_aviation',
    Cruise: 'cruise',
    Rail: 'rail',
    Transfer: 'transfer',
    Yacht: 'yacht',
    Stay: 'stay',
    Experience: 'experience',
    Other: 'other'
} as const;
export type CatalogueItemKindEnum = typeof CatalogueItemKindEnum[keyof typeof CatalogueItemKindEnum];


/**
 * Check if a given object implements the CatalogueItem interface.
 */
export function instanceOfCatalogueItem(value: object): value is CatalogueItem {
    if ((!('destinationIds' in (value as Record<string, any>)) && !('destination_ids' in (value as Record<string, any>))) || ((value as Record<string, any>)['destinationIds'] === undefined && (value as Record<string, any>)['destination_ids'] === undefined)) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CatalogueItemFromJSON(json: any): CatalogueItem {
    return CatalogueItemFromJSONTyped(json, false);
}

export function CatalogueItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogueItem {
    if (json == null) {
        return json;
    }
    return {
        
        'clientDescription': json['client_description'] == null ? undefined : json['client_description'],
        'description': json['description'] == null ? undefined : json['description'],
        'destinationIds': json['destination_ids'],
        'inclusions': json['inclusions'] == null ? undefined : json['inclusions'],
        'kind': json['kind'],
        'ref': CatalogueRefFromJSON(json['ref']),
        'subtype': json['subtype'] === undefined ? undefined : json['subtype'] === null ? null : json['subtype'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'title': json['title'],
    };
}

export function CatalogueItemToJSON(json: any): CatalogueItem {
    return CatalogueItemToJSONTyped(json, false);
}

export function CatalogueItemToJSONTyped(value?: CatalogueItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_description': value['clientDescription'],
        'description': value['description'],
        'destination_ids': value['destinationIds'],
        'inclusions': value['inclusions'],
        'kind': value['kind'],
        'ref': CatalogueRefToJSON(value['ref']),
        'subtype': value['subtype'],
        'tags': value['tags'],
        'title': value['title'],
    };
}

