/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogueItemMatch } from './CatalogueItemMatch';
import {
    CatalogueItemMatchFromJSON,
    CatalogueItemMatchFromJSONTyped,
    CatalogueItemMatchToJSON,
    CatalogueItemMatchToJSONTyped,
} from './CatalogueItemMatch';

/**
 * 
 * @export
 * @interface CatalogueDestinationMatches
 */
export interface CatalogueDestinationMatches {
    /**
     * 
     * @type {string}
     * @memberof CatalogueDestinationMatches
     */
    destinationId: string;
    /**
     * 
     * @type {Array<CatalogueItemMatch>}
     * @memberof CatalogueDestinationMatches
     */
    matches?: Array<CatalogueItemMatch>;
    /**
     * 
     * @type {string}
     * @memberof CatalogueDestinationMatches
     */
    opportunityId?: string | null;
}

/**
 * Check if a given object implements the CatalogueDestinationMatches interface.
 */
export function instanceOfCatalogueDestinationMatches(value: object): value is CatalogueDestinationMatches {
    if ((!('destinationId' in (value as Record<string, any>)) && !('destination_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['destinationId'] === undefined && (value as Record<string, any>)['destination_id'] === undefined)) return false;
    return true;
}

export function CatalogueDestinationMatchesFromJSON(json: any): CatalogueDestinationMatches {
    return CatalogueDestinationMatchesFromJSONTyped(json, false);
}

export function CatalogueDestinationMatchesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogueDestinationMatches {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationId': json['destination_id'],
        'matches': json['matches'] == null ? undefined : ((json['matches'] as Array<any>).map(CatalogueItemMatchFromJSON)),
        'opportunityId': json['opportunity_id'] === undefined ? undefined : json['opportunity_id'] === null ? null : json['opportunity_id'],
    };
}

export function CatalogueDestinationMatchesToJSON(json: any): CatalogueDestinationMatches {
    return CatalogueDestinationMatchesToJSONTyped(json, false);
}

export function CatalogueDestinationMatchesToJSONTyped(value?: CatalogueDestinationMatches | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destination_id': value['destinationId'],
        'matches': value['matches'] == null ? undefined : ((value['matches'] as Array<any>).map(CatalogueItemMatchToJSON)),
        'opportunity_id': value['opportunityId'],
    };
}

