/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TripPrice } from './TripPrice';
import {
    TripPriceFromJSON,
    TripPriceFromJSONTyped,
    TripPriceToJSON,
    TripPriceToJSONTyped,
} from './TripPrice';

/**
 * Lightweight component inventory for one exact date option.
 * 
 * Component metadata is deliberately scoped to the DateOption instead of the
 * destination card. This prevents a selected sibling date from displaying a
 * flight/stay count or "from" price that belongs to another date variant.
 * 
 * Keep property/destination metadata such as amenities, images, descriptions,
 * reviews, and static events OUT of this model. Those are deduped at their
 * natural property/destination scope and selected by candidate/date identity.
 * @export
 * @interface DateOptionComponentSummary
 */
export interface DateOptionComponentSummary {
    /**
     * 
     * @type {TripPrice}
     * @memberof DateOptionComponentSummary
     */
    minPrice?: TripPrice | null;
    /**
     * 
     * @type {number}
     * @memberof DateOptionComponentSummary
     */
    optionCount?: number | null;
}

/**
 * Check if a given object implements the DateOptionComponentSummary interface.
 */
export function instanceOfDateOptionComponentSummary(value: object): value is DateOptionComponentSummary {
    return true;
}

export function DateOptionComponentSummaryFromJSON(json: any): DateOptionComponentSummary {
    return DateOptionComponentSummaryFromJSONTyped(json, false);
}

export function DateOptionComponentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateOptionComponentSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'minPrice': json['min_price'] === undefined ? undefined : json['min_price'] === null ? null : TripPriceFromJSON(json['min_price']),
        'optionCount': json['option_count'] === undefined ? undefined : json['option_count'] === null ? null : json['option_count'],
    };
}

export function DateOptionComponentSummaryToJSON(json: any): DateOptionComponentSummary {
    return DateOptionComponentSummaryToJSONTyped(json, false);
}

export function DateOptionComponentSummaryToJSONTyped(value?: DateOptionComponentSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_price': TripPriceToJSON(value['minPrice']),
        'option_count': value['optionCount'],
    };
}

