/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DateOptionKind = {
    Requested: 'requested',
    Nearby: 'nearby',
    Alternative: 'alternative',
    Defaulted: 'defaulted'
} as const;
export type DateOptionKind = typeof DateOptionKind[keyof typeof DateOptionKind];


export function instanceOfDateOptionKind(value: any): boolean {
    for (const key in DateOptionKind) {
        if (Object.prototype.hasOwnProperty.call(DateOptionKind, key)) {
            if (DateOptionKind[key as keyof typeof DateOptionKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DateOptionKindFromJSON(json: any): DateOptionKind {
    return DateOptionKindFromJSONTyped(json, false);
}

export function DateOptionKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateOptionKind {
    return json as DateOptionKind;
}

export function DateOptionKindToJSON(value?: DateOptionKind | null): any {
    return value as any;
}

export function DateOptionKindToJSONTyped(value: any, ignoreDiscriminator: boolean): DateOptionKind {
    return value as DateOptionKind;
}

