/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BudgetAmount } from './BudgetAmount';
import {
    BudgetAmountFromJSON,
    BudgetAmountFromJSONTyped,
    BudgetAmountToJSON,
    BudgetAmountToJSONTyped,
} from './BudgetAmount';

/**
 * 
 * @export
 * @interface DiscoveryInterpretation
 */
export interface DiscoveryInterpretation {
    /**
     * 
     * @type {number}
     * @memberof DiscoveryInterpretation
     */
    adults?: number;
    /**
     * 
     * @type {BudgetAmount}
     * @memberof DiscoveryInterpretation
     */
    budgetAmount?: BudgetAmount | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryInterpretation
     */
    budgetCurrency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryInterpretation
     */
    budgetScope?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryInterpretation
     */
    categories?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryInterpretation
     */
    children?: number;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryInterpretation
     */
    dateMode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryInterpretation
     */
    dateText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryInterpretation
     */
    durationNights?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryInterpretation
     */
    endDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryInterpretation
     */
    origin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryInterpretation
     */
    startDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryInterpretation
     */
    title: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryInterpretation
     */
    warnings?: Array<string>;
}

/**
 * Check if a given object implements the DiscoveryInterpretation interface.
 */
export function instanceOfDiscoveryInterpretation(value: object): value is DiscoveryInterpretation {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function DiscoveryInterpretationFromJSON(json: any): DiscoveryInterpretation {
    return DiscoveryInterpretationFromJSONTyped(json, false);
}

export function DiscoveryInterpretationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryInterpretation {
    if (json == null) {
        return json;
    }
    return {
        
        'adults': json['adults'] == null ? undefined : json['adults'],
        'budgetAmount': json['budget_amount'] === undefined ? undefined : json['budget_amount'] === null ? null : BudgetAmountFromJSON(json['budget_amount']),
        'budgetCurrency': json['budget_currency'] === undefined ? undefined : json['budget_currency'] === null ? null : json['budget_currency'],
        'budgetScope': json['budget_scope'] === undefined ? undefined : json['budget_scope'] === null ? null : json['budget_scope'],
        'categories': json['categories'] == null ? undefined : json['categories'],
        'children': json['children'] == null ? undefined : json['children'],
        'dateMode': json['date_mode'] === undefined ? undefined : json['date_mode'] === null ? null : json['date_mode'],
        'dateText': json['date_text'] === undefined ? undefined : json['date_text'] === null ? null : json['date_text'],
        'durationNights': json['duration_nights'] === undefined ? undefined : json['duration_nights'] === null ? null : json['duration_nights'],
        'endDate': json['end_date'] === undefined ? undefined : json['end_date'] === null ? null : json['end_date'],
        'origin': json['origin'] === undefined ? undefined : json['origin'] === null ? null : json['origin'],
        'startDate': json['start_date'] === undefined ? undefined : json['start_date'] === null ? null : json['start_date'],
        'title': json['title'],
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
    };
}

export function DiscoveryInterpretationToJSON(json: any): DiscoveryInterpretation {
    return DiscoveryInterpretationToJSONTyped(json, false);
}

export function DiscoveryInterpretationToJSONTyped(value?: DiscoveryInterpretation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adults': value['adults'],
        'budget_amount': BudgetAmountToJSON(value['budgetAmount']),
        'budget_currency': value['budgetCurrency'],
        'budget_scope': value['budgetScope'],
        'categories': value['categories'],
        'children': value['children'],
        'date_mode': value['dateMode'],
        'date_text': value['dateText'],
        'duration_nights': value['durationNights'],
        'end_date': value['endDate'],
        'origin': value['origin'],
        'start_date': value['startDate'],
        'title': value['title'],
        'warnings': value['warnings'],
    };
}

