/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscoveryPreferences
 */
export interface DiscoveryPreferences {
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryPreferences
     */
    activityPreferences?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryPreferences
     */
    eventTypes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryPreferences
     */
    interests?: Array<string>;
    /**
     * 
     * @type {DiscoveryPreferencesPaceEnum}
     * @memberof DiscoveryPreferences
     */
    pace?: DiscoveryPreferencesPaceEnum | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryPreferences
     */
    tripDimensions?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryPreferences
     */
    weather?: string | null;
}


/**
 * @export
 */
export const DiscoveryPreferencesPaceEnum = {
    Relaxed: 'relaxed',
    Balanced: 'balanced',
    Busy: 'busy'
} as const;
export type DiscoveryPreferencesPaceEnum = typeof DiscoveryPreferencesPaceEnum[keyof typeof DiscoveryPreferencesPaceEnum];


/**
 * Check if a given object implements the DiscoveryPreferences interface.
 */
export function instanceOfDiscoveryPreferences(value: object): value is DiscoveryPreferences {
    return true;
}

export function DiscoveryPreferencesFromJSON(json: any): DiscoveryPreferences {
    return DiscoveryPreferencesFromJSONTyped(json, false);
}

export function DiscoveryPreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryPreferences {
    if (json == null) {
        return json;
    }
    return {
        
        'activityPreferences': json['activity_preferences'] == null ? undefined : json['activity_preferences'],
        'eventTypes': json['event_types'] == null ? undefined : json['event_types'],
        'interests': json['interests'] == null ? undefined : json['interests'],
        'pace': json['pace'] === undefined ? undefined : json['pace'] === null ? null : json['pace'],
        'tripDimensions': json['trip_dimensions'] == null ? undefined : json['trip_dimensions'],
        'weather': json['weather'] === undefined ? undefined : json['weather'] === null ? null : json['weather'],
    };
}

export function DiscoveryPreferencesToJSON(json: any): DiscoveryPreferences {
    return DiscoveryPreferencesToJSONTyped(json, false);
}

export function DiscoveryPreferencesToJSONTyped(value?: DiscoveryPreferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activity_preferences': value['activityPreferences'],
        'event_types': value['eventTypes'],
        'interests': value['interests'],
        'pace': value['pace'],
        'trip_dimensions': value['tripDimensions'],
        'weather': value['weather'],
    };
}

