/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageObject } from './ImageObject';
import {
    ImageObjectFromJSON,
    ImageObjectFromJSONTyped,
    ImageObjectToJSON,
    ImageObjectToJSONTyped,
} from './ImageObject';

/**
 * 
 * @export
 * @interface DiscoveryDestination
 */
export interface DiscoveryDestination {
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestination
     */
    countryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestination
     */
    countryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestination
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestination
     */
    id: string;
    /**
     * 
     * @type {ImageObject}
     * @memberof DiscoveryDestination
     */
    image?: ImageObject | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestination
     */
    kind?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestination
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestination
     */
    region?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestination
     */
    subtitle?: string | null;
}

/**
 * Check if a given object implements the DiscoveryDestination interface.
 */
export function instanceOfDiscoveryDestination(value: object): value is DiscoveryDestination {
    if ((!('displayName' in (value as Record<string, any>)) && !('display_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['displayName'] === undefined && (value as Record<string, any>)['display_name'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DiscoveryDestinationFromJSON(json: any): DiscoveryDestination {
    return DiscoveryDestinationFromJSONTyped(json, false);
}

export function DiscoveryDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCode': json['country_code'] === undefined ? undefined : json['country_code'] === null ? null : json['country_code'],
        'countryName': json['country_name'] === undefined ? undefined : json['country_name'] === null ? null : json['country_name'],
        'displayName': json['display_name'],
        'id': json['id'],
        'image': json['image'] === undefined ? undefined : json['image'] === null ? null : ImageObjectFromJSON(json['image']),
        'kind': json['kind'] === undefined ? undefined : json['kind'] === null ? null : json['kind'],
        'name': json['name'],
        'region': json['region'] === undefined ? undefined : json['region'] === null ? null : json['region'],
        'subtitle': json['subtitle'] === undefined ? undefined : json['subtitle'] === null ? null : json['subtitle'],
    };
}

export function DiscoveryDestinationToJSON(json: any): DiscoveryDestination {
    return DiscoveryDestinationToJSONTyped(json, false);
}

export function DiscoveryDestinationToJSONTyped(value?: DiscoveryDestination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country_code': value['countryCode'],
        'country_name': value['countryName'],
        'display_name': value['displayName'],
        'id': value['id'],
        'image': ImageObjectToJSON(value['image']),
        'kind': value['kind'],
        'name': value['name'],
        'region': value['region'],
        'subtitle': value['subtitle'],
    };
}

