/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscoveryDateBound
 */
export interface DiscoveryDateBound {
    /**
     * 
     * @type {Date}
     * @memberof DiscoveryDateBound
     */
    earliest?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof DiscoveryDateBound
     */
    latest?: Date | null;
}

/**
 * Check if a given object implements the DiscoveryDateBound interface.
 */
export function instanceOfDiscoveryDateBound(value: object): value is DiscoveryDateBound {
    return true;
}

export function DiscoveryDateBoundFromJSON(json: any): DiscoveryDateBound {
    return DiscoveryDateBoundFromJSONTyped(json, false);
}

export function DiscoveryDateBoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryDateBound {
    if (json == null) {
        return json;
    }
    return {
        
        'earliest': json['earliest'] === undefined ? undefined : json['earliest'] === null ? null : (new Date(json['earliest'])),
        'latest': json['latest'] === undefined ? undefined : json['latest'] === null ? null : (new Date(json['latest'])),
    };
}

export function DiscoveryDateBoundToJSON(json: any): DiscoveryDateBound {
    return DiscoveryDateBoundToJSONTyped(json, false);
}

export function DiscoveryDateBoundToJSONTyped(value?: DiscoveryDateBound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'earliest': value['earliest'] == null ? value['earliest'] : value['earliest'].toISOString().substring(0,10),
        'latest': value['latest'] == null ? value['latest'] : value['latest'].toISOString().substring(0,10),
    };
}

