/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscoveryDateOption } from './DiscoveryDateOption';
import {
    DiscoveryDateOptionFromJSON,
    DiscoveryDateOptionFromJSONTyped,
    DiscoveryDateOptionToJSON,
    DiscoveryDateOptionToJSONTyped,
} from './DiscoveryDateOption';
import type { DiscoveryDestination } from './DiscoveryDestination';
import {
    DiscoveryDestinationFromJSON,
    DiscoveryDestinationFromJSONTyped,
    DiscoveryDestinationToJSON,
    DiscoveryDestinationToJSONTyped,
} from './DiscoveryDestination';
import type { DiscoveryFit } from './DiscoveryFit';
import {
    DiscoveryFitFromJSON,
    DiscoveryFitFromJSONTyped,
    DiscoveryFitToJSON,
    DiscoveryFitToJSONTyped,
} from './DiscoveryFit';
import type { DiscoverySearchInputsAvailable } from './DiscoverySearchInputsAvailable';
import {
    DiscoverySearchInputsAvailableFromJSON,
    DiscoverySearchInputsAvailableFromJSONTyped,
    DiscoverySearchInputsAvailableToJSON,
    DiscoverySearchInputsAvailableToJSONTyped,
} from './DiscoverySearchInputsAvailable';

/**
 * 
 * @export
 * @interface DiscoveryOpportunity
 */
export interface DiscoveryOpportunity {
    /**
     * 
     * @type {Array<DiscoveryDateOption>}
     * @memberof DiscoveryOpportunity
     */
    dateOptions?: Array<DiscoveryDateOption>;
    /**
     * 
     * @type {DiscoveryDestination}
     * @memberof DiscoveryOpportunity
     */
    destination: DiscoveryDestination;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryOpportunity
     */
    destinationAirportIataCodes?: Array<string>;
    /**
     * 
     * @type {DiscoveryFit}
     * @memberof DiscoveryOpportunity
     */
    fit?: DiscoveryFit;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryOpportunity
     */
    opportunityId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryOpportunity
     */
    originAirportIataCodes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryOpportunity
     */
    rank: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryOpportunity
     */
    reasons?: Array<string>;
    /**
     * 
     * @type {DiscoverySearchInputsAvailable}
     * @memberof DiscoveryOpportunity
     */
    searchInputsAvailable?: DiscoverySearchInputsAvailable;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryOpportunity
     */
    tags?: Array<string>;
    /**
     * 
     * @type {DiscoveryOpportunityVerificationStatusEnum}
     * @memberof DiscoveryOpportunity
     */
    verificationStatus?: DiscoveryOpportunityVerificationStatusEnum;
}


/**
 * @export
 */
export const DiscoveryOpportunityVerificationStatusEnum = {
    NotVerified: 'not_verified'
} as const;
export type DiscoveryOpportunityVerificationStatusEnum = typeof DiscoveryOpportunityVerificationStatusEnum[keyof typeof DiscoveryOpportunityVerificationStatusEnum];


/**
 * Check if a given object implements the DiscoveryOpportunity interface.
 */
export function instanceOfDiscoveryOpportunity(value: object): value is DiscoveryOpportunity {
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if ((!('opportunityId' in (value as Record<string, any>)) && !('opportunity_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['opportunityId'] === undefined && (value as Record<string, any>)['opportunity_id'] === undefined)) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    return true;
}

export function DiscoveryOpportunityFromJSON(json: any): DiscoveryOpportunity {
    return DiscoveryOpportunityFromJSONTyped(json, false);
}

export function DiscoveryOpportunityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryOpportunity {
    if (json == null) {
        return json;
    }
    return {
        
        'dateOptions': json['date_options'] == null ? undefined : ((json['date_options'] as Array<any>).map(DiscoveryDateOptionFromJSON)),
        'destination': DiscoveryDestinationFromJSON(json['destination']),
        'destinationAirportIataCodes': json['destination_airport_iata_codes'] == null ? undefined : json['destination_airport_iata_codes'],
        'fit': json['fit'] == null ? undefined : DiscoveryFitFromJSON(json['fit']),
        'opportunityId': json['opportunity_id'],
        'originAirportIataCodes': json['origin_airport_iata_codes'] == null ? undefined : json['origin_airport_iata_codes'],
        'rank': json['rank'],
        'reasons': json['reasons'] == null ? undefined : json['reasons'],
        'searchInputsAvailable': json['search_inputs_available'] == null ? undefined : DiscoverySearchInputsAvailableFromJSON(json['search_inputs_available']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'verificationStatus': json['verification_status'] == null ? undefined : json['verification_status'],
    };
}

export function DiscoveryOpportunityToJSON(json: any): DiscoveryOpportunity {
    return DiscoveryOpportunityToJSONTyped(json, false);
}

export function DiscoveryOpportunityToJSONTyped(value?: DiscoveryOpportunity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date_options': value['dateOptions'] == null ? undefined : ((value['dateOptions'] as Array<any>).map(DiscoveryDateOptionToJSON)),
        'destination': DiscoveryDestinationToJSON(value['destination']),
        'destination_airport_iata_codes': value['destinationAirportIataCodes'],
        'fit': DiscoveryFitToJSON(value['fit']),
        'opportunity_id': value['opportunityId'],
        'origin_airport_iata_codes': value['originAirportIataCodes'],
        'rank': value['rank'],
        'reasons': value['reasons'],
        'search_inputs_available': DiscoverySearchInputsAvailableToJSON(value['searchInputsAvailable']),
        'tags': value['tags'],
        'verification_status': value['verificationStatus'],
    };
}

