/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscoveryDateOption
 */
export interface DiscoveryDateOption {
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDateOption
     */
    dateOptionId?: string | null;
    /**
     * 
     * @type {DiscoveryDateOptionDateTypeEnum}
     * @memberof DiscoveryDateOption
     */
    dateType?: DiscoveryDateOptionDateTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof DiscoveryDateOption
     */
    endDate: Date;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryDateOption
     */
    nights: number;
    /**
     * 
     * @type {Date}
     * @memberof DiscoveryDateOption
     */
    startDate: Date;
}


/**
 * @export
 */
export const DiscoveryDateOptionDateTypeEnum = {
    Primary: 'primary',
    FlexibleWindow: 'flexible_window',
    NearbyAlternative: 'nearby_alternative',
    Unknown: 'unknown'
} as const;
export type DiscoveryDateOptionDateTypeEnum = typeof DiscoveryDateOptionDateTypeEnum[keyof typeof DiscoveryDateOptionDateTypeEnum];


/**
 * Check if a given object implements the DiscoveryDateOption interface.
 */
export function instanceOfDiscoveryDateOption(value: object): value is DiscoveryDateOption {
    if ((!('endDate' in (value as Record<string, any>)) && !('end_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['endDate'] === undefined && (value as Record<string, any>)['end_date'] === undefined)) return false;
    if (!('nights' in value) || value['nights'] === undefined) return false;
    if ((!('startDate' in (value as Record<string, any>)) && !('start_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['startDate'] === undefined && (value as Record<string, any>)['start_date'] === undefined)) return false;
    return true;
}

export function DiscoveryDateOptionFromJSON(json: any): DiscoveryDateOption {
    return DiscoveryDateOptionFromJSONTyped(json, false);
}

export function DiscoveryDateOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryDateOption {
    if (json == null) {
        return json;
    }
    return {
        
        'dateOptionId': json['date_option_id'] === undefined ? undefined : json['date_option_id'] === null ? null : json['date_option_id'],
        'dateType': json['date_type'] == null ? undefined : json['date_type'],
        'endDate': (new Date(json['end_date'])),
        'nights': json['nights'],
        'startDate': (new Date(json['start_date'])),
    };
}

export function DiscoveryDateOptionToJSON(json: any): DiscoveryDateOption {
    return DiscoveryDateOptionToJSONTyped(json, false);
}

export function DiscoveryDateOptionToJSONTyped(value?: DiscoveryDateOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date_option_id': value['dateOptionId'],
        'date_type': value['dateType'],
        'end_date': value['endDate'].toISOString().substring(0,10),
        'nights': value['nights'],
        'start_date': value['startDate'].toISOString().substring(0,10),
    };
}

