/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Canonical destination identity from the active Discovery planner snapshot.
 * @export
 * @interface DiscoveryDestinationReference
 */
export interface DiscoveryDestinationReference {
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestinationReference
     */
    countryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestinationReference
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestinationReference
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestinationReference
     */
    kind?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryDestinationReference
     */
    lat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryDestinationReference
     */
    lon?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestinationReference
     */
    name: string;
}

/**
 * Check if a given object implements the DiscoveryDestinationReference interface.
 */
export function instanceOfDiscoveryDestinationReference(value: object): value is DiscoveryDestinationReference {
    if ((!('displayName' in (value as Record<string, any>)) && !('display_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['displayName'] === undefined && (value as Record<string, any>)['display_name'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DiscoveryDestinationReferenceFromJSON(json: any): DiscoveryDestinationReference {
    return DiscoveryDestinationReferenceFromJSONTyped(json, false);
}

export function DiscoveryDestinationReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryDestinationReference {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCode': json['country_code'] === undefined ? undefined : json['country_code'] === null ? null : json['country_code'],
        'displayName': json['display_name'],
        'id': json['id'],
        'kind': json['kind'] === undefined ? undefined : json['kind'] === null ? null : json['kind'],
        'lat': json['lat'] === undefined ? undefined : json['lat'] === null ? null : json['lat'],
        'lon': json['lon'] === undefined ? undefined : json['lon'] === null ? null : json['lon'],
        'name': json['name'],
    };
}

export function DiscoveryDestinationReferenceToJSON(json: any): DiscoveryDestinationReference {
    return DiscoveryDestinationReferenceToJSONTyped(json, false);
}

export function DiscoveryDestinationReferenceToJSONTyped(value?: DiscoveryDestinationReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country_code': value['countryCode'],
        'display_name': value['displayName'],
        'id': value['id'],
        'kind': value['kind'],
        'lat': value['lat'],
        'lon': value['lon'],
        'name': value['name'],
    };
}

