/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Stable qualitative fit. Raw planner scores are deliberately private.
 * @export
 * @interface DiscoveryFit
 */
export interface DiscoveryFit {
    /**
     * 
     * @type {DiscoveryFitLabelEnum}
     * @memberof DiscoveryFit
     */
    label?: DiscoveryFitLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryFit
     */
    reason?: string | null;
}


/**
 * @export
 */
export const DiscoveryFitLabelEnum = {
    Strong: 'strong',
    Possible: 'possible',
    Stretch: 'stretch',
    Unknown: 'unknown'
} as const;
export type DiscoveryFitLabelEnum = typeof DiscoveryFitLabelEnum[keyof typeof DiscoveryFitLabelEnum];


/**
 * Check if a given object implements the DiscoveryFit interface.
 */
export function instanceOfDiscoveryFit(value: object): value is DiscoveryFit {
    return true;
}

export function DiscoveryFitFromJSON(json: any): DiscoveryFit {
    return DiscoveryFitFromJSONTyped(json, false);
}

export function DiscoveryFitFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryFit {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function DiscoveryFitToJSON(json: any): DiscoveryFit {
    return DiscoveryFitToJSONTyped(json, false);
}

export function DiscoveryFitToJSONTyped(value?: DiscoveryFit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'reason': value['reason'],
    };
}

