/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscoveryDestinationReference } from './DiscoveryDestinationReference';
import {
    DiscoveryDestinationReferenceFromJSON,
    DiscoveryDestinationReferenceFromJSONTyped,
    DiscoveryDestinationReferenceToJSON,
    DiscoveryDestinationReferenceToJSONTyped,
} from './DiscoveryDestinationReference';

/**
 * Public destination lookup result for clients authoring destination_ids.
 * @export
 * @interface DiscoveryDestinationLookupResponse
 */
export interface DiscoveryDestinationLookupResponse {
    /**
     * 
     * @type {Array<DiscoveryDestinationReference>}
     * @memberof DiscoveryDestinationLookupResponse
     */
    destinations?: Array<DiscoveryDestinationReference>;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDestinationLookupResponse
     */
    query: string;
}

/**
 * Check if a given object implements the DiscoveryDestinationLookupResponse interface.
 */
export function instanceOfDiscoveryDestinationLookupResponse(value: object): value is DiscoveryDestinationLookupResponse {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function DiscoveryDestinationLookupResponseFromJSON(json: any): DiscoveryDestinationLookupResponse {
    return DiscoveryDestinationLookupResponseFromJSONTyped(json, false);
}

export function DiscoveryDestinationLookupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryDestinationLookupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'destinations': json['destinations'] == null ? undefined : ((json['destinations'] as Array<any>).map(DiscoveryDestinationReferenceFromJSON)),
        'query': json['query'],
    };
}

export function DiscoveryDestinationLookupResponseToJSON(json: any): DiscoveryDestinationLookupResponse {
    return DiscoveryDestinationLookupResponseToJSONTyped(json, false);
}

export function DiscoveryDestinationLookupResponseToJSONTyped(value?: DiscoveryDestinationLookupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinations': value['destinations'] == null ? undefined : ((value['destinations'] as Array<any>).map(DiscoveryDestinationReferenceToJSON)),
        'query': value['query'],
    };
}

