/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscoveryDateBound } from './DiscoveryDateBound';
import {
    DiscoveryDateBoundFromJSON,
    DiscoveryDateBoundFromJSONTyped,
    DiscoveryDateBoundToJSON,
    DiscoveryDateBoundToJSONTyped,
} from './DiscoveryDateBound';
import type { DiscoveryOuterWindow } from './DiscoveryOuterWindow';
import {
    DiscoveryOuterWindowFromJSON,
    DiscoveryOuterWindowFromJSONTyped,
    DiscoveryOuterWindowToJSON,
    DiscoveryOuterWindowToJSONTyped,
} from './DiscoveryOuterWindow';

/**
 * 
 * @export
 * @interface DiscoveryDates
 */
export interface DiscoveryDates {
    /**
     * 
     * @type {string}
     * @memberof DiscoveryDates
     */
    dateText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryDates
     */
    durationNights?: number | null;
    /**
     * 
     * @type {DiscoveryDateBound}
     * @memberof DiscoveryDates
     */
    end?: DiscoveryDateBound | null;
    /**
     * 
     * @type {Date}
     * @memberof DiscoveryDates
     */
    endDate?: Date | null;
    /**
     * 
     * @type {DiscoveryOuterWindow}
     * @memberof DiscoveryDates
     */
    outerWindow?: DiscoveryOuterWindow | null;
    /**
     * 
     * @type {DiscoveryDateBound}
     * @memberof DiscoveryDates
     */
    start?: DiscoveryDateBound | null;
    /**
     * 
     * @type {Date}
     * @memberof DiscoveryDates
     */
    startDate?: Date | null;
}

/**
 * Check if a given object implements the DiscoveryDates interface.
 */
export function instanceOfDiscoveryDates(value: object): value is DiscoveryDates {
    return true;
}

export function DiscoveryDatesFromJSON(json: any): DiscoveryDates {
    return DiscoveryDatesFromJSONTyped(json, false);
}

export function DiscoveryDatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryDates {
    if (json == null) {
        return json;
    }
    return {
        
        'dateText': json['date_text'] === undefined ? undefined : json['date_text'] === null ? null : json['date_text'],
        'durationNights': json['duration_nights'] === undefined ? undefined : json['duration_nights'] === null ? null : json['duration_nights'],
        'end': json['end'] === undefined ? undefined : json['end'] === null ? null : DiscoveryDateBoundFromJSON(json['end']),
        'endDate': json['end_date'] === undefined ? undefined : json['end_date'] === null ? null : (new Date(json['end_date'])),
        'outerWindow': json['outer_window'] === undefined ? undefined : json['outer_window'] === null ? null : DiscoveryOuterWindowFromJSON(json['outer_window']),
        'start': json['start'] === undefined ? undefined : json['start'] === null ? null : DiscoveryDateBoundFromJSON(json['start']),
        'startDate': json['start_date'] === undefined ? undefined : json['start_date'] === null ? null : (new Date(json['start_date'])),
    };
}

export function DiscoveryDatesToJSON(json: any): DiscoveryDates {
    return DiscoveryDatesToJSONTyped(json, false);
}

export function DiscoveryDatesToJSONTyped(value?: DiscoveryDates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date_text': value['dateText'],
        'duration_nights': value['durationNights'],
        'end': DiscoveryDateBoundToJSON(value['end']),
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'outer_window': DiscoveryOuterWindowToJSON(value['outerWindow']),
        'start': DiscoveryDateBoundToJSON(value['start']),
        'start_date': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString().substring(0,10),
    };
}

