/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StandardizedEvent } from './StandardizedEvent';
import {
    StandardizedEventFromJSON,
    StandardizedEventFromJSONTyped,
    StandardizedEventToJSON,
    StandardizedEventToJSONTyped,
} from './StandardizedEvent';

/**
 * 
 * @export
 * @interface EventDetail
 */
export interface EventDetail {
    /**
     * 
     * @type {StandardizedEvent}
     * @memberof EventDetail
     */
    event: StandardizedEvent;
}

/**
 * Check if a given object implements the EventDetail interface.
 */
export function instanceOfEventDetail(value: object): value is EventDetail {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function EventDetailFromJSON(json: any): EventDetail {
    return EventDetailFromJSONTyped(json, false);
}

export function EventDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'event': StandardizedEventFromJSON(json['event']),
    };
}

export function EventDetailToJSON(json: any): EventDetail {
    return EventDetailToJSONTyped(json, false);
}

export function EventDetailToJSONTyped(value?: EventDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': StandardizedEventToJSON(value['event']),
    };
}

