/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlimStandardizedFlightOffer } from './SlimStandardizedFlightOffer';
import {
    SlimStandardizedFlightOfferFromJSON,
    SlimStandardizedFlightOfferFromJSONTyped,
    SlimStandardizedFlightOfferToJSON,
    SlimStandardizedFlightOfferToJSONTyped,
} from './SlimStandardizedFlightOffer';

/**
 * 
 * @export
 * @interface FlightDetail
 */
export interface FlightDetail {
    /**
     * 
     * @type {SlimStandardizedFlightOffer}
     * @memberof FlightDetail
     */
    flight: SlimStandardizedFlightOffer;
}

/**
 * Check if a given object implements the FlightDetail interface.
 */
export function instanceOfFlightDetail(value: object): value is FlightDetail {
    if (!('flight' in value) || value['flight'] === undefined) return false;
    return true;
}

export function FlightDetailFromJSON(json: any): FlightDetail {
    return FlightDetailFromJSONTyped(json, false);
}

export function FlightDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlightDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'flight': SlimStandardizedFlightOfferFromJSON(json['flight']),
    };
}

export function FlightDetailToJSON(json: any): FlightDetail {
    return FlightDetailToJSONTyped(json, false);
}

export function FlightDetailToJSONTyped(value?: FlightDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'flight': SlimStandardizedFlightOfferToJSON(value['flight']),
    };
}

