/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageAttribution } from './ImageAttribution';
import {
    ImageAttributionFromJSON,
    ImageAttributionFromJSONTyped,
    ImageAttributionToJSON,
    ImageAttributionToJSONTyped,
} from './ImageAttribution';

/**
 * 
 * @export
 * @interface ImageObject
 */
export interface ImageObject {
    /**
     * 
     * @type {ImageAttribution}
     * @memberof ImageObject
     */
    attribution?: ImageAttribution | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    blurHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    credits?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    downloadLocation?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ImageObject
     */
    height?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ImageObject
     */
    isFallback?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    license?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    originalUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    providerAssetId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    sourceUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ImageObject
     */
    usageKind?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ImageObject
     */
    width?: number | null;
}

/**
 * Check if a given object implements the ImageObject interface.
 */
export function instanceOfImageObject(value: object): value is ImageObject {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ImageObjectFromJSON(json: any): ImageObject {
    return ImageObjectFromJSONTyped(json, false);
}

export function ImageObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageObject {
    if (json == null) {
        return json;
    }
    return {
        
        'attribution': json['attribution'] === undefined ? undefined : json['attribution'] === null ? null : ImageAttributionFromJSON(json['attribution']),
        'blurHash': json['blur_hash'] === undefined ? undefined : json['blur_hash'] === null ? null : json['blur_hash'],
        'credits': json['credits'] === undefined ? undefined : json['credits'] === null ? null : json['credits'],
        'downloadLocation': json['download_location'] === undefined ? undefined : json['download_location'] === null ? null : json['download_location'],
        'height': json['height'] === undefined ? undefined : json['height'] === null ? null : json['height'],
        'isFallback': json['is_fallback'] === undefined ? undefined : json['is_fallback'] === null ? null : json['is_fallback'],
        'license': json['license'] === undefined ? undefined : json['license'] === null ? null : json['license'],
        'originalUrl': json['original_url'] === undefined ? undefined : json['original_url'] === null ? null : json['original_url'],
        'provider': json['provider'] === undefined ? undefined : json['provider'] === null ? null : json['provider'],
        'providerAssetId': json['provider_asset_id'] === undefined ? undefined : json['provider_asset_id'] === null ? null : json['provider_asset_id'],
        'sourceUrl': json['source_url'] === undefined ? undefined : json['source_url'] === null ? null : json['source_url'],
        'url': json['url'],
        'usageKind': json['usage_kind'] === undefined ? undefined : json['usage_kind'] === null ? null : json['usage_kind'],
        'width': json['width'] === undefined ? undefined : json['width'] === null ? null : json['width'],
    };
}

export function ImageObjectToJSON(json: any): ImageObject {
    return ImageObjectToJSONTyped(json, false);
}

export function ImageObjectToJSONTyped(value?: ImageObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribution': ImageAttributionToJSON(value['attribution']),
        'blur_hash': value['blurHash'],
        'credits': value['credits'],
        'download_location': value['downloadLocation'],
        'height': value['height'],
        'is_fallback': value['isFallback'],
        'license': value['license'],
        'original_url': value['originalUrl'],
        'provider': value['provider'],
        'provider_asset_id': value['providerAssetId'],
        'source_url': value['sourceUrl'],
        'url': value['url'],
        'usage_kind': value['usageKind'],
        'width': value['width'],
    };
}

