/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Internal Money representation.
 * amount_minor: integer value of the currency (e.g., cents)
 * currency: ISO 4217 currency code (e.g., "USD", "EUR")
 * raw_text: original raw text string if available
 * currency_source: source of currency inference (provider, symbol_inferred, unknown)
 * currency_confidence: confidence level of inference
 * @export
 * @interface Money
 */
export interface Money {
    /**
     * 
     * @type {number}
     * @memberof Money
     */
    amountMinor: number;
    /**
     * 
     * @type {string}
     * @memberof Money
     */
    currency: string;
    /**
     * 
     * @type {MoneyCurrencyConfidenceEnum}
     * @memberof Money
     */
    currencyConfidence?: MoneyCurrencyConfidenceEnum;
    /**
     * 
     * @type {MoneyCurrencySourceEnum}
     * @memberof Money
     */
    currencySource?: MoneyCurrencySourceEnum;
    /**
     * 
     * @type {string}
     * @memberof Money
     */
    rawText?: string | null;
}


/**
 * @export
 */
export const MoneyCurrencyConfidenceEnum = {
    High: 'high',
    Medium: 'medium',
    Low: 'low'
} as const;
export type MoneyCurrencyConfidenceEnum = typeof MoneyCurrencyConfidenceEnum[keyof typeof MoneyCurrencyConfidenceEnum];

/**
 * @export
 */
export const MoneyCurrencySourceEnum = {
    Provider: 'provider',
    SymbolInferred: 'symbol_inferred',
    Default: 'default',
    Unknown: 'unknown'
} as const;
export type MoneyCurrencySourceEnum = typeof MoneyCurrencySourceEnum[keyof typeof MoneyCurrencySourceEnum];


/**
 * Check if a given object implements the Money interface.
 */
export function instanceOfMoney(value: object): value is Money {
    if ((!('amountMinor' in (value as Record<string, any>)) && !('amount_minor' in (value as Record<string, any>))) || ((value as Record<string, any>)['amountMinor'] === undefined && (value as Record<string, any>)['amount_minor'] === undefined)) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function MoneyFromJSON(json: any): Money {
    return MoneyFromJSONTyped(json, false);
}

export function MoneyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Money {
    if (json == null) {
        return json;
    }
    return {
        
        'amountMinor': json['amount_minor'],
        'currency': json['currency'],
        'currencyConfidence': json['currency_confidence'] == null ? undefined : json['currency_confidence'],
        'currencySource': json['currency_source'] == null ? undefined : json['currency_source'],
        'rawText': json['raw_text'] === undefined ? undefined : json['raw_text'] === null ? null : json['raw_text'],
    };
}

export function MoneyToJSON(json: any): Money {
    return MoneyToJSONTyped(json, false);
}

export function MoneyToJSONTyped(value?: Money | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_minor': value['amountMinor'],
        'currency': value['currency'],
        'currency_confidence': value['currencyConfidence'],
        'currency_source': value['currencySource'],
        'raw_text': value['rawText'],
    };
}

