/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PriceInsightKind = {
    AbsoluteLowPrice: 'absolute_low_price',
    RelativeValue: 'relative_value',
    HistoricalDrop: 'historical_drop',
    HistoricalLow: 'historical_low',
    ProviderDeal: 'provider_deal'
} as const;
export type PriceInsightKind = typeof PriceInsightKind[keyof typeof PriceInsightKind];


export function instanceOfPriceInsightKind(value: any): boolean {
    for (const key in PriceInsightKind) {
        if (Object.prototype.hasOwnProperty.call(PriceInsightKind, key)) {
            if (PriceInsightKind[key as keyof typeof PriceInsightKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PriceInsightKindFromJSON(json: any): PriceInsightKind {
    return PriceInsightKindFromJSONTyped(json, false);
}

export function PriceInsightKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceInsightKind {
    return json as PriceInsightKind;
}

export function PriceInsightKindToJSON(value?: PriceInsightKind | null): any {
    return value as any;
}

export function PriceInsightKindToJSONTyped(value: any, ignoreDiscriminator: boolean): PriceInsightKind {
    return value as PriceInsightKind;
}

