/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PriceInsightSource = {
    VerifiedObservation: 'verified_observation',
    LearnedSignal: 'learned_signal',
    HistoricalObservations: 'historical_observations',
    Provider: 'provider'
} as const;
export type PriceInsightSource = typeof PriceInsightSource[keyof typeof PriceInsightSource];


export function instanceOfPriceInsightSource(value: any): boolean {
    for (const key in PriceInsightSource) {
        if (Object.prototype.hasOwnProperty.call(PriceInsightSource, key)) {
            if (PriceInsightSource[key as keyof typeof PriceInsightSource] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PriceInsightSourceFromJSON(json: any): PriceInsightSource {
    return PriceInsightSourceFromJSONTyped(json, false);
}

export function PriceInsightSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceInsightSource {
    return json as PriceInsightSource;
}

export function PriceInsightSourceToJSON(value?: PriceInsightSource | null): any {
    return value as any;
}

export function PriceInsightSourceToJSONTyped(value: any, ignoreDiscriminator: boolean): PriceInsightSource {
    return value as PriceInsightSource;
}

