/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PriceBasis = {
    OneWayPerTraveller: 'one_way_per_traveller',
    ReturnPerTraveller: 'return_per_traveller',
    FlightPartyTotal: 'flight_party_total',
    AccommodationPerNight: 'accommodation_per_night',
    AccommodationPerGuest: 'accommodation_per_guest',
    AccommodationTotal: 'accommodation_total',
    BundlePerTraveller: 'bundle_per_traveller',
    BundlePartyTotal: 'bundle_party_total'
} as const;
export type PriceBasis = typeof PriceBasis[keyof typeof PriceBasis];


export function instanceOfPriceBasis(value: any): boolean {
    for (const key in PriceBasis) {
        if (Object.prototype.hasOwnProperty.call(PriceBasis, key)) {
            if (PriceBasis[key as keyof typeof PriceBasis] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PriceBasisFromJSON(json: any): PriceBasis {
    return PriceBasisFromJSONTyped(json, false);
}

export function PriceBasisFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceBasis {
    return json as PriceBasis;
}

export function PriceBasisToJSON(value?: PriceBasis | null): any {
    return value as any;
}

export function PriceBasisToJSONTyped(value: any, ignoreDiscriminator: boolean): PriceBasis {
    return value as PriceBasis;
}

