/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PriceInsightScope = {
    Flight: 'flight',
    Accommodation: 'accommodation',
    Bundle: 'bundle'
} as const;
export type PriceInsightScope = typeof PriceInsightScope[keyof typeof PriceInsightScope];


export function instanceOfPriceInsightScope(value: any): boolean {
    for (const key in PriceInsightScope) {
        if (Object.prototype.hasOwnProperty.call(PriceInsightScope, key)) {
            if (PriceInsightScope[key as keyof typeof PriceInsightScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PriceInsightScopeFromJSON(json: any): PriceInsightScope {
    return PriceInsightScopeFromJSONTyped(json, false);
}

export function PriceInsightScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceInsightScope {
    return json as PriceInsightScope;
}

export function PriceInsightScopeToJSON(value?: PriceInsightScope | null): any {
    return value as any;
}

export function PriceInsightScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): PriceInsightScope {
    return value as PriceInsightScope;
}

