/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceInsightKind } from './PriceInsightKind';
import {
    PriceInsightKindFromJSON,
    PriceInsightKindFromJSONTyped,
    PriceInsightKindToJSON,
    PriceInsightKindToJSONTyped,
} from './PriceInsightKind';
import type { PriceInsightSource } from './PriceInsightSource';
import {
    PriceInsightSourceFromJSON,
    PriceInsightSourceFromJSONTyped,
    PriceInsightSourceToJSON,
    PriceInsightSourceToJSONTyped,
} from './PriceInsightSource';
import type { PriceInsightScope } from './PriceInsightScope';
import {
    PriceInsightScopeFromJSON,
    PriceInsightScopeFromJSONTyped,
    PriceInsightScopeToJSON,
    PriceInsightScopeToJSONTyped,
} from './PriceInsightScope';
import type { PriceBasis } from './PriceBasis';
import {
    PriceBasisFromJSON,
    PriceBasisFromJSONTyped,
    PriceBasisToJSON,
    PriceBasisToJSONTyped,
} from './PriceBasis';

/**
 * A truthful, display-ready claim about one exact price identity.
 * @export
 * @interface PriceInsight
 */
export interface PriceInsight {
    /**
     * 
     * @type {PriceBasis}
     * @memberof PriceInsight
     */
    basis: PriceBasis;
    /**
     * 
     * @type {number}
     * @memberof PriceInsight
     */
    changeAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PriceInsight
     */
    changePercent?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PriceInsight
     */
    comparisonKey: string;
    /**
     * 
     * @type {number}
     * @memberof PriceInsight
     */
    confidence?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PriceInsight
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof PriceInsight
     */
    currentAmount: number;
    /**
     * 
     * @type {Date}
     * @memberof PriceInsight
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PriceInsight
     */
    explanation: string;
    /**
     * 
     * @type {string}
     * @memberof PriceInsight
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof PriceInsight
     */
    isNewLow?: boolean | null;
    /**
     * 
     * @type {PriceInsightKind}
     * @memberof PriceInsight
     */
    kind: PriceInsightKind;
    /**
     * 
     * @type {string}
     * @memberof PriceInsight
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof PriceInsight
     */
    observationCount?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PriceInsight
     */
    observedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof PriceInsight
     */
    previousAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PriceInsight
     */
    providerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PriceInsight
     */
    relativeBand?: string | null;
    /**
     * 
     * @type {PriceInsightScope}
     * @memberof PriceInsight
     */
    scope: PriceInsightScope;
    /**
     * 
     * @type {PriceInsightSource}
     * @memberof PriceInsight
     */
    source: PriceInsightSource;
    /**
     * 
     * @type {number}
     * @memberof PriceInsight
     */
    thresholdAmount?: number | null;
}



/**
 * Check if a given object implements the PriceInsight interface.
 */
export function instanceOfPriceInsight(value: object): value is PriceInsight {
    if (!('basis' in value) || value['basis'] === undefined) return false;
    if ((!('comparisonKey' in (value as Record<string, any>)) && !('comparison_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['comparisonKey'] === undefined && (value as Record<string, any>)['comparison_key'] === undefined)) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if ((!('currentAmount' in (value as Record<string, any>)) && !('current_amount' in (value as Record<string, any>))) || ((value as Record<string, any>)['currentAmount'] === undefined && (value as Record<string, any>)['current_amount'] === undefined)) return false;
    if (!('explanation' in value) || value['explanation'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if ((!('observedAt' in (value as Record<string, any>)) && !('observed_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['observedAt'] === undefined && (value as Record<string, any>)['observed_at'] === undefined)) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function PriceInsightFromJSON(json: any): PriceInsight {
    return PriceInsightFromJSONTyped(json, false);
}

export function PriceInsightFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceInsight {
    if (json == null) {
        return json;
    }
    return {
        
        'basis': PriceBasisFromJSON(json['basis']),
        'changeAmount': json['change_amount'] === undefined ? undefined : json['change_amount'] === null ? null : json['change_amount'],
        'changePercent': json['change_percent'] === undefined ? undefined : json['change_percent'] === null ? null : json['change_percent'],
        'comparisonKey': json['comparison_key'],
        'confidence': json['confidence'] === undefined ? undefined : json['confidence'] === null ? null : json['confidence'],
        'currency': json['currency'],
        'currentAmount': json['current_amount'],
        'expiresAt': json['expires_at'] === undefined ? undefined : json['expires_at'] === null ? null : (new Date(json['expires_at'])),
        'explanation': json['explanation'],
        'id': json['id'],
        'isNewLow': json['is_new_low'] === undefined ? undefined : json['is_new_low'] === null ? null : json['is_new_low'],
        'kind': PriceInsightKindFromJSON(json['kind']),
        'label': json['label'],
        'observationCount': json['observation_count'] === undefined ? undefined : json['observation_count'] === null ? null : json['observation_count'],
        'observedAt': (new Date(json['observed_at'])),
        'previousAmount': json['previous_amount'] === undefined ? undefined : json['previous_amount'] === null ? null : json['previous_amount'],
        'providerName': json['provider_name'] === undefined ? undefined : json['provider_name'] === null ? null : json['provider_name'],
        'relativeBand': json['relative_band'] === undefined ? undefined : json['relative_band'] === null ? null : json['relative_band'],
        'scope': PriceInsightScopeFromJSON(json['scope']),
        'source': PriceInsightSourceFromJSON(json['source']),
        'thresholdAmount': json['threshold_amount'] === undefined ? undefined : json['threshold_amount'] === null ? null : json['threshold_amount'],
    };
}

export function PriceInsightToJSON(json: any): PriceInsight {
    return PriceInsightToJSONTyped(json, false);
}

export function PriceInsightToJSONTyped(value?: PriceInsight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'basis': PriceBasisToJSON(value['basis']),
        'change_amount': value['changeAmount'],
        'change_percent': value['changePercent'],
        'comparison_key': value['comparisonKey'],
        'confidence': value['confidence'],
        'currency': value['currency'],
        'current_amount': value['currentAmount'],
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'explanation': value['explanation'],
        'id': value['id'],
        'is_new_low': value['isNewLow'],
        'kind': PriceInsightKindToJSON(value['kind']),
        'label': value['label'],
        'observation_count': value['observationCount'],
        'observed_at': value['observedAt'].toISOString(),
        'previous_amount': value['previousAmount'],
        'provider_name': value['providerName'],
        'relative_band': value['relativeBand'],
        'scope': PriceInsightScopeToJSON(value['scope']),
        'source': PriceInsightSourceToJSON(value['source']),
        'threshold_amount': value['thresholdAmount'],
    };
}

