/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderUrl
 */
export interface ProviderUrl {
    /**
     * 
     * @type {string}
     * @memberof ProviderUrl
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderUrl
     */
    url: string;
}

/**
 * Check if a given object implements the ProviderUrl interface.
 */
export function instanceOfProviderUrl(value: object): value is ProviderUrl {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ProviderUrlFromJSON(json: any): ProviderUrl {
    return ProviderUrlFromJSONTyped(json, false);
}

export function ProviderUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderUrl {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
    };
}

export function ProviderUrlToJSON(json: any): ProviderUrl {
    return ProviderUrlToJSONTyped(json, false);
}

export function ProviderUrlToJSONTyped(value?: ProviderUrl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
    };
}

