/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceInsight } from './PriceInsight';
import {
    PriceInsightFromJSON,
    PriceInsightFromJSONTyped,
    PriceInsightToJSON,
    PriceInsightToJSONTyped,
} from './PriceInsight';

/**
 * 
 * @export
 * @interface StandardizedStayOffer
 */
export interface StandardizedStayOffer {
    /**
     * 
     * @type {string}
     * @memberof StandardizedStayOffer
     */
    checkInDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StandardizedStayOffer
     */
    checkOutDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StandardizedStayOffer
     */
    currency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StandardizedStayOffer
     */
    nightlyPrice?: number | null;
    /**
     * 
     * @type {Array<PriceInsight>}
     * @memberof StandardizedStayOffer
     */
    priceInsights?: Array<PriceInsight>;
    /**
     * 
     * @type {number}
     * @memberof StandardizedStayOffer
     */
    priceTotal?: number | null;
    /**
     * 
     * @type {PriceInsight}
     * @memberof StandardizedStayOffer
     */
    primaryPriceInsight?: PriceInsight | null;
    /**
     * 
     * @type {boolean}
     * @memberof StandardizedStayOffer
     */
    taxesFeesIncluded?: boolean | null;
}

/**
 * Check if a given object implements the StandardizedStayOffer interface.
 */
export function instanceOfStandardizedStayOffer(value: object): value is StandardizedStayOffer {
    return true;
}

export function StandardizedStayOfferFromJSON(json: any): StandardizedStayOffer {
    return StandardizedStayOfferFromJSONTyped(json, false);
}

export function StandardizedStayOfferFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandardizedStayOffer {
    if (json == null) {
        return json;
    }
    return {
        
        'checkInDate': json['check_in_date'] === undefined ? undefined : json['check_in_date'] === null ? null : json['check_in_date'],
        'checkOutDate': json['check_out_date'] === undefined ? undefined : json['check_out_date'] === null ? null : json['check_out_date'],
        'currency': json['currency'] === undefined ? undefined : json['currency'] === null ? null : json['currency'],
        'nightlyPrice': json['nightly_price'] === undefined ? undefined : json['nightly_price'] === null ? null : json['nightly_price'],
        'priceInsights': json['price_insights'] == null ? undefined : ((json['price_insights'] as Array<any>).map(PriceInsightFromJSON)),
        'priceTotal': json['price_total'] === undefined ? undefined : json['price_total'] === null ? null : json['price_total'],
        'primaryPriceInsight': json['primary_price_insight'] === undefined ? undefined : json['primary_price_insight'] === null ? null : PriceInsightFromJSON(json['primary_price_insight']),
        'taxesFeesIncluded': json['taxes_fees_included'] === undefined ? undefined : json['taxes_fees_included'] === null ? null : json['taxes_fees_included'],
    };
}

export function StandardizedStayOfferToJSON(json: any): StandardizedStayOffer {
    return StandardizedStayOfferToJSONTyped(json, false);
}

export function StandardizedStayOfferToJSONTyped(value?: StandardizedStayOffer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'check_in_date': value['checkInDate'],
        'check_out_date': value['checkOutDate'],
        'currency': value['currency'],
        'nightly_price': value['nightlyPrice'],
        'price_insights': value['priceInsights'] == null ? undefined : ((value['priceInsights'] as Array<any>).map(PriceInsightToJSON)),
        'price_total': value['priceTotal'],
        'primary_price_insight': PriceInsightToJSON(value['primaryPriceInsight']),
        'taxes_fees_included': value['taxesFeesIncluded'],
    };
}

