/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StandardizedFlightSegment } from './StandardizedFlightSegment';
import {
    StandardizedFlightSegmentFromJSON,
    StandardizedFlightSegmentFromJSONTyped,
    StandardizedFlightSegmentToJSON,
    StandardizedFlightSegmentToJSONTyped,
} from './StandardizedFlightSegment';

/**
 * 
 * @export
 * @interface StandardizedFlightLeg
 */
export interface StandardizedFlightLeg {
    /**
     * 
     * @type {string}
     * @memberof StandardizedFlightLeg
     */
    arrivalAirport?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StandardizedFlightLeg
     */
    arrivalTimeLocal?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StandardizedFlightLeg
     */
    arrivalTimeUtc?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof StandardizedFlightLeg
     */
    arrivalTimezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StandardizedFlightLeg
     */
    departureAirport?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StandardizedFlightLeg
     */
    departureTimeLocal?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StandardizedFlightLeg
     */
    departureTimeUtc?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof StandardizedFlightLeg
     */
    departureTimezone?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StandardizedFlightLeg
     */
    durationMinutes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StandardizedFlightLeg
     */
    layoverMinutesTotal?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StandardizedFlightLeg
     */
    legIndex: number;
    /**
     * 
     * @type {Array<StandardizedFlightSegment>}
     * @memberof StandardizedFlightLeg
     */
    segments: Array<StandardizedFlightSegment>;
    /**
     * 
     * @type {number}
     * @memberof StandardizedFlightLeg
     */
    stopCount?: number | null;
}

/**
 * Check if a given object implements the StandardizedFlightLeg interface.
 */
export function instanceOfStandardizedFlightLeg(value: object): value is StandardizedFlightLeg {
    if ((!('legIndex' in (value as Record<string, any>)) && !('leg_index' in (value as Record<string, any>))) || ((value as Record<string, any>)['legIndex'] === undefined && (value as Record<string, any>)['leg_index'] === undefined)) return false;
    if (!('segments' in value) || value['segments'] === undefined) return false;
    return true;
}

export function StandardizedFlightLegFromJSON(json: any): StandardizedFlightLeg {
    return StandardizedFlightLegFromJSONTyped(json, false);
}

export function StandardizedFlightLegFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandardizedFlightLeg {
    if (json == null) {
        return json;
    }
    return {
        
        'arrivalAirport': json['arrival_airport'] === undefined ? undefined : json['arrival_airport'] === null ? null : json['arrival_airport'],
        'arrivalTimeLocal': json['arrival_time_local'] === undefined ? undefined : json['arrival_time_local'] === null ? null : json['arrival_time_local'],
        'arrivalTimeUtc': json['arrival_time_utc'] === undefined ? undefined : json['arrival_time_utc'] === null ? null : (new Date(json['arrival_time_utc'])),
        'arrivalTimezone': json['arrival_timezone'] === undefined ? undefined : json['arrival_timezone'] === null ? null : json['arrival_timezone'],
        'departureAirport': json['departure_airport'] === undefined ? undefined : json['departure_airport'] === null ? null : json['departure_airport'],
        'departureTimeLocal': json['departure_time_local'] === undefined ? undefined : json['departure_time_local'] === null ? null : json['departure_time_local'],
        'departureTimeUtc': json['departure_time_utc'] === undefined ? undefined : json['departure_time_utc'] === null ? null : (new Date(json['departure_time_utc'])),
        'departureTimezone': json['departure_timezone'] === undefined ? undefined : json['departure_timezone'] === null ? null : json['departure_timezone'],
        'durationMinutes': json['duration_minutes'] === undefined ? undefined : json['duration_minutes'] === null ? null : json['duration_minutes'],
        'layoverMinutesTotal': json['layover_minutes_total'] === undefined ? undefined : json['layover_minutes_total'] === null ? null : json['layover_minutes_total'],
        'legIndex': json['leg_index'],
        'segments': ((json['segments'] as Array<any>).map(StandardizedFlightSegmentFromJSON)),
        'stopCount': json['stop_count'] === undefined ? undefined : json['stop_count'] === null ? null : json['stop_count'],
    };
}

export function StandardizedFlightLegToJSON(json: any): StandardizedFlightLeg {
    return StandardizedFlightLegToJSONTyped(json, false);
}

export function StandardizedFlightLegToJSONTyped(value?: StandardizedFlightLeg | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arrival_airport': value['arrivalAirport'],
        'arrival_time_local': value['arrivalTimeLocal'],
        'arrival_time_utc': value['arrivalTimeUtc'] == null ? value['arrivalTimeUtc'] : value['arrivalTimeUtc'].toISOString(),
        'arrival_timezone': value['arrivalTimezone'],
        'departure_airport': value['departureAirport'],
        'departure_time_local': value['departureTimeLocal'],
        'departure_time_utc': value['departureTimeUtc'] == null ? value['departureTimeUtc'] : value['departureTimeUtc'].toISOString(),
        'departure_timezone': value['departureTimezone'],
        'duration_minutes': value['durationMinutes'],
        'layover_minutes_total': value['layoverMinutesTotal'],
        'leg_index': value['legIndex'],
        'segments': ((value['segments'] as Array<any>).map(StandardizedFlightSegmentToJSON)),
        'stop_count': value['stopCount'],
    };
}

