/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlimStandardizedStay } from './SlimStandardizedStay';
import {
    SlimStandardizedStayFromJSON,
    SlimStandardizedStayFromJSONTyped,
    SlimStandardizedStayToJSON,
    SlimStandardizedStayToJSONTyped,
} from './SlimStandardizedStay';

/**
 * 
 * @export
 * @interface StayDetail
 */
export interface StayDetail {
    /**
     * 
     * @type {SlimStandardizedStay}
     * @memberof StayDetail
     */
    stay: SlimStandardizedStay;
}

/**
 * Check if a given object implements the StayDetail interface.
 */
export function instanceOfStayDetail(value: object): value is StayDetail {
    if (!('stay' in value) || value['stay'] === undefined) return false;
    return true;
}

export function StayDetailFromJSON(json: any): StayDetail {
    return StayDetailFromJSONTyped(json, false);
}

export function StayDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): StayDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'stay': SlimStandardizedStayFromJSON(json['stay']),
    };
}

export function StayDetailToJSON(json: any): StayDetail {
    return StayDetailToJSONTyped(json, false);
}

export function StayDetailToJSONTyped(value?: StayDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stay': SlimStandardizedStayToJSON(value['stay']),
    };
}

