/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StayTransportOption
 */
export interface StayTransportOption {
    /**
     * 
     * @type {number}
     * @memberof StayTransportOption
     */
    durationMinutes?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StayTransportOption
     */
    durationText: string;
    /**
     * 
     * @type {string}
     * @memberof StayTransportOption
     */
    mode: string;
}

/**
 * Check if a given object implements the StayTransportOption interface.
 */
export function instanceOfStayTransportOption(value: object): value is StayTransportOption {
    if ((!('durationText' in (value as Record<string, any>)) && !('duration_text' in (value as Record<string, any>))) || ((value as Record<string, any>)['durationText'] === undefined && (value as Record<string, any>)['duration_text'] === undefined)) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function StayTransportOptionFromJSON(json: any): StayTransportOption {
    return StayTransportOptionFromJSONTyped(json, false);
}

export function StayTransportOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StayTransportOption {
    if (json == null) {
        return json;
    }
    return {
        
        'durationMinutes': json['duration_minutes'] === undefined ? undefined : json['duration_minutes'] === null ? null : json['duration_minutes'],
        'durationText': json['duration_text'],
        'mode': json['mode'],
    };
}

export function StayTransportOptionToJSON(json: any): StayTransportOption {
    return StayTransportOptionToJSONTyped(json, false);
}

export function StayTransportOptionToJSONTyped(value?: StayTransportOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration_minutes': value['durationMinutes'],
        'duration_text': value['durationText'],
        'mode': value['mode'],
    };
}

