/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StayRatingBucket
 */
export interface StayRatingBucket {
    /**
     * 
     * @type {number}
     * @memberof StayRatingBucket
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof StayRatingBucket
     */
    stars: number;
}

/**
 * Check if a given object implements the StayRatingBucket interface.
 */
export function instanceOfStayRatingBucket(value: object): value is StayRatingBucket {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('stars' in value) || value['stars'] === undefined) return false;
    return true;
}

export function StayRatingBucketFromJSON(json: any): StayRatingBucket {
    return StayRatingBucketFromJSONTyped(json, false);
}

export function StayRatingBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): StayRatingBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'stars': json['stars'],
    };
}

export function StayRatingBucketToJSON(json: any): StayRatingBucket {
    return StayRatingBucketToJSONTyped(json, false);
}

export function StayRatingBucketToJSONTyped(value?: StayRatingBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'stars': value['stars'],
    };
}

