/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Public provider deal context for a stay.
 * 
 * This is display/explainability data only. It should not be treated as a
 * Voyager learned-price baseline.
 * @export
 * @interface StayDealSignal
 */
export interface StayDealSignal {
    /**
     * 
     * @type {string}
     * @memberof StayDealSignal
     */
    description?: string | null;
    /**
     * 
     * @type {StayDealSignalDirectionEnum}
     * @memberof StayDealSignal
     */
    direction?: StayDealSignalDirectionEnum | null;
    /**
     * 
     * @type {string}
     * @memberof StayDealSignal
     */
    label?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StayDealSignal
     */
    percentDelta?: number | null;
    /**
     * 
     * @type {StayDealSignalSourceEnum}
     * @memberof StayDealSignal
     */
    source?: StayDealSignalSourceEnum;
}


/**
 * @export
 */
export const StayDealSignalDirectionEnum = {
    BelowUsual: 'below_usual',
    AboveUsual: 'above_usual'
} as const;
export type StayDealSignalDirectionEnum = typeof StayDealSignalDirectionEnum[keyof typeof StayDealSignalDirectionEnum];

/**
 * @export
 */
export const StayDealSignalSourceEnum = {
    Provider: 'provider'
} as const;
export type StayDealSignalSourceEnum = typeof StayDealSignalSourceEnum[keyof typeof StayDealSignalSourceEnum];


/**
 * Check if a given object implements the StayDealSignal interface.
 */
export function instanceOfStayDealSignal(value: object): value is StayDealSignal {
    return true;
}

export function StayDealSignalFromJSON(json: any): StayDealSignal {
    return StayDealSignalFromJSONTyped(json, false);
}

export function StayDealSignalFromJSONTyped(json: any, ignoreDiscriminator: boolean): StayDealSignal {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'direction': json['direction'] === undefined ? undefined : json['direction'] === null ? null : json['direction'],
        'label': json['label'] === undefined ? undefined : json['label'] === null ? null : json['label'],
        'percentDelta': json['percent_delta'] === undefined ? undefined : json['percent_delta'] === null ? null : json['percent_delta'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function StayDealSignalToJSON(json: any): StayDealSignal {
    return StayDealSignalToJSONTyped(json, false);
}

export function StayDealSignalToJSONTyped(value?: StayDealSignal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'direction': value['direction'],
        'label': value['label'],
        'percent_delta': value['percentDelta'],
        'source': value['source'],
    };
}

