/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StayTransportOption } from './StayTransportOption';
import {
    StayTransportOptionFromJSON,
    StayTransportOptionFromJSONTyped,
    StayTransportOptionToJSON,
    StayTransportOptionToJSONTyped,
} from './StayTransportOption';

/**
 * 
 * @export
 * @interface StayNearbyPlace
 */
export interface StayNearbyPlace {
    /**
     * 
     * @type {string}
     * @memberof StayNearbyPlace
     */
    name: string;
    /**
     * 
     * @type {Array<StayTransportOption>}
     * @memberof StayNearbyPlace
     */
    transportations?: Array<StayTransportOption>;
}

/**
 * Check if a given object implements the StayNearbyPlace interface.
 */
export function instanceOfStayNearbyPlace(value: object): value is StayNearbyPlace {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StayNearbyPlaceFromJSON(json: any): StayNearbyPlace {
    return StayNearbyPlaceFromJSONTyped(json, false);
}

export function StayNearbyPlaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): StayNearbyPlace {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'transportations': json['transportations'] == null ? undefined : ((json['transportations'] as Array<any>).map(StayTransportOptionFromJSON)),
    };
}

export function StayNearbyPlaceToJSON(json: any): StayNearbyPlace {
    return StayNearbyPlaceToJSONTyped(json, false);
}

export function StayNearbyPlaceToJSONTyped(value?: StayNearbyPlace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'transportations': value['transportations'] == null ? undefined : ((value['transportations'] as Array<any>).map(StayTransportOptionToJSON)),
    };
}

