/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Only amenities with an existing provider parameter and post-filter.
 * @export
 * @interface StructuredStay
 */
export interface StructuredStay {
    /**
     * 
     * @type {Array<StructuredStayAmenitiesEnum>}
     * @memberof StructuredStay
     */
    amenities?: Array<StructuredStayAmenitiesEnum>;
    /**
     * 
     * @type {StructuredStayDirectionEnum}
     * @memberof StructuredStay
     */
    direction?: StructuredStayDirectionEnum;
    /**
     * 
     * @type {StructuredStayPropertyTypeEnum}
     * @memberof StructuredStay
     */
    propertyType?: StructuredStayPropertyTypeEnum | null;
}


/**
 * @export
 */
export const StructuredStayAmenitiesEnum = {
    FreeWifi: 'FREE_WIFI',
    Pool: 'POOL',
    AirConditioning: 'AIR_CONDITIONING',
    Parking: 'PARKING',
    PetsAllowed: 'PETS_ALLOWED',
    Spa: 'SPA',
    Gym: 'GYM',
    BreakfastIncluded: 'BREAKFAST_INCLUDED',
    Restaurant: 'RESTAURANT',
    Bar: 'BAR',
    RoomService: 'ROOM_SERVICE',
    WheelchairAccessible: 'WHEELCHAIR_ACCESSIBLE',
    BeachAccess: 'BEACH_ACCESS',
    AllInclusive: 'ALL_INCLUSIVE',
    ChildFriendly: 'CHILD_FRIENDLY',
    IndoorPool: 'INDOOR_POOL',
    OutdoorPool: 'OUTDOOR_POOL'
} as const;
export type StructuredStayAmenitiesEnum = typeof StructuredStayAmenitiesEnum[keyof typeof StructuredStayAmenitiesEnum];

/**
 * @export
 */
export const StructuredStayDirectionEnum = {
    Prefer: 'prefer',
    Must: 'must'
} as const;
export type StructuredStayDirectionEnum = typeof StructuredStayDirectionEnum[keyof typeof StructuredStayDirectionEnum];

/**
 * @export
 */
export const StructuredStayPropertyTypeEnum = {
    Resort: 'resort',
    Villa: 'villa',
    Apartment: 'apartment'
} as const;
export type StructuredStayPropertyTypeEnum = typeof StructuredStayPropertyTypeEnum[keyof typeof StructuredStayPropertyTypeEnum];


/**
 * Check if a given object implements the StructuredStay interface.
 */
export function instanceOfStructuredStay(value: object): value is StructuredStay {
    return true;
}

export function StructuredStayFromJSON(json: any): StructuredStay {
    return StructuredStayFromJSONTyped(json, false);
}

export function StructuredStayFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructuredStay {
    if (json == null) {
        return json;
    }
    return {
        
        'amenities': json['amenities'] == null ? undefined : json['amenities'],
        'direction': json['direction'] == null ? undefined : json['direction'],
        'propertyType': json['property_type'] === undefined ? undefined : json['property_type'] === null ? null : json['property_type'],
    };
}

export function StructuredStayToJSON(json: any): StructuredStay {
    return StructuredStayToJSONTyped(json, false);
}

export function StructuredStayToJSONTyped(value?: StructuredStay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amenities': value['amenities'],
        'direction': value['direction'],
        'property_type': value['propertyType'],
    };
}

