/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripPrice
 */
export interface TripPrice {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TripPrice
     */
    breakdown?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof TripPrice
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof TripPrice
     */
    total: number;
}

/**
 * Check if a given object implements the TripPrice interface.
 */
export function instanceOfTripPrice(value: object): value is TripPrice {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function TripPriceFromJSON(json: any): TripPrice {
    return TripPriceFromJSONTyped(json, false);
}

export function TripPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'breakdown': json['breakdown'] === undefined ? undefined : json['breakdown'] === null ? null : json['breakdown'],
        'currency': json['currency'],
        'total': json['total'],
    };
}

export function TripPriceToJSON(json: any): TripPrice {
    return TripPriceToJSONTyped(json, false);
}

export function TripPriceToJSONTyped(value?: TripPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'breakdown': value['breakdown'],
        'currency': value['currency'],
        'total': value['total'],
    };
}

