/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Location of a known external commitment.
 * 
 * MCP/agent callers may send a human place query when they do not know an MEP
 * UUID. Voyager resolves it through the existing canonical explicit-place policy.
 * @export
 * @interface TripAnchorDestination
 */
export interface TripAnchorDestination {
    /**
     * 
     * @type {string}
     * @memberof TripAnchorDestination
     */
    placeId?: string | null;
    /**
     * Place to resolve, e.g. 'Barcelona, Spain'. Use place_id when a canonical MyEscapePlan destination id is already known.
     * @type {string}
     * @memberof TripAnchorDestination
     */
    query?: string | null;
}

/**
 * Check if a given object implements the TripAnchorDestination interface.
 */
export function instanceOfTripAnchorDestination(value: object): value is TripAnchorDestination {
    return true;
}

export function TripAnchorDestinationFromJSON(json: any): TripAnchorDestination {
    return TripAnchorDestinationFromJSONTyped(json, false);
}

export function TripAnchorDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripAnchorDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'placeId': json['place_id'] === undefined ? undefined : json['place_id'] === null ? null : json['place_id'],
        'query': json['query'] === undefined ? undefined : json['query'] === null ? null : json['query'],
    };
}

export function TripAnchorDestinationToJSON(json: any): TripAnchorDestination {
    return TripAnchorDestinationToJSONTyped(json, false);
}

export function TripAnchorDestinationToJSONTyped(value?: TripAnchorDestination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'place_id': value['placeId'],
        'query': value['query'],
    };
}

