/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TripAnchorDestination } from './TripAnchorDestination';
import {
    TripAnchorDestinationFromJSON,
    TripAnchorDestinationFromJSONTyped,
    TripAnchorDestinationToJSON,
    TripAnchorDestinationToJSONTyped,
} from './TripAnchorDestination';
import type { TripAnchorPresence } from './TripAnchorPresence';
import {
    TripAnchorPresenceFromJSON,
    TripAnchorPresenceFromJSONTyped,
    TripAnchorPresenceToJSON,
    TripAnchorPresenceToJSONTyped,
} from './TripAnchorPresence';

/**
 * Known external commitment that a trip must satisfy.
 * 
 * MEP does not discover or verify this event/appointment. The caller provides
 * its known place and required local calendar dates. `cover` (the public default)
 * requires the trip to contain the complete date interval. `overlap` requires
 * at least one shared local calendar day.
 * @export
 * @interface TripAnchor
 */
export interface TripAnchor {
    /**
     * 
     * @type {TripAnchorDestination}
     * @memberof TripAnchor
     */
    destination: TripAnchorDestination;
    /**
     * Optional provenance/reference supplied by the caller. MEP does not fetch or reinterpret this reference during planning.
     * @type {string}
     * @memberof TripAnchor
     */
    externalReference?: string | null;
    /**
     * 
     * @type {TripAnchorModeEnum}
     * @memberof TripAnchor
     */
    mode?: TripAnchorModeEnum;
    /**
     * 
     * @type {TripAnchorPresence}
     * @memberof TripAnchor
     */
    requiredPresence: TripAnchorPresence;
    /**
     * 
     * @type {string}
     * @memberof TripAnchor
     */
    title?: string | null;
    /**
     * 
     * @type {TripAnchorTypeEnum}
     * @memberof TripAnchor
     */
    type?: TripAnchorTypeEnum;
}


/**
 * @export
 */
export const TripAnchorModeEnum = {
    Cover: 'cover',
    Overlap: 'overlap'
} as const;
export type TripAnchorModeEnum = typeof TripAnchorModeEnum[keyof typeof TripAnchorModeEnum];

/**
 * @export
 */
export const TripAnchorTypeEnum = {
    Event: 'event',
    Appointment: 'appointment',
    Cruise: 'cruise',
    Tour: 'tour',
    Other: 'other'
} as const;
export type TripAnchorTypeEnum = typeof TripAnchorTypeEnum[keyof typeof TripAnchorTypeEnum];


/**
 * Check if a given object implements the TripAnchor interface.
 */
export function instanceOfTripAnchor(value: object): value is TripAnchor {
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if ((!('requiredPresence' in (value as Record<string, any>)) && !('required_presence' in (value as Record<string, any>))) || ((value as Record<string, any>)['requiredPresence'] === undefined && (value as Record<string, any>)['required_presence'] === undefined)) return false;
    return true;
}

export function TripAnchorFromJSON(json: any): TripAnchor {
    return TripAnchorFromJSONTyped(json, false);
}

export function TripAnchorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripAnchor {
    if (json == null) {
        return json;
    }
    return {
        
        'destination': TripAnchorDestinationFromJSON(json['destination']),
        'externalReference': json['external_reference'] === undefined ? undefined : json['external_reference'] === null ? null : json['external_reference'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'requiredPresence': TripAnchorPresenceFromJSON(json['required_presence']),
        'title': json['title'] === undefined ? undefined : json['title'] === null ? null : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function TripAnchorToJSON(json: any): TripAnchor {
    return TripAnchorToJSONTyped(json, false);
}

export function TripAnchorToJSONTyped(value?: TripAnchor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destination': TripAnchorDestinationToJSON(value['destination']),
        'external_reference': value['externalReference'],
        'mode': value['mode'],
        'required_presence': TripAnchorPresenceToJSON(value['requiredPresence']),
        'title': value['title'],
        'type': value['type'],
    };
}

