/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Required local calendar dates for a known commitment.
 * 
 * V1 is intentionally date-grained. Voyager can guarantee that the trip covers
 * these local calendar dates, but it does not yet prove that a flight arrives
 * before an event's exact clock time. Upstream agents should therefore convert
 * known event timestamps to the event's local start/end dates.
 * @export
 * @interface TripAnchorPresence
 */
export interface TripAnchorPresence {
    /**
     * 
     * @type {Date}
     * @memberof TripAnchorPresence
     */
    endDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof TripAnchorPresence
     */
    startDate: Date;
}

/**
 * Check if a given object implements the TripAnchorPresence interface.
 */
export function instanceOfTripAnchorPresence(value: object): value is TripAnchorPresence {
    if ((!('endDate' in (value as Record<string, any>)) && !('end_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['endDate'] === undefined && (value as Record<string, any>)['end_date'] === undefined)) return false;
    if ((!('startDate' in (value as Record<string, any>)) && !('start_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['startDate'] === undefined && (value as Record<string, any>)['start_date'] === undefined)) return false;
    return true;
}

export function TripAnchorPresenceFromJSON(json: any): TripAnchorPresence {
    return TripAnchorPresenceFromJSONTyped(json, false);
}

export function TripAnchorPresenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripAnchorPresence {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': (new Date(json['end_date'])),
        'startDate': (new Date(json['start_date'])),
    };
}

export function TripAnchorPresenceToJSON(json: any): TripAnchorPresence {
    return TripAnchorPresenceToJSONTyped(json, false);
}

export function TripAnchorPresenceToJSONTyped(value?: TripAnchorPresence | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_date': value['endDate'].toISOString().substring(0,10),
        'start_date': value['startDate'].toISOString().substring(0,10),
    };
}

