/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeatherObservation
 */
export interface WeatherObservation {
    /**
     * 
     * @type {number}
     * @memberof WeatherObservation
     */
    avgTempC?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WeatherObservation
     */
    condition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WeatherObservation
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof WeatherObservation
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof WeatherObservation
     */
    maxTempC?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WeatherObservation
     */
    minTempC?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WeatherObservation
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof WeatherObservation
     */
    temperatureCelsius: number;
}

/**
 * Check if a given object implements the WeatherObservation interface.
 */
export function instanceOfWeatherObservation(value: object): value is WeatherObservation {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if ((!('temperatureCelsius' in (value as Record<string, any>)) && !('temperature_celsius' in (value as Record<string, any>))) || ((value as Record<string, any>)['temperatureCelsius'] === undefined && (value as Record<string, any>)['temperature_celsius'] === undefined)) return false;
    return true;
}

export function WeatherObservationFromJSON(json: any): WeatherObservation {
    return WeatherObservationFromJSONTyped(json, false);
}

export function WeatherObservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherObservation {
    if (json == null) {
        return json;
    }
    return {
        
        'avgTempC': json['avg_temp_c'] === undefined ? undefined : json['avg_temp_c'] === null ? null : json['avg_temp_c'],
        'condition': json['condition'] === undefined ? undefined : json['condition'] === null ? null : json['condition'],
        'date': json['date'],
        'description': json['description'],
        'maxTempC': json['max_temp_c'] === undefined ? undefined : json['max_temp_c'] === null ? null : json['max_temp_c'],
        'minTempC': json['min_temp_c'] === undefined ? undefined : json['min_temp_c'] === null ? null : json['min_temp_c'],
        'source': json['source'],
        'temperatureCelsius': json['temperature_celsius'],
    };
}

export function WeatherObservationToJSON(json: any): WeatherObservation {
    return WeatherObservationToJSONTyped(json, false);
}

export function WeatherObservationToJSONTyped(value?: WeatherObservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_temp_c': value['avgTempC'],
        'condition': value['condition'],
        'date': value['date'],
        'description': value['description'],
        'max_temp_c': value['maxTempC'],
        'min_temp_c': value['minTempC'],
        'source': value['source'],
        'temperature_celsius': value['temperatureCelsius'],
    };
}

