"""
    MyEscapePlan Business Travel API

    External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

NAME = "myescapeplan"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">= 3.10"
# pyproject.toml is authoritative for modern PEP 517 builds; keep this
# metadata aligned for legacy setup.py users.
REQUIRES = [
    "python-dateutil >= 2.8.2",
    "httpx >= 0.28.1",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="MyEscapePlan Business Travel API",
    author="MyEscapePlan",
    author_email="engineering@myescapeplan.app",
    url="https://github.com/myescapeplan/myescapeplan-sdk",
    license="MIT",
    keywords=["MyEscapePlan", "Business Travel API", "SDK"],
    project_urls={
        "Homepage": "https://github.com/myescapeplan/myescapeplan-sdk#readme",
        "Issues": "https://github.com/myescapeplan/myescapeplan-sdk/issues",
        "Repository": "https://github.com/myescapeplan/myescapeplan-sdk",
    },
    python_requires=PYTHON_REQUIRES,
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type="text/markdown",
    long_description="""\
External MyEscapePlan Travel Discovery and verified-search API.
Authenticate with X-API-KEY.
""",
    package_data={"myescapeplan": ["py.typed"]},
)
