"""
    MyEscapePlan Business Travel API

    Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning. Discovery ranks destination/date opportunities before inventory shopping; optional Verified Search performs provider-backed checks. Authenticate with X-API-KEY.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

NAME = "myescapeplan"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">= 3.10"
# pyproject.toml is authoritative for modern PEP 517 builds; keep this
# metadata aligned for legacy setup.py users.
REQUIRES = [
    "python-dateutil >= 2.8.2",
    "httpx >= 0.28.1",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Travel discovery API SDK for natural-language travel search and destination recommendation",
    author="MyEscapePlan",
    author_email="engineering@myescapeplan.app",
    url="https://github.com/myescapeplan/myescapeplan-sdk",
    license="MIT",
    keywords=["MyEscapePlan", "travel API", "travel discovery", "travel planning", "travel search", "destination recommendation", "AI travel", "Python SDK"],
    project_urls={
        "Homepage": "https://business.myescapeplan.app/developers",
        "Documentation": "https://business.myescapeplan.app/developers",
        "Discovery": "https://business.myescapeplan.app/discovery",
        "Issues": "https://github.com/myescapeplan/myescapeplan-sdk/issues",
        "Repository": "https://github.com/myescapeplan/myescapeplan-sdk",
    },
    python_requires=PYTHON_REQUIRES,
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type="text/markdown",
    long_description="""\
MyEscapePlan Travel Discovery API for natural-language travel search, destination recommendation and flexible-date planning.
Canonical documentation: https://business.myescapeplan.app/developers
""",
    package_data={"myescapeplan": ["py.typed"]},
)
