/* tslint:disable */
/* eslint-disable */
/**
 * MyEscapePlan Business Travel API
 * External MyEscapePlan Travel Discovery and verified-search API. Authenticate with X-API-KEY.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BusinessErrorEnvelope,
    BusinessErrorEnvelopeFromJSON,
    BusinessErrorEnvelopeToJSON,
} from '../models/BusinessErrorEnvelope';
import {
    type BusinessJobResource,
    BusinessJobResourceFromJSON,
    BusinessJobResourceToJSON,
} from '../models/BusinessJobResource';
import {
    type BusinessJobStatus,
    BusinessJobStatusFromJSON,
    BusinessJobStatusToJSON,
} from '../models/BusinessJobStatus';
import {
    type BusinessResultDetail,
    BusinessResultDetailFromJSON,
    BusinessResultDetailToJSON,
} from '../models/BusinessResultDetail';
import {
    type BusinessSearchCreateRequest,
    BusinessSearchCreateRequestFromJSON,
    BusinessSearchCreateRequestToJSON,
} from '../models/BusinessSearchCreateRequest';
import {
    type BusinessSearchListResponse,
    BusinessSearchListResponseFromJSON,
    BusinessSearchListResponseToJSON,
} from '../models/BusinessSearchListResponse';
import {
    type BusinessSearchResult,
    BusinessSearchResultFromJSON,
    BusinessSearchResultToJSON,
} from '../models/BusinessSearchResult';
import {
    type BusinessSearchResultsResponse,
    BusinessSearchResultsResponseFromJSON,
    BusinessSearchResultsResponseToJSON,
} from '../models/BusinessSearchResultsResponse';
import {
    type BusinessUsageResponse,
    BusinessUsageResponseFromJSON,
    BusinessUsageResponseToJSON,
} from '../models/BusinessUsageResponse';
import {
    type DiscoveryDestinationLookupResponse,
    DiscoveryDestinationLookupResponseFromJSON,
    DiscoveryDestinationLookupResponseToJSON,
} from '../models/DiscoveryDestinationLookupResponse';
import {
    type DiscoveryRequest,
    DiscoveryRequestFromJSON,
    DiscoveryRequestToJSON,
} from '../models/DiscoveryRequest';
import {
    type DiscoveryResponse,
    DiscoveryResponseFromJSON,
    DiscoveryResponseToJSON,
} from '../models/DiscoveryResponse';

export interface CancelSearchRequest {
    searchId: string;
}

export interface CreateDiscoveryRequest {
    idempotencyKey: string;
    discoveryRequest: DiscoveryRequest;
}

export interface CreateSearchRequest {
    idempotencyKey: string;
    businessSearchCreateRequest: BusinessSearchCreateRequest;
    xClientReference?: string | null;
}

export interface GetSearchRequest {
    searchId: string;
}

export interface GetSearchResultRequest {
    searchId: string;
    resultId: string;
}

export interface GetSearchResultDetailsRequest {
    searchId: string;
    resultId: string;
    dateOptionId?: string | null;
}

export interface GetSearchResultsRequest {
    searchId: string;
}

export interface ListSearchesRequest {
    status?: BusinessJobStatus | null;
    clientReference?: string | null;
    createdAfter?: Date | null;
    createdBefore?: Date | null;
    limit?: number;
    cursor?: string | null;
}

export interface LookupDestinationsRequest {
    q: string;
    limit?: number;
}

/**
 * BusinessTravelAPIApi - interface
 * 
 * @export
 * @interface BusinessTravelAPIApiInterface
 */
export interface BusinessTravelAPIApiInterface {
    /**
     * Creates request options for cancelSearch without sending the request
     * @param {string} searchId 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    cancelSearchRequestOpts(requestParameters: CancelSearchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Cancel a verified business search
     * @param {string} searchId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    cancelSearchRaw(requestParameters: CancelSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessJobResource>>;

    /**
     * Cancel a verified business search
     */
    cancelSearch(requestParameters: CancelSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessJobResource>;

    /**
     * Creates request options for createDiscovery without sending the request
     * @param {string} idempotencyKey 
     * @param {DiscoveryRequest} discoveryRequest 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    createDiscoveryRequestOpts(requestParameters: CreateDiscoveryRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Discover destination/date opportunities without live shopping
     * @param {string} idempotencyKey 
     * @param {DiscoveryRequest} discoveryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    createDiscoveryRaw(requestParameters: CreateDiscoveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiscoveryResponse>>;

    /**
     * Discover destination/date opportunities without live shopping
     */
    createDiscovery(requestParameters: CreateDiscoveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiscoveryResponse>;

    /**
     * Creates request options for createSearch without sending the request
     * @param {string} idempotencyKey 
     * @param {BusinessSearchCreateRequest} businessSearchCreateRequest 
     * @param {string} [xClientReference] 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    createSearchRequestOpts(requestParameters: CreateSearchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a detached verified business travel search
     * @param {string} idempotencyKey 
     * @param {BusinessSearchCreateRequest} businessSearchCreateRequest 
     * @param {string} [xClientReference] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    createSearchRaw(requestParameters: CreateSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessJobResource>>;

    /**
     * Create a detached verified business travel search
     */
    createSearch(requestParameters: CreateSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessJobResource>;

    /**
     * Creates request options for getSearch without sending the request
     * @param {string} searchId 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getSearchRequestOpts(requestParameters: GetSearchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get verified-search status
     * @param {string} searchId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getSearchRaw(requestParameters: GetSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessJobResource>>;

    /**
     * Get verified-search status
     */
    getSearch(requestParameters: GetSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessJobResource>;

    /**
     * Creates request options for getSearchResult without sending the request
     * @param {string} searchId 
     * @param {string} resultId 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getSearchResultRequestOpts(requestParameters: GetSearchResultRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get one canonical verified result
     * @param {string} searchId 
     * @param {string} resultId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getSearchResultRaw(requestParameters: GetSearchResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessSearchResult>>;

    /**
     * Get one canonical verified result
     */
    getSearchResult(requestParameters: GetSearchResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessSearchResult>;

    /**
     * Creates request options for getSearchResultDetails without sending the request
     * @param {string} searchId 
     * @param {string} resultId 
     * @param {string} [dateOptionId] 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getSearchResultDetailsRequestOpts(requestParameters: GetSearchResultDetailsRequest): Promise<runtime.RequestOpts>;

    /**
     * Return the consumer-grade detail payload for a Business result.
     * @summary Get rich details for one verified result
     * @param {string} searchId 
     * @param {string} resultId 
     * @param {string} [dateOptionId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getSearchResultDetailsRaw(requestParameters: GetSearchResultDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessResultDetail>>;

    /**
     * Return the consumer-grade detail payload for a Business result.
     * Get rich details for one verified result
     */
    getSearchResultDetails(requestParameters: GetSearchResultDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessResultDetail>;

    /**
     * Creates request options for getSearchResults without sending the request
     * @param {string} searchId 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getSearchResultsRequestOpts(requestParameters: GetSearchResultsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get canonical verified travel results
     * @param {string} searchId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getSearchResultsRaw(requestParameters: GetSearchResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessSearchResultsResponse>>;

    /**
     * Get canonical verified travel results
     */
    getSearchResults(requestParameters: GetSearchResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessSearchResultsResponse>;

    /**
     * Creates request options for getUsage without sending the request
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getUsageRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get current Business API usage and allowances
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    getUsageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessUsageResponse>>;

    /**
     * Get current Business API usage and allowances
     */
    getUsage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessUsageResponse>;

    /**
     * Creates request options for listSearches without sending the request
     * @param {BusinessJobStatus} [status] 
     * @param {string} [clientReference] 
     * @param {Date} [createdAfter] Inclusive ISO-8601 lower bound with timezone.
     * @param {Date} [createdBefore] Exclusive ISO-8601 upper bound with timezone.
     * @param {number} [limit] 
     * @param {string} [cursor] 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    listSearchesRequestOpts(requestParameters: ListSearchesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List verified business searches
     * @param {BusinessJobStatus} [status] 
     * @param {string} [clientReference] 
     * @param {Date} [createdAfter] Inclusive ISO-8601 lower bound with timezone.
     * @param {Date} [createdBefore] Exclusive ISO-8601 upper bound with timezone.
     * @param {number} [limit] 
     * @param {string} [cursor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    listSearchesRaw(requestParameters: ListSearchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessSearchListResponse>>;

    /**
     * List verified business searches
     */
    listSearches(requestParameters: ListSearchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessSearchListResponse>;

    /**
     * Creates request options for lookupDestinations without sending the request
     * @param {string} q Destination name or prefix to resolve.
     * @param {number} [limit] 
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    lookupDestinationsRequestOpts(requestParameters: LookupDestinationsRequest): Promise<runtime.RequestOpts>;

    /**
     * Return canonical destination IDs safe to pass back as destination_ids.
     * @summary Resolve destinations from the active Discovery planner snapshot
     * @param {string} q Destination name or prefix to resolve.
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessTravelAPIApiInterface
     */
    lookupDestinationsRaw(requestParameters: LookupDestinationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiscoveryDestinationLookupResponse>>;

    /**
     * Return canonical destination IDs safe to pass back as destination_ids.
     * Resolve destinations from the active Discovery planner snapshot
     */
    lookupDestinations(requestParameters: LookupDestinationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiscoveryDestinationLookupResponse>;

}

/**
 * 
 */
export class BusinessTravelAPIApi extends runtime.BaseAPI implements BusinessTravelAPIApiInterface {

    /**
     * Creates request options for cancelSearch without sending the request
     */
    async cancelSearchRequestOpts(requestParameters: CancelSearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['searchId'] == null) {
            throw new runtime.RequiredError(
                'searchId',
                'Required parameter "searchId" was null or undefined when calling cancelSearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/searches/{search_id}`;
        urlPath = urlPath.replace('{search_id}', encodeURIComponent(String(requestParameters['searchId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel a verified business search
     */
    async cancelSearchRaw(requestParameters: CancelSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessJobResource>> {
        const requestOptions = await this.cancelSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessJobResourceFromJSON(jsonValue));
    }

    /**
     * Cancel a verified business search
     */
    async cancelSearch(requestParameters: CancelSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessJobResource> {
        const response = await this.cancelSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createDiscovery without sending the request
     */
    async createDiscoveryRequestOpts(requestParameters: CreateDiscoveryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createDiscovery().'
            );
        }

        if (requestParameters['discoveryRequest'] == null) {
            throw new runtime.RequiredError(
                'discoveryRequest',
                'Required parameter "discoveryRequest" was null or undefined when calling createDiscovery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/discovery`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DiscoveryRequestToJSON(requestParameters['discoveryRequest']),
        };
    }

    /**
     * Discover destination/date opportunities without live shopping
     */
    async createDiscoveryRaw(requestParameters: CreateDiscoveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiscoveryResponse>> {
        const requestOptions = await this.createDiscoveryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiscoveryResponseFromJSON(jsonValue));
    }

    /**
     * Discover destination/date opportunities without live shopping
     */
    async createDiscovery(requestParameters: CreateDiscoveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiscoveryResponse> {
        const response = await this.createDiscoveryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSearch without sending the request
     */
    async createSearchRequestOpts(requestParameters: CreateSearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createSearch().'
            );
        }

        if (requestParameters['businessSearchCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'businessSearchCreateRequest',
                'Required parameter "businessSearchCreateRequest" was null or undefined when calling createSearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['xClientReference'] != null) {
            headerParameters['X-Client-Reference'] = String(requestParameters['xClientReference']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/searches`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BusinessSearchCreateRequestToJSON(requestParameters['businessSearchCreateRequest']),
        };
    }

    /**
     * Create a detached verified business travel search
     */
    async createSearchRaw(requestParameters: CreateSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessJobResource>> {
        const requestOptions = await this.createSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessJobResourceFromJSON(jsonValue));
    }

    /**
     * Create a detached verified business travel search
     */
    async createSearch(requestParameters: CreateSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessJobResource> {
        const response = await this.createSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSearch without sending the request
     */
    async getSearchRequestOpts(requestParameters: GetSearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['searchId'] == null) {
            throw new runtime.RequiredError(
                'searchId',
                'Required parameter "searchId" was null or undefined when calling getSearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/searches/{search_id}`;
        urlPath = urlPath.replace('{search_id}', encodeURIComponent(String(requestParameters['searchId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get verified-search status
     */
    async getSearchRaw(requestParameters: GetSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessJobResource>> {
        const requestOptions = await this.getSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessJobResourceFromJSON(jsonValue));
    }

    /**
     * Get verified-search status
     */
    async getSearch(requestParameters: GetSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessJobResource> {
        const response = await this.getSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSearchResult without sending the request
     */
    async getSearchResultRequestOpts(requestParameters: GetSearchResultRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['searchId'] == null) {
            throw new runtime.RequiredError(
                'searchId',
                'Required parameter "searchId" was null or undefined when calling getSearchResult().'
            );
        }

        if (requestParameters['resultId'] == null) {
            throw new runtime.RequiredError(
                'resultId',
                'Required parameter "resultId" was null or undefined when calling getSearchResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/searches/{search_id}/results/{result_id}`;
        urlPath = urlPath.replace('{search_id}', encodeURIComponent(String(requestParameters['searchId'])));
        urlPath = urlPath.replace('{result_id}', encodeURIComponent(String(requestParameters['resultId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one canonical verified result
     */
    async getSearchResultRaw(requestParameters: GetSearchResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessSearchResult>> {
        const requestOptions = await this.getSearchResultRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessSearchResultFromJSON(jsonValue));
    }

    /**
     * Get one canonical verified result
     */
    async getSearchResult(requestParameters: GetSearchResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessSearchResult> {
        const response = await this.getSearchResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSearchResultDetails without sending the request
     */
    async getSearchResultDetailsRequestOpts(requestParameters: GetSearchResultDetailsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['searchId'] == null) {
            throw new runtime.RequiredError(
                'searchId',
                'Required parameter "searchId" was null or undefined when calling getSearchResultDetails().'
            );
        }

        if (requestParameters['resultId'] == null) {
            throw new runtime.RequiredError(
                'resultId',
                'Required parameter "resultId" was null or undefined when calling getSearchResultDetails().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateOptionId'] != null) {
            queryParameters['date_option_id'] = requestParameters['dateOptionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/searches/{search_id}/results/{result_id}/details`;
        urlPath = urlPath.replace('{search_id}', encodeURIComponent(String(requestParameters['searchId'])));
        urlPath = urlPath.replace('{result_id}', encodeURIComponent(String(requestParameters['resultId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the consumer-grade detail payload for a Business result.
     * Get rich details for one verified result
     */
    async getSearchResultDetailsRaw(requestParameters: GetSearchResultDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessResultDetail>> {
        const requestOptions = await this.getSearchResultDetailsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessResultDetailFromJSON(jsonValue));
    }

    /**
     * Return the consumer-grade detail payload for a Business result.
     * Get rich details for one verified result
     */
    async getSearchResultDetails(requestParameters: GetSearchResultDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessResultDetail> {
        const response = await this.getSearchResultDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSearchResults without sending the request
     */
    async getSearchResultsRequestOpts(requestParameters: GetSearchResultsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['searchId'] == null) {
            throw new runtime.RequiredError(
                'searchId',
                'Required parameter "searchId" was null or undefined when calling getSearchResults().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/searches/{search_id}/results`;
        urlPath = urlPath.replace('{search_id}', encodeURIComponent(String(requestParameters['searchId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get canonical verified travel results
     */
    async getSearchResultsRaw(requestParameters: GetSearchResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessSearchResultsResponse>> {
        const requestOptions = await this.getSearchResultsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessSearchResultsResponseFromJSON(jsonValue));
    }

    /**
     * Get canonical verified travel results
     */
    async getSearchResults(requestParameters: GetSearchResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessSearchResultsResponse> {
        const response = await this.getSearchResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUsage without sending the request
     */
    async getUsageRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/usage`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get current Business API usage and allowances
     */
    async getUsageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessUsageResponse>> {
        const requestOptions = await this.getUsageRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessUsageResponseFromJSON(jsonValue));
    }

    /**
     * Get current Business API usage and allowances
     */
    async getUsage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessUsageResponse> {
        const response = await this.getUsageRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSearches without sending the request
     */
    async listSearchesRequestOpts(requestParameters: ListSearchesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['clientReference'] != null) {
            queryParameters['client_reference'] = requestParameters['clientReference'];
        }

        if (requestParameters['createdAfter'] != null) {
            queryParameters['created_after'] = (requestParameters['createdAfter'] as any).toISOString();
        }

        if (requestParameters['createdBefore'] != null) {
            queryParameters['created_before'] = (requestParameters['createdBefore'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/searches`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List verified business searches
     */
    async listSearchesRaw(requestParameters: ListSearchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessSearchListResponse>> {
        const requestOptions = await this.listSearchesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessSearchListResponseFromJSON(jsonValue));
    }

    /**
     * List verified business searches
     */
    async listSearches(requestParameters: ListSearchesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessSearchListResponse> {
        const response = await this.listSearchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for lookupDestinations without sending the request
     */
    async lookupDestinationsRequestOpts(requestParameters: LookupDestinationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling lookupDestinations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // BusinessApiKey authentication
        }


        let urlPath = `/api/v1/business/discovery/destinations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return canonical destination IDs safe to pass back as destination_ids.
     * Resolve destinations from the active Discovery planner snapshot
     */
    async lookupDestinationsRaw(requestParameters: LookupDestinationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiscoveryDestinationLookupResponse>> {
        const requestOptions = await this.lookupDestinationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiscoveryDestinationLookupResponseFromJSON(jsonValue));
    }

    /**
     * Return canonical destination IDs safe to pass back as destination_ids.
     * Resolve destinations from the active Discovery planner snapshot
     */
    async lookupDestinations(requestParameters: LookupDestinationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiscoveryDestinationLookupResponse> {
        const response = await this.lookupDestinationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
